// AI: below section was generated by an AI
//
// Pairing v2 LAN signing, checked against the shared vectors (epixc-backend
// shared/lan-auth/vectors.json, copied to test/pixc/vectors/lan_auth_vectors.json). Every request
// and reply vector is recomputed with wled00/pixc_lan_auth.h, and every request is also run through
// verify() the way the device handles it: accepted once, refused as a replay, refused under a
// different boot id, and refused with any byte of the MAC changed.
#include <cstdio>
#include <cstring>
#include <fstream>
#include <sstream>
#include <string>

#include "test_check.h"
#include "pixc_lan_auth.h"
#include "src/dependencies/json/ArduinoJson-v6.h"

using namespace pixc::lan;

static std::string readFile(const char* path) {
  std::ifstream f(path, std::ios::binary);
  std::stringstream ss;
  ss << f.rdbuf();
  return ss.str();
}

void testLanAuthVectors() {
  const std::string json = readFile(PIXC_VECTORS_PATH);
  CHECK(!json.empty());
  DynamicJsonDocument doc(32768);
  CHECK(!deserializeJson(doc, json));

  int requests = 0, replies = 0;
  for (JsonObject v : doc["requests"].as<JsonArray>()) {
    requests++;
    const char* key = v["lan_key"];
    const char* body = v["body_utf8"];
    const uint32_t ctr = v["ctr"];
    char bh[65];
    bodyHashHex(reinterpret_cast<const uint8_t*>(body), strlen(body), bh);
    CHECK(strcmp(bh, v["body_sha256"].as<const char*>()) == 0);
    char mac[kMacB64Len + 1];
    CHECK(requestMac(key, v["method"], v["path_and_query"], v["boot_id"], ctr, v["client_id"], bh, mac));
    const bool macOk = strcmp(mac, v["mac_b64"].as<const char*>()) == 0;
    CHECK(macOk);
    if (!macOk) std::fprintf(stderr, "  vector '%s': got %s\n", v["name"].as<const char*>(), mac);

    // The header parses back to the same fields.
    ParsedAuth pa;
    CHECK(parseAuthHeader(v["header"], pa));
    CHECK(strcmp(pa.clientId, v["client_id"].as<const char*>()) == 0);
    CHECK(strcmp(pa.bootId, v["boot_id"].as<const char*>()) == 0);
    CHECK(pa.ctr == ctr);

    // The device's verify(): accepted, then a replay, then wrong boot, then a tampered MAC.
    ReplayTable rt;
    const uint8_t* b = reinterpret_cast<const uint8_t*>(body);
    const size_t bl = strlen(body);
    CHECK(verify(v["header"], key, "", v["boot_id"], v["method"], v["path_and_query"], b, bl, rt, nullptr) == Verdict::Ok);
    CHECK(verify(v["header"], key, "", v["boot_id"], v["method"], v["path_and_query"], b, bl, rt, nullptr) == Verdict::Replay);
    ReplayTable fresh;
    CHECK(verify(v["header"], key, "", "00000000", v["method"], v["path_and_query"], b, bl, fresh, nullptr) == Verdict::StaleBoot);
    std::string bad = v["header"].as<std::string>();
    bad[bad.size() - 2] = bad[bad.size() - 2] == 'A' ? 'B' : 'A';
    CHECK(verify(bad.c_str(), key, "", v["boot_id"], v["method"], v["path_and_query"], b, bl, fresh, nullptr) == Verdict::Unauthorised);
    // A different body, path or method under the same header is refused.
    CHECK(verify(v["header"], key, "", v["boot_id"], v["method"], "/json/cfg", b, bl, fresh, nullptr) == Verdict::Unauthorised);
    CHECK(verify(v["header"], key, "", v["boot_id"], "PUT", v["path_and_query"], b, bl, fresh, nullptr) == Verdict::Unauthorised);
    // No key on the device: nothing verifies.
    CHECK(verify(v["header"], "", "", v["boot_id"], v["method"], v["path_and_query"], b, bl, fresh, nullptr) == Verdict::NoKey);
    // Signed with the key before a rotation: refused, but told apart so it is not counted.
    CHECK(verify(v["header"], "ffffffffffffffffffffffffffffffff", key, v["boot_id"], v["method"], v["path_and_query"], b, bl, fresh, nullptr) == Verdict::PreviousKey);
  }
  // Each refusal has its own code, so a client can tell a stale key (re-read it) from a wrong one.
  CHECK(strcmp(verdictCode(Verdict::PreviousKey), "STALE_KEY") == 0);
  CHECK(strcmp(verdictCode(Verdict::StaleBoot), "STALE_BOOT") == 0);
  CHECK(strcmp(verdictCode(Verdict::Replay), "REPLAY") == 0);
  CHECK(strcmp(verdictCode(Verdict::Unauthorised), "UNAUTHORISED") == 0);
  // The Wi-Fi password the phone hands over: open, a passphrase of 8-63, or a 64-hex PSK.
  const std::string hex64(64, 'a'), hex64Upper(64, 'F'), notHex64 = std::string(63, 'a') + "g";
  CHECK(validPsk("", 0));
  CHECK(!validPsk("1234567", 7));
  CHECK(validPsk("12345678", 8));
  CHECK(validPsk(std::string(63, 'x').c_str(), 63));
  CHECK(validPsk(hex64.c_str(), 64));
  CHECK(validPsk(hex64Upper.c_str(), 64));
  CHECK(!validPsk(notHex64.c_str(), 64));
  CHECK(!validPsk(std::string(65, 'a').c_str(), 65));
  for (JsonObject v : doc["replies"].as<JsonArray>()) {
    replies++;
    const char* body = v["body_utf8"];
    char bh[65];
    bodyHashHex(reinterpret_cast<const uint8_t*>(body), strlen(body), bh);
    CHECK(strcmp(bh, v["body_sha256"].as<const char*>()) == 0);
    char sig[kMacB64Len + 1];
    CHECK(replySig(v["lan_key"], v["boot_id"], v["ctr"], v["client_id"], bh, sig));
    CHECK(strcmp(sig, v["sig_b64"].as<const char*>()) == 0);
    CHECK(std::string("v2 ") + sig == v["header"].as<std::string>());
  }
  CHECK(requests >= 6);
  CHECK(replies >= 2);
  std::printf("  lan auth vectors: %d requests, %d replies\n", requests, replies);

  // The replay table: strictly increasing per client, 16 clients, least recently used out.
  ReplayTable rt;
  CHECK(rt.fresh("aaaaaaaaaaaaaaaa", 1));
  rt.accept("aaaaaaaaaaaaaaaa", 5);
  CHECK(!rt.fresh("aaaaaaaaaaaaaaaa", 5));
  CHECK(!rt.fresh("aaaaaaaaaaaaaaaa", 4));
  CHECK(rt.fresh("aaaaaaaaaaaaaaaa", 6));
  char id[17];
  for (int i = 0; i < 16; i++) {                      // 16 other clients push the first one out
    std::snprintf(id, sizeof(id), "%016x", 0x1000 + i);
    rt.accept(id, 1);
  }
  CHECK(rt.fresh("aaaaaaaaaaaaaaaa", 1));             // the accepted residual risk (design doc)

  // No LAN factory reset (founder, 2026-09-25): /json/pixc/reset is routed exactly like any other
  // unknown /json/pixc path - to the one signed 404 - and the state/config paths are not.
  CHECK(isPixcNamespace("/json/pixc/reset"));
  CHECK(isPixcNamespace("/json/pixc/unknown"));
  CHECK(isPixcNamespace("/json/pixc"));
  CHECK(!isPixcNamespace("/json"));
  CHECK(!isPixcNamespace("/json/state"));
  CHECK(!isPixcNamespace("/json/cfg"));
  CHECK(!isPixcNamespace(nullptr));
  CHECK(strcmp(kNotFoundBody, "{\"error\":\"NOT_FOUND\"}") == 0);
  {
    // A correctly signed request to it still reaches that 404: the signature verifies (it is a
    // valid request), and routing - not auth - is what refuses it.
    const char* key = "000102030405060708090a0b0c0d0e0f";
    const char* body = "{\"reset\":true}";
    char bh[65], mac[kMacB64Len + 1];
    bodyHashHex(reinterpret_cast<const uint8_t*>(body), strlen(body), bh);
    CHECK(requestMac(key, "POST", "/json/pixc/reset", "5eed1e55", 1, "8b1f2c3d4e5f6a7b", bh, mac));
    const std::string hdr = std::string("v2 8b1f2c3d4e5f6a7b:5eed1e55:1:") + mac;
    ReplayTable rt2;
    CHECK(verify(hdr.c_str(), key, "", "5eed1e55", "POST", "/json/pixc/reset",
                 reinterpret_cast<const uint8_t*>(body), strlen(body), rt2, nullptr) == Verdict::Ok);
    CHECK(isPixcNamespace("/json/pixc/reset") == isPixcNamespace("/json/pixc/no-such-thing"));
  }

  // Header parsing is strict.
  ParsedAuth pa;
  CHECK(!parseAuthHeader("v1 8b1f2c3d4e5f6a7b:5eed1e55:1:C1SCV/RrXLyvz1dmq0nUAJYiysrkbCoOTiM1r90/jyk=", pa));
  CHECK(!parseAuthHeader("v2 8b1f2c3d4e5f6a7b:5eed1e55:01:C1SCV/RrXLyvz1dmq0nUAJYiysrkbCoOTiM1r90/jyk=", pa));
  CHECK(!parseAuthHeader("v2 8b1f2c3d4e5f6a7b:5eed1e55:0:C1SCV/RrXLyvz1dmq0nUAJYiysrkbCoOTiM1r90/jyk=", pa));
  CHECK(!parseAuthHeader("v2 8B1F2C3D4E5F6A7B:5eed1e55:1:C1SCV/RrXLyvz1dmq0nUAJYiysrkbCoOTiM1r90/jyk=", pa));
  CHECK(!parseAuthHeader("v2 8b1f2c3d4e5f6a7b:5eed1e55:4294967296:C1SCV/RrXLyvz1dmq0nUAJYiysrkbCoOTiM1r90/jyk=", pa));
  CHECK(!parseAuthHeader("v2 8b1f2c3d4e5f6a7b:5eed1e55:1:short", pa));
  CHECK(!parseAuthHeader(nullptr, pa));
}
// AI: end
