// AI: below section was generated by an AI
//
// Host-side unit tests for the ePixC firmware's pure logic (usermods/pixc_connect_blink/pixc_logic.h
// and wled00/pixc_lan_guard.h). No test framework on purpose: this has to build with nothing but a
// C++17 compiler, on a laptop and in CI, so a missing dependency can never be the reason it did
// not run. Run with test/pixc/run.sh; a non-zero exit is a failure.

#include <cstdio>
#include <cstdlib>
#include <cstring>

#include "pixc_logic.h"

static int g_failures = 0;
static int g_checks = 0;

#define CHECK(cond)                                                              \
  do {                                                                           \
    ++g_checks;                                                                  \
    if (!(cond)) {                                                               \
      ++g_failures;                                                              \
      std::fprintf(stderr, "%s:%d: CHECK failed: %s\n", __FILE__, __LINE__, #cond); \
    }                                                                            \
  } while (0)

// ---------------------------------------------------------------------------------------------
// S1: the usermod must see its own topics after WLED strips the device prefix.
// ---------------------------------------------------------------------------------------------
static void testClassifyTopic() {
  using pixc::Topic;
  const char* base = "epixc/v1/d/aabbccddeeff";

  // What WLED actually delivers (mqtt.cpp strips mqttDeviceTopic). This is the case that was dead.
  CHECK(pixc::classifyTopic("/cfg", base) == Topic::Cfg);
  CHECK(pixc::classifyTopic("/reset", base) == Topic::Reset);
  CHECK(pixc::classifyTopic("/ota", base) == Topic::Ota);

  // The unstripped form, for a delivery path that does not strip.
  CHECK(pixc::classifyTopic("epixc/v1/d/aabbccddeeff/cfg", base) == Topic::Cfg);
  CHECK(pixc::classifyTopic("epixc/v1/d/aabbccddeeff/ota", base) == Topic::Ota);

  // Exact match only: our own publish topic is not a command, and near-misses are nothing.
  CHECK(pixc::classifyTopic("/ota/progress", base) == Topic::None);
  CHECK(pixc::classifyTopic("epixc/v1/d/aabbccddeeff/ota/progress", base) == Topic::None);
  CHECK(pixc::classifyTopic("/cfgX", base) == Topic::None);
  CHECK(pixc::classifyTopic("/api", base) == Topic::None);
  CHECK(pixc::classifyTopic("", base) == Topic::None);
  CHECK(pixc::classifyTopic(nullptr, base) == Topic::None);

  // Another device's topic must never match, stripped or not.
  CHECK(pixc::classifyTopic("epixc/v1/d/001122334455/cfg", base) == Topic::None);

  // The old matcher's bug, pinned: a strstr for the FULL topic inside "/cfg" can never succeed.
  CHECK(std::strstr("/cfg", "epixc/v1/d/aabbccddeeff/cfg") == nullptr);

  // No base configured: only the stripped form can match.
  CHECK(pixc::classifyTopic("/reset", "") == Topic::Reset);
  CHECK(pixc::classifyTopic("/reset", nullptr) == Topic::Reset);
}

// ---------------------------------------------------------------------------------------------
// B2: debug output must never carry the PIN or a password, even on a dev build.
// ---------------------------------------------------------------------------------------------
static void redacts(const char* in, const char* want) {
  char buf[512];
  std::snprintf(buf, sizeof(buf), "%s", in);
  pixc::redactJsonSecrets(buf);
  const bool ok = std::strcmp(buf, want) == 0;
  CHECK(ok);
  if (!ok) std::fprintf(stderr, "  in:   %s\n  got:  %s\n  want: %s\n", in, buf, want);
}

static void testRedaction() {
  // The cloud /cfg payload that carries the rotated PIN (DeviceService.buildCfg).
  redacts(R"({"def":{"bri":191},"um":{"PixcConnect":{"settingsPin":"4821"}}})",
          R"({"def":{"bri":191},"um":{"PixcConnect":{"settingsPin":"****"}}})");
  // The LAN body the app sends with every request.
  redacts(R"({"on":true,"pin":"1234"})", R"({"on":true,"pin":"****"})");
  // MQTT credential push and Wi-Fi provisioning.
  redacts(R"({"if":{"mqtt":{"en":true,"user":"aabbccddeeff","psk":"0123abcd"}}})",
          R"({"if":{"mqtt":{"en":true,"user":"aabbccddeeff","psk":"********"}}})");
  redacts(R"({"nw":{"ins":[{"ssid":"Home","psk":"hunter2"}]}})",
          R"({"nw":{"ins":[{"ssid":"Home","psk":"*******"}]}})");
  // Bare values, whitespace, mixed case, escapes.
  redacts(R"({"PIN" : 1234, "bri":5})", R"({"PIN" : ****, "bri":5})");
  redacts(R"({"password":"a\"b"})", R"({"password":"****"})");
  redacts(R"({"ota":{"pwd":"wledota"}})", R"({"ota":{"pwd":"*******"}})");
  // Values that merely LOOK like secret keys are left alone; so is non-secret data.
  redacts(R"({"ssid":"pin","v":true})", R"({"ssid":"pin","v":true})");
  redacts(R"({"seg":[{"col":[[255,0,0]]}]})", R"({"seg":[{"col":[[255,0,0]]}]})");
  // Truncated input must not read past the terminator.
  redacts(R"({"pin":"12)", R"({"pin":"**)");
  redacts(R"({"pi)", R"({"pi)");
  CHECK(pixc::isSecretKey("mqttPass", 8));
  CHECK(pixc::isSecretKey("lan_secret", 10));
  CHECK(!pixc::isSecretKey("ping", 4));
  CHECK(!pixc::isSecretKey("user", 4));
}

int main() {
  testClassifyTopic();
  testRedaction();
  if (g_failures == 0) {
    std::printf("pixc host tests: %d checks passed\n", g_checks);
    return EXIT_SUCCESS;
  }
  std::fprintf(stderr, "pixc host tests: %d of %d checks FAILED\n", g_failures, g_checks);
  return EXIT_FAILURE;
}
// AI: end
