// AI: below section was generated by an AI
//
// Host-side unit tests for the ePixC firmware's pure logic (usermods/pixc_connect_blink/pixc_logic.h
// and wled00/pixc_lan_guard.h). No test framework on purpose: this has to build with nothing but a
// C++17 compiler, on a laptop and in CI, so a missing dependency can never be the reason it did
// not run. Run with test/pixc/run.sh; a non-zero exit is a failure.

#include <cstdio>
#include <cstdlib>
#include <cstring>

#include "pixc_logic.h"
#include "pixc_lan_guard.h"

static int g_failures = 0;
static int g_checks = 0;

#define CHECK(cond)                                                              \
  do {                                                                           \
    ++g_checks;                                                                  \
    if (!(cond)) {                                                               \
      ++g_failures;                                                              \
      std::fprintf(stderr, "%s:%d: CHECK failed: %s\n", __FILE__, __LINE__, #cond); \
    }                                                                            \
  } while (0)

// ---------------------------------------------------------------------------------------------
// S1: the usermod must see its own topics after WLED strips the device prefix.
// ---------------------------------------------------------------------------------------------
static void testClassifyTopic() {
  using pixc::Topic;
  const char* base = "epixc/v1/d/aabbccddeeff";

  // What WLED actually delivers (mqtt.cpp strips mqttDeviceTopic). This is the case that was dead.
  CHECK(pixc::classifyTopic("/cfg", base) == Topic::Cfg);
  CHECK(pixc::classifyTopic("/reset", base) == Topic::Reset);
  CHECK(pixc::classifyTopic("/ota", base) == Topic::Ota);

  // The unstripped form, for a delivery path that does not strip.
  CHECK(pixc::classifyTopic("epixc/v1/d/aabbccddeeff/cfg", base) == Topic::Cfg);
  CHECK(pixc::classifyTopic("epixc/v1/d/aabbccddeeff/ota", base) == Topic::Ota);

  // Exact match only: our own publish topic is not a command, and near-misses are nothing.
  CHECK(pixc::classifyTopic("/ota/progress", base) == Topic::None);
  CHECK(pixc::classifyTopic("epixc/v1/d/aabbccddeeff/ota/progress", base) == Topic::None);
  CHECK(pixc::classifyTopic("/cfgX", base) == Topic::None);
  CHECK(pixc::classifyTopic("/api", base) == Topic::None);
  CHECK(pixc::classifyTopic("", base) == Topic::None);
  CHECK(pixc::classifyTopic(nullptr, base) == Topic::None);

  // Another device's topic must never match, stripped or not.
  CHECK(pixc::classifyTopic("epixc/v1/d/001122334455/cfg", base) == Topic::None);

  // The old matcher's bug, pinned: a strstr for the FULL topic inside "/cfg" can never succeed.
  CHECK(std::strstr("/cfg", "epixc/v1/d/aabbccddeeff/cfg") == nullptr);

  // No base configured: only the stripped form can match.
  CHECK(pixc::classifyTopic("/reset", "") == Topic::Reset);
  CHECK(pixc::classifyTopic("/reset", nullptr) == Topic::Reset);
}

// ---------------------------------------------------------------------------------------------
// B2: debug output must never carry the PIN or a password, even on a dev build.
// ---------------------------------------------------------------------------------------------
static void redacts(const char* in, const char* want) {
  char buf[512];
  std::snprintf(buf, sizeof(buf), "%s", in);
  pixc::redactJsonSecrets(buf);
  const bool ok = std::strcmp(buf, want) == 0;
  CHECK(ok);
  if (!ok) std::fprintf(stderr, "  in:   %s\n  got:  %s\n  want: %s\n", in, buf, want);
}

static void testRedaction() {
  // The cloud /cfg payload that carries the rotated PIN (DeviceService.buildCfg).
  redacts(R"({"def":{"bri":191},"um":{"PixcConnect":{"settingsPin":"4821"}}})",
          R"({"def":{"bri":191},"um":{"PixcConnect":{"settingsPin":"****"}}})");
  // The LAN body the app sends with every request.
  redacts(R"({"on":true,"pin":"1234"})", R"({"on":true,"pin":"****"})");
  // MQTT credential push and Wi-Fi provisioning.
  redacts(R"({"if":{"mqtt":{"en":true,"user":"aabbccddeeff","psk":"0123abcd"}}})",
          R"({"if":{"mqtt":{"en":true,"user":"aabbccddeeff","psk":"********"}}})");
  redacts(R"({"nw":{"ins":[{"ssid":"Home","psk":"hunter2"}]}})",
          R"({"nw":{"ins":[{"ssid":"Home","psk":"*******"}]}})");
  // Bare values, whitespace, mixed case, escapes.
  redacts(R"({"PIN" : 1234, "bri":5})", R"({"PIN" : ****, "bri":5})");
  redacts(R"({"password":"a\"b"})", R"({"password":"****"})");
  redacts(R"({"ota":{"pwd":"wledota"}})", R"({"ota":{"pwd":"*******"}})");
  // Values that merely LOOK like secret keys are left alone; so is non-secret data.
  redacts(R"({"ssid":"pin","v":true})", R"({"ssid":"pin","v":true})");
  redacts(R"({"seg":[{"col":[[255,0,0]]}]})", R"({"seg":[{"col":[[255,0,0]]}]})");
  // Truncated input must not read past the terminator.
  redacts(R"({"pin":"12)", R"({"pin":"**)");
  redacts(R"({"pi)", R"({"pi)");
  CHECK(pixc::isSecretKey("mqttPass", 8));
  CHECK(pixc::isSecretKey("lan_secret", 10));
  CHECK(!pixc::isSecretKey("ping", 4));
  CHECK(!pixc::isSecretKey("user", 4));
}

// ---------------------------------------------------------------------------------------------
// S3: per-address backoff and a global ceiling that never locks out a correct PIN elsewhere.
// ---------------------------------------------------------------------------------------------
// An address on 192.168.1.0/24 as lwIP stores it on a little-endian CPU (first octet low byte).
static uint32_t lanIp(uint8_t host) { return 192u | (168u << 8) | (1u << 16) | (uint32_t(host) << 24); }

static void testPinGuardBackoff() {
  pixc::PinGuard g;
  const uint32_t a = lanIp(66);
  uint64_t t = 1000000;
  CHECK(g.mayTry(a, t));
  g.onWrong(a, t);
  uint64_t wait = 0;
  CHECK(!g.mayTry(a, t + 999, &wait));
  CHECK(wait == 1);
  CHECK(g.mayTry(a, t + 1000));
  g.onWrong(a, t + 1000);                       // 2nd: 2 s
  CHECK(!g.mayTry(a, t + 2999));
  CHECK(g.mayTry(a, t + 3000));
  g.onWrong(a, t + 3000);                       // 3rd: 4 s
  CHECK(!g.mayTry(a, t + 6999));
  CHECK(g.mayTry(a, t + 7000));
  g.onRight(a);                                 // a right PIN forgives the address
  g.onWrong(a, t + 7000);
  CHECK(g.mayTry(a, t + 8000));                 // back to 1 s
}

static void testPinGuardOwnerNeverLockedOut() {
  pixc::PinGuard g;
  const uint32_t attacker = lanIp(66), owner = lanIp(20), sync = lanIp(21);
  uint64_t t = 5000;
  int ownerRefused = 0;
  // A day of an attacker guessing as fast as it is allowed, every 100 ms, while the owner's app
  // and Sync talk to the light every second with the right PIN.
  for (uint64_t ms = 0; ms < 24ULL * 3600 * 1000; ms += 100) {
    if (g.mayTry(attacker, t + ms)) g.onWrong(attacker, t + ms);
    if (ms % 1000 == 0) {
      if (g.mayTry(owner, t + ms)) g.onRight(owner); else ownerRefused++;
      if (g.mayTry(sync, t + ms)) g.onRight(sync); else ownerRefused++;
    }
  }
  CHECK(ownerRefused == 0);
}

static void testPinGuardCeiling() {
  // A single address: the backoff alone keeps it to a few dozen guesses a day.
  {
    pixc::PinGuard g;
    int guesses = 0;
    for (uint64_t ms = 0; ms < 24ULL * 3600 * 1000; ms += 100) {
      if (g.mayTry(lanIp(66), ms + 1)) { g.onWrong(lanIp(66), ms + 1); guesses++; }
    }
    std::printf("  single-host attacker: %d wrong guesses/day\n", guesses);
    CHECK(guesses <= 40);
  }
  // Every address of the /24, rotating as fast as allowed: bounded by budget + one per address.
  {
    pixc::PinGuard g;
    int guesses = 0;
    for (uint64_t sec = 0; sec < 24ULL * 3600; sec++) {
      for (int h = 1; h < 255; h++) {
        const uint64_t now = sec * 1000 + 1;
        if (g.mayTry(lanIp(uint8_t(h)), now)) { g.onWrong(lanIp(uint8_t(h)), now); guesses++; }
      }
    }
    std::printf("  whole-/24 attacker:   %d wrong guesses/day\n", guesses);
    CHECK(guesses <= pixc::PinGuard::kBudgetBurst + 96 + 256);
    CHECK(guesses >= 100);                      // and the bound is not vacuous
  }
  // With the budget spent, a fresh host is still heard exactly once.
  {
    pixc::PinGuard g;
    for (int i = 0; i < 40; i++) {
      const uint32_t ip = lanIp(uint8_t(100 + i));
      if (g.mayTry(ip, 10)) g.onWrong(ip, 10);
    }
    CHECK(g.tokens() == 0);
    CHECK(g.mayTry(lanIp(200), 10));            // never failed: evaluated
    g.onWrong(lanIp(200), 10);
    CHECK(!g.mayTry(lanIp(200), 2000));         // failed with no budget: refused until a token
    CHECK(g.mayTry(lanIp(201), 2000));          // a different fresh host: still heard
  }
}

int main() {
  testClassifyTopic();
  testRedaction();
  testPinGuardBackoff();
  testPinGuardOwnerNeverLockedOut();
  testPinGuardCeiling();
  if (g_failures == 0) {
    std::printf("pixc host tests: %d checks passed\n", g_checks);
    return EXIT_SUCCESS;
  }
  std::fprintf(stderr, "pixc host tests: %d of %d checks FAILED\n", g_failures, g_checks);
  return EXIT_FAILURE;
}
// AI: end
