// AI: below section was generated by an AI
//
// The pure parts of wled00/pixc_lan.cpp (wled00/pixc_lan_logic.h): the pairing endpoint's body
// validation and 409 rule, the hotspot subnet, DDP lease slots and expiry, the signed
// PATH_AND_QUERY, and the LAN config sanitiser.
#include <cstdio>
#include <cstring>
#include <string>
#include <utility>
#include <vector>

#include "test_check.h"
#include "pixc_lan_logic.h"
#include "src/dependencies/json/ArduinoJson-v6.h"

using namespace pixc::lan;

// An address as lwIP stores it (first octet in the low byte).
static uint32_t ip4(uint8_t a, uint8_t b, uint8_t c, uint8_t d) {
  return uint32_t(a) | (uint32_t(b) << 8) | (uint32_t(c) << 16) | (uint32_t(d) << 24);
}

static const char* kDev = "00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff";
static const char* kLan = "000102030405060708090a0b0c0d0e0f";

static void testPairValidation() {
  CHECK(validPairBody("Home", "hunter22", kDev, kLan));
  CHECK(validPairBody("H", "", kDev, kLan));                             // an open network
  CHECK(validPairBody(std::string(32, 's').c_str(), std::string(63, 'p').c_str(), kDev, kLan));
  CHECK(validPairBody("Home", "00112233445566778899aabbccddeeff00112233445566778899AABBCCDDEEFF", kDev, kLan));
  // SSID: empty or over 32 bytes.
  CHECK(!validPairBody("", "hunter22", kDev, kLan));
  CHECK(!validPairBody(std::string(33, 's').c_str(), "hunter22", kDev, kLan));
  // Wi-Fi key: 1-7, 64 non-hex, over 64.
  CHECK(!validPairBody("Home", "short", kDev, kLan));
  CHECK(!validPairBody("Home", std::string(64, 'z').c_str(), kDev, kLan));
  CHECK(!validPairBody("Home", std::string(65, 'a').c_str(), kDev, kLan));
  // Keys: exact length, lowercase hex only.
  CHECK(!validPairBody("Home", "hunter22", "00", kLan));
  CHECK(!validPairBody("Home", "hunter22", kDev, "000102030405060708090a0b0c0d0e0"));
  CHECK(!validPairBody("Home", "hunter22", kDev, "000102030405060708090a0b0c0d0e0f0"));
  CHECK(!validPairBody("Home", "hunter22", kDev, "000102030405060708090A0B0C0D0E0F"));
  CHECK(!validPairBody("Home", "hunter22", std::string(64, 'g').c_str(), kLan));
  CHECK(!validPairBody(nullptr, "hunter22", kDev, kLan));
  CHECK(!validPairBody("Home", "hunter22", nullptr, kLan));
  // Body size: 1..1024.
  CHECK(!pairBodySizeOk(0));
  CHECK(pairBodySizeOk(1));
  CHECK(pairBodySizeOk(1024));
  CHECK(!pairBodySizeOk(1025));
}

static void testPairConflict() {
  char storedLan[33], storedDev[65];
  std::strcpy(storedLan, kLan);
  std::strcpy(storedDev, kDev);
  // A new light pairs with anyone on its hotspot.
  CHECK(!pairConflicts(false, "", "", kLan, kDev));
  // The wrong-password retry: same phone, same keys.
  CHECK(!pairConflicts(true, storedLan, storedDev, kLan, kDev));
  // A member or Sync (k_lan, but not k_dev), a stranger (neither), or a mix: 409.
  const std::string otherDev(64, 'a'), otherLan(32, 'b');
  CHECK(pairConflicts(true, storedLan, storedDev, kLan, otherDev.c_str()));
  CHECK(pairConflicts(true, storedLan, storedDev, otherLan.c_str(), kDev));
  CHECK(pairConflicts(true, storedLan, storedDev, otherLan.c_str(), otherDev.c_str()));
  // One differing nibble anywhere in either key.
  for (size_t i = 0; i < 64; i++) {
    std::string d(kDev);
    d[i] = d[i] == 'f' ? 'e' : 'f';
    CHECK(pairConflicts(true, storedLan, storedDev, kLan, d.c_str()));
    if (i < 32) {
      std::string l(kLan);
      l[i] = l[i] == 'f' ? 'e' : 'f';
      CHECK(pairConflicts(true, storedLan, storedDev, l.c_str(), kDev));
    }
  }
}

static void testHotspotSubnet() {
  CHECK(onHotspotSubnet(ip4(4, 3, 2, 1)));
  CHECK(onHotspotSubnet(ip4(4, 3, 2, 254)));
  CHECK(!onHotspotSubnet(ip4(4, 3, 3, 1)));
  CHECK(!onHotspotSubnet(ip4(192, 168, 1, 20)));
  CHECK(!onHotspotSubnet(ip4(1, 2, 3, 4)));      // the octets in the wrong order
  CHECK(!onHotspotSubnet(0));
}

static void testLeases() {
  const uint32_t sync = ip4(192, 168, 1, 21), app = ip4(192, 168, 1, 20);
  // Granted, capped at 120 s, expired exactly on time.
  {
    LeaseTable t;
    CHECK(!t.allowed(sync, 1000));
    t.grant(sync, 60, 1000);
    CHECK(t.allowed(sync, 1000));
    CHECK(t.allowed(sync, 60999));
    CHECK(!t.allowed(sync, 61000));
    CHECK(!t.allowed(app, 2000));                  // only the leaseholder
    t.grant(sync, 100000, 70000);
    CHECK(t.allowed(sync, 70000 + 119999));
    CHECK(!t.allowed(sync, 70000 + 120000));
  }
  // Renewal keeps one slot; release frees it; a negative request is a release; 0.0.0.0 never.
  {
    LeaseTable t;
    for (uint32_t now = 0; now < 600000; now += 20000) t.grant(sync, 60, now);
    CHECK(t.allowed(sync, 600000));
    t.grant(sync, 0, 600001);
    CHECK(!t.allowed(sync, 600002));
    t.grant(sync, 30, 700000);
    t.grant(sync, -5, 700001);
    CHECK(!t.allowed(sync, 700002));
    t.grant(0, 60, 700000);
    CHECK(!t.allowed(0, 700001));
  }
  // Four holders fit; a fifth takes the lease ending soonest, never a live one ending later.
  {
    LeaseTable t;
    const uint32_t h[5] = {ip4(10, 0, 0, 1), ip4(10, 0, 0, 2), ip4(10, 0, 0, 3), ip4(10, 0, 0, 4), ip4(10, 0, 0, 5)};
    t.grant(h[0], 100, 0);
    t.grant(h[1], 30, 0);                           // ends soonest
    t.grant(h[2], 110, 0);
    t.grant(h[3], 120, 0);
    for (int i = 0; i < 4; i++) CHECK(t.allowed(h[i], 1000));
    t.grant(h[4], 60, 1000);
    CHECK(t.allowed(h[4], 1000));
    CHECK(!t.allowed(h[1], 1000));                  // evicted
    CHECK(t.allowed(h[0], 1000) && t.allowed(h[2], 1000) && t.allowed(h[3], 1000));
  }
  // An expired slot is reused before any live one is evicted.
  {
    LeaseTable t;
    for (uint8_t i = 1; i <= 4; i++) t.grant(ip4(10, 0, 0, i), i == 3 ? 5 : 120, 0);
    t.grant(ip4(10, 0, 0, 9), 60, 10000);           // 10.0.0.3 expired at 5 s
    for (uint8_t i : {1, 2, 4, 9}) CHECK(t.allowed(ip4(10, 0, 0, i), 10000));
  }
  // A releasing stranger removes nothing.
  {
    LeaseTable t;
    t.grant(sync, 60, 0);
    t.grant(app, 0, 10);
    CHECK(t.allowed(sync, 20));
  }
  // Across the millis() wrap: a lease granted just before it lasts its full time.
  {
    LeaseTable t;
    const uint32_t now = 0xFFFFFFFFu - 5000u;
    t.grant(sync, 60, now);
    CHECK(t.allowed(sync, now + 59999u));
    CHECK(!t.allowed(sync, now + 60000u));
  }
}

// ---------------------------------------------------------------------------------------------
// PATH_AND_QUERY: exact when nothing was decoded, refused otherwise.
// ---------------------------------------------------------------------------------------------
struct P { const char* name; const char* value; bool skip; };
static bool pq(const char* path, std::vector<P> params, std::string& out) {
  return buildPathAndQuery(out, path, params.size(), [&params](size_t i) {
    return QueryParam{params[i].name, params[i].value, params[i].skip};
  });
}

static void testPathAndQuery() {
  std::string out;
  CHECK(pq("/json/state", {}, out) && out == "/json/state");
  CHECK(pq("/json/state", {{"v", "1", false}}, out) && out == "/json/state?v=1");
  CHECK(pq("/json", {{"a", "1", false}, {"b", "x.y_z~-", false}}, out) && out == "/json?a=1&b=x.y_z~-");
  CHECK(pq("/json", {{"flag", "", false}}, out) && out == "/json?flag=");       // "?flag" signs as this
  // POST fields and files are not part of the request line.
  CHECK(pq("/json", {{"body", "x", true}, {"v", "1", false}}, out) && out == "/json?v=1");
  // Anything the server percent-decoded cannot be rebuilt byte for byte: refused.
  CHECK(!pq("/json/st ate", {}, out));
  CHECK(!pq("/json/%73tate", {}, out));
  CHECK(!pq("/json", {{"v", "a b", false}}, out));
  CHECK(!pq("/json", {{"v", "a+b", false}}, out));
  CHECK(!pq("/json", {{"v", "a&b=c", false}}, out));
  CHECK(!pq("/json", {{"v/x", "1", false}}, out));                             // '/' only in the path
  CHECK(!pq("/json", {{"v", "\xc3\xa9", false}}, out));                        // UTF-8, decoded
  CHECK(!pq(nullptr, {}, out));
  CHECK(unreserved("/json/pixc/pair", true));
  CHECK(!unreserved("/json/pixc/pair", false));
}

static void testSanitizeLanCfg() {
  DynamicJsonDocument doc(2048);
  CHECK(!deserializeJson(doc, R"({
    "id":{"name":"Desk"},
    "if":{"mqtt":{"en":true,"broker":"evil"},"ntp":{"en":true}},
    "ap":{"ssid":"x","psk":"y"},
    "ota":{"lock":false},
    "pin":"1234",
    "pixc":{"lan":"00"},
    "um":{"PixcConnect":{"settingsPin":"k"},"AudioReactive":{"sync":{"mode":2}}},
    "hw":{"led":{"maxpwr":4000}}
  })"));
  sanitizeLanCfg(doc.as<JsonObject>());
  JsonObject r = doc.as<JsonObject>();
  CHECK(r["if"]["mqtt"].isNull());
  CHECK(r["if"]["ntp"]["en"] == true);              // the rest of "if" stays
  CHECK(r["ap"].isNull() && r["ota"].isNull() && r["pin"].isNull() && r["pixc"].isNull());
  CHECK(r["um"]["PixcConnect"].isNull());
  CHECK(r["um"]["AudioReactive"]["sync"]["mode"] == 2);
  CHECK(r["id"]["name"] == "Desk");
  CHECK(r["hw"]["led"]["maxpwr"] == 4000);
  // A body without any of them is left alone, and a non-object "if" or "um" does not crash.
  DynamicJsonDocument d2(256);
  CHECK(!deserializeJson(d2, R"({"if":5,"um":"x","bri":9})"));
  sanitizeLanCfg(d2.as<JsonObject>());
  CHECK(d2["bri"] == 9);
}

void testLanLogic() {
  testPairValidation();
  testPairConflict();
  testHotspotSubnet();
  testLeases();
  testPathAndQuery();
  testSanitizeLanCfg();
}
// AI: end
