# AI: below section was generated by an AI
#
# ePixC build identity (audit C4 and S6). Defines, for every source file:
#
#   PIXC_FW_BUILD  a monotonic build number. It is compiled into the image's build descriptor
#                  (usermods/pixc_connect_blink/pixc_logic.h, BuildDesc), which the ECDSA signature
#                  covers, and a unit refuses an OTA image whose number is lower than its own.
#                  CI sets EPIXC_BUILD_NUMBER (github.run_number plus a fixed offset, so it only
#                  ever grows); a local build uses the commit count of HEAD.
#   PIXC_FW_GIT    `git describe --always --dirty` - which source this image came from, reported in
#                  the announce and boot event so two images with the same package.json version can
#                  be told apart.
#
# The security version (the anti-rollback floor) is not derived here: it is PIXC_SECURITY_VERSION
# in pixc_logic.h, raised by hand when a release fixes a vulnerability that must never come back.
import os
import subprocess

Import("env")  # noqa: F821 (provided by PlatformIO/SCons)


def _git(*args):
    try:
        return subprocess.run(["git", *args], capture_output=True, text=True, check=True,
                              cwd=env.subst("$PROJECT_DIR")).stdout.strip()  # noqa: F821
    except Exception:
        return ""


number = os.environ.get("EPIXC_BUILD_NUMBER", "").strip()
if not number.isdigit():
    count = _git("rev-list", "--count", "HEAD")
    number = count if count.isdigit() else "0"
describe = _git("describe", "--always", "--dirty", "--abbrev=10") or "unknown"
# Keep it a safe C string and short enough for the MQTT payloads it is copied into.
describe = "".join(c for c in describe if c.isalnum() or c in "-._+")[:40]

env.Append(CPPDEFINES=[  # noqa: F821
    ("PIXC_FW_BUILD", number),
    ("PIXC_FW_GIT", '\\"%s\\"' % describe),
])
print("ePixC build %s (%s)" % (number, describe))
# AI: end
