#pragma once

// AI: below section was generated by an AI
//
// Pairing and LAN security v2 on the device: the signed LAN API, the pairing endpoint, the realtime
// lease and the keys. Vault: 05-Firmware/Pairing and LAN security v2. Compiled with PIXC_LAN_AUTH.
//
//   GET  /json/id           unauthenticated: {"mac","boot_id","v":2}
//   GET  /json/pixc/pair    hotspot only: {"mac","fw","leds","state":"new"|"keyed"}
//   POST /json/pixc/pair    hotspot only: {"ssid","psk","k_dev","k_lan"[,"api_host"]} -> 200 {"mac"},
//                           409 ALREADY_PAIRED, 400 on a malformed body; then reboots
//   every other /json*      X-PixC-Auth v2 required; replies carry X-PixC-Sig v2
//   POST /json {"pixc":{"rt_lease":N}}   realtime (DDP) lease for the caller, N <= 120 s
//   POST /json/pixc/reset {"reset":true} factory reset
//
// The LAN key is written at pairing and by the cloud (um.PixcConnect.settingsPin), never by a LAN
// config write, and is never returned by any interface.

#include <Arduino.h>
#include <stddef.h>
#include <stdint.h>

#include "pixc_lan_auth.h"

class AsyncWebServer;
class AsyncWebServerRequest;
class AsyncWebServerResponse;

// What a verified request needs for its reply signature.
struct PixcReplySigner {
  bool active = false;
  char clientId[pixc::lan::kClientIdLen + 1] = "";
  uint32_t ctr = 0;
};

// Streams bytes into SHA-256, so a JSON reply is hashed as ArduinoJson will send it, with no copy.
class PixcHashPrint : public Print {
 public:
  size_t write(uint8_t c) override { _s.update(&c, 1); return 1; }
  size_t write(const uint8_t* b, size_t n) override { _s.update(b, n); return n; }
  void hex(char out[65]) { uint8_t d[32]; _s.finish(d); pixc::lan::toHex(d, 32, out); }
 private:
  pixc::lan::Sha256 _s;
};

// Verify the request's X-PixC-Auth over `body`. On failure the 401 (or 429) reply has been sent and
// false is returned; on success `out` is filled for signing the reply.
bool pixcAuthorise(AsyncWebServerRequest* request, const uint8_t* body, size_t len, PixcReplySigner& out);

// Add X-PixC-Sig for a reply whose body hashes to `bodyHashHex`. No-op for an inactive signer.
void pixcSignResponse(AsyncWebServerResponse* response, const PixcReplySigner& signer, const char* bodyHashHex);
// Send a small signed reply.
void pixcSendSigned(AsyncWebServerRequest* request, const PixcReplySigner& signer, int code,
                    const char* contentType, const char* body);

// /json/id and /json/pixc/pair. Call before the generic /json handlers are registered: those
// match every /json/... prefix.
void pixcRegisterRoutes(AsyncWebServer& server);

// A verified POST /json{,/pixc/reset} that carries ePixC's own keys: the realtime lease and the
// factory reset. Returns true if it answered the request; strips the `pixc` key otherwise.
bool pixcHandleAuthedPost(AsyncWebServerRequest* request, JsonObject root, const PixcReplySigner& signer);

// Remove what a LAN /json/cfg write may not change: the broker (if.mqtt), the access point, the
// usermod's provisioning keys, OTA settings, the settings PIN and ePixC's own section.
void pixcSanitizeLanCfg(JsonObject root);

// The LAN key from the cloud (32 lowercase hex). Keeps the previous key for one grace purpose only:
// a request signed with it is not counted against its sender. Returns true if the key changed.
bool pixcSetLanKey(const char* keyHex);
bool pixcIsKeyed();

// wsec.json: the device key and the LAN key.
void pixcSerializeSecrets(JsonObject root);
void pixcDeserializeSecrets(JsonObject root);

// DDP is accepted only from an address holding a lease (e131.cpp).
bool pixcRealtimeAllowed(uint32_t ip);

// The caller's IPv4 address as lwIP stores it (first octet in the low byte).
uint32_t pixcCallerIp(AsyncWebServerRequest* request);
// AI: end
