#include "wled.h"

#ifdef PIXC_LAN_AUTH

// AI: below section was generated by an AI
#include "pixc_lan.h"
#include "pixc_lan_guard.h"
#include "pixc_device.h"
#include "../usermods/pixc_connect_blink/pixc_logic.h"

namespace {

pixc::lan::ReplayTable replay;
// A per-address brake on hosts sending bad signatures - no global ceiling (a 128-bit key cannot be
// guessed at any rate) and two free failures, so the one request a client signs with the key
// before a rotation costs nothing.
pixc::PinGuard authGuard(false, 2);
char previousLanKey[pixc::lan::kKeyHexLen + 1] = "";

constexpr uint8_t kLeases = 4;
constexpr uint16_t kLeaseMaxS = 120;
struct Lease { uint32_t ip; uint32_t until; };   // until: millis()
Lease leases[kLeases];

uint64_t nowMs64() { return static_cast<uint64_t>(esp_timer_get_time() / 1000); }

void sendError(AsyncWebServerRequest* request, int code, const char* err) {
  char body[48];
  snprintf(body, sizeof(body), "{\"error\":\"%s\"}", err);
  request->send(code, FPSTR(CONTENT_TYPE_JSON), body);
}

void sendLimited(AsyncWebServerRequest* request, uint64_t retryAfterMs) {
  const uint32_t secs = static_cast<uint32_t>(retryAfterMs / 1000) + 1;
  char body[48];
  snprintf(body, sizeof(body), "{\"error\":\"RATE_LIMITED\",\"retry_after\":%u}", (unsigned)secs);
  AsyncWebServerResponse* response = request->beginResponse(429, FPSTR(CONTENT_TYPE_JSON), body);
  response->addHeader(F("Retry-After"), String(secs));
  request->send(response);
}

// PATH_AND_QUERY as sent. AsyncWebServer keeps the decoded path and the parsed query parameters,
// not the request line, so the query is rebuilt from them in order as name=value joined by '&'.
// Exact for the unreserved characters ePixC's clients use (e.g. /json/state?v=1).
String pathAndQuery(AsyncWebServerRequest* request) {
  String out = request->url();
  bool first = true;
  const size_t n = request->params();
  for (size_t i = 0; i < n; i++) {
    const AsyncWebParameter* p = request->getParam(i);
    if (p == nullptr || p->isPost() || p->isFile()) continue;
    out += first ? '?' : '&';
    first = false;
    out += p->name();
    out += '=';
    out += p->value();
  }
  return out;
}

bool onHotspotSubnet(uint32_t ip) {
  // 4.3.2.0/24 with lwIP's byte order (first octet lowest).
  return (ip & 0x00FFFFFFu) == (4u | (3u << 8) | (2u << 16));
}

bool validKey(const char* s, size_t n) { return pixc::lan::isLowerHex(s, n); }

// ---------------------------------------------------------------------------------------------
// /json/pixc/pair
// ---------------------------------------------------------------------------------------------

// The endpoint exists only on the hotspot, for a caller on the hotspot's own subnet.
bool pairReachable(AsyncWebServerRequest* request) {
  return apActive && onHotspotSubnet(pixcCallerIp(request));
}

void handlePairGet(AsyncWebServerRequest* request) {
  if (!pairReachable(request)) { request->send(404); return; }
  char body[160];
  snprintf(body, sizeof(body), "{\"mac\":\"%s\",\"fw\":\"%s\",\"leds\":%u,\"state\":\"%s\"}",
           escapedMac.c_str(), versionString, (unsigned)strip.getLengthTotal(),
           pixcIsKeyed() ? "keyed" : "new");
  request->send(200, FPSTR(CONTENT_TYPE_JSON), body);
}

void handlePairPost(AsyncWebServerRequest* request) {
  if (!pairReachable(request)) { request->send(404); return; }
  const size_t len = request->contentLength();
  if (request->_tempObject == nullptr || len == 0 || len > 1024) { sendError(request, 400, "BAD_REQUEST"); return; }
  StaticJsonDocument<768> doc;
  if (deserializeJson(doc, static_cast<const char*>(request->_tempObject), len)) { sendError(request, 400, "BAD_REQUEST"); return; }
  const char* ssid = doc["ssid"] | "";
  const char* psk = doc["psk"] | "";
  const char* kDev = doc["k_dev"] | "";
  const char* kLan = doc["k_lan"] | "";
  const size_t ssidLen = strlen(ssid), pskLen = strlen(psk);
  // Validate everything before storing anything: a malformed body stores nothing.
  if (ssidLen == 0 || ssidLen > 32 || (pskLen != 0 && (pskLen < 8 || pskLen > 63)) ||
      !validKey(kDev, 64) || !validKey(kLan, pixc::lan::kKeyHexLen)) {
    sendError(request, 400, "BAD_REQUEST");
    return;
  }
  // A keyed light takes a new Wi-Fi password only from the phone that holds its key (the
  // wrong-password retry). Anyone else must factory-reset it first.
  if (pixcIsKeyed() && !pixc::lan::equalConstTime(pixcLanKey, kLan, pixc::lan::kKeyHexLen)) {
    sendError(request, 409, "ALREADY_PAIRED");
    return;
  }

  // One network, the one the phone gave. Static addressing is not offered at pairing.
  multiWiFi.resize(1);
  memset(multiWiFi[0].clientSSID, 0, sizeof(multiWiFi[0].clientSSID));
  memset(multiWiFi[0].clientPass, 0, sizeof(multiWiFi[0].clientPass));
  strlcpy(multiWiFi[0].clientSSID, ssid, sizeof(multiWiFi[0].clientSSID));
  strlcpy(multiWiFi[0].clientPass, psk, sizeof(multiWiFi[0].clientPass));
  multiWiFi[0].staticIP = IPAddress(0, 0, 0, 0);
  memset(multiWiFi[0].bssid, 0, sizeof(multiWiFi[0].bssid));
  strlcpy(pixcDeviceKey, kDev, sizeof(pixcDeviceKey));
  if (strcmp(pixcLanKey, kLan) != 0) {
    strlcpy(pixcLanKey, kLan, sizeof(pixcLanKey));
    previousLanKey[0] = 0;
    replay.clear();
  }
  // A new pairing starts with no broker login: the light pulls its own once registered.
  mqttUser[0] = 0;
  mqttPass[0] = 0;
  mqttServer[0] = 0;
#ifdef EPIXC_ALLOW_PLAINTEXT_PROVISION
  // Bench only: the app may point the light at a local API ("host" or "host:port").
  const char* apiHost = doc["api_host"] | "";
  if (apiHost[0]) {
    StaticJsonDocument<192> um;
    char host[64];
    strlcpy(host, apiHost, sizeof(host));
    char* colon = strchr(host, ':');
    JsonObject top = um.createNestedObject("PixcConnect");
    if (colon) { *colon = 0; top["apiPort"] = atoi(colon + 1); }
    top["apiHost"] = host;
    JsonObject umRoot = um.as<JsonObject>();
    UsermodManager::readFromConfig(umRoot);
  }
#endif
  serializeConfigToFS();   // cfg.json (the SSID) and wsec.json (PSK, keys), one save
  char body[40];
  snprintf(body, sizeof(body), "{\"mac\":\"%s\"}", escapedMac.c_str());
  request->send(200, FPSTR(CONTENT_TYPE_JSON), body);
  pixcRebootAfter(1500);   // let the reply leave before the hotspot goes
}

}  // namespace

// ---------------------------------------------------------------------------------------------

uint32_t pixcCallerIp(AsyncWebServerRequest* request) {
  AsyncClient* c = request ? request->client() : nullptr;
  return c ? static_cast<uint32_t>(c->remoteIP()) : 0;
}

bool pixcIsKeyed() { return validKey(pixcLanKey, pixc::lan::kKeyHexLen); }

bool pixcSetLanKey(const char* keyHex) {
  if (!validKey(keyHex, pixc::lan::kKeyHexLen) || strcmp(keyHex, pixcLanKey) == 0) return false;
  strlcpy(previousLanKey, pixcLanKey, sizeof(previousLanKey));
  strlcpy(pixcLanKey, keyHex, sizeof(pixcLanKey));
  replay.clear();
  return true;
}

void pixcSerializeSecrets(JsonObject root) {
  JsonObject p = root.createNestedObject("pixc");
  p["lan"] = pixcLanKey;
  p["dev"] = pixcDeviceKey;
}

void pixcDeserializeSecrets(JsonObject root) {
  JsonObject p = root["pixc"];
  if (p.isNull()) return;
  const char* lan = p["lan"] | "";
  const char* dev = p["dev"] | "";
  strlcpy(pixcLanKey, validKey(lan, pixc::lan::kKeyHexLen) ? lan : "", sizeof(pixcLanKey));
  strlcpy(pixcDeviceKey, validKey(dev, 64) ? dev : "", sizeof(pixcDeviceKey));
}

bool pixcAuthorise(AsyncWebServerRequest* request, const uint8_t* body, size_t len, PixcReplySigner& out) {
  out.active = false;
  const uint32_t ip = pixcCallerIp(request);
  uint64_t retry = 0;
  if (!authGuard.mayTry(ip, nowMs64(), &retry)) { sendLimited(request, retry); return false; }
  const AsyncWebHeader* h = request->getHeader(F("X-PixC-Auth"));
  const String path = pathAndQuery(request);
  const String method(request->methodToString());   // "GET", "POST", ... upper case
  pixc::lan::ParsedAuth pa;
  const pixc::lan::Verdict v = pixc::lan::verify(h ? h->value().c_str() : nullptr, pixcLanKey, previousLanKey,
      pixcBootId(), method.c_str(), path.c_str(), body, len, replay, &pa);
  if (v == pixc::lan::Verdict::Ok) {
    authGuard.onRight(ip);
    out.active = true;
    strlcpy(out.clientId, pa.clientId, sizeof(out.clientId));
    out.ctr = pa.ctr;
    return true;
  }
  // A bad signature slows its sender down. A stale boot id or a replayed counter is what an honest
  // client sees after a reboot or a lost reply, and the stale key what it sends once after a
  // rotation: none of those is counted.
  if (v == pixc::lan::Verdict::Unauthorised) authGuard.onWrong(ip, nowMs64());
  sendError(request, 401, pixc::lan::verdictCode(v));
  return false;
}

void pixcSignResponse(AsyncWebServerResponse* response, const PixcReplySigner& signer, const char* bodyHashHex) {
  if (!signer.active || response == nullptr) return;
  char sig[pixc::lan::kMacB64Len + 1];
  if (!pixc::lan::replySig(pixcLanKey, pixcBootId(), signer.ctr, signer.clientId, bodyHashHex, sig)) return;
  String v = F("v2 ");
  v += sig;
  response->addHeader(F("X-PixC-Sig"), v);
}

void pixcSendSigned(AsyncWebServerRequest* request, const PixcReplySigner& signer, int code,
                    const char* contentType, const char* body) {
  char bh[65];
  pixc::lan::bodyHashHex(reinterpret_cast<const uint8_t*>(body), strlen(body), bh);
  AsyncWebServerResponse* response = request->beginResponse(code, contentType, body);
  pixcSignResponse(response, signer, bh);
  request->send(response);
}

void pixcRegisterRoutes(AsyncWebServer& srv) {
  // Who am I, unauthenticated: the MAC (which anyone on the LAN sees in ARP anyway) and this boot's
  // id, which every signed request must carry. A client reads it before its first request and after
  // any 401 STALE_BOOT. Registered before /json, whose handlers match every /json/... prefix.
  srv.on(F("/json/id"), HTTP_GET, [](AsyncWebServerRequest* request) {
    char body[80];
    snprintf(body, sizeof(body), "{\"mac\":\"%s\",\"boot_id\":\"%s\",\"v\":2}", escapedMac.c_str(), pixcBootId());
    request->send(200, FPSTR(CONTENT_TYPE_JSON), body);
  });
  srv.on(F("/json/pixc/pair"), HTTP_GET, handlePairGet);
  AsyncCallbackJsonWebHandler* pair = new AsyncCallbackJsonWebHandler(F("/json/pixc/pair"), handlePairPost);
  pair->setMaxContentLength(1024);
  srv.addHandler(pair);
}

bool pixcHandleAuthedPost(AsyncWebServerRequest* request, JsonObject root, const PixcReplySigner& signer) {
  if (request->url() == F("/json/pixc/reset")) {
    JsonVariant r = root["reset"];
    if (!r.is<bool>() || !r.as<bool>()) { pixcSendSigned(request, signer, 400, CONTENT_TYPE_JSON, "{\"error\":\"BAD_REQUEST\"}"); return true; }
    pixcSendSigned(request, signer, 200, CONTENT_TYPE_JSON, "{\"success\":true}");
    pixcRequestFactoryReset("lan");
    return true;
  }
  if (request->url().startsWith(F("/json/pixc"))) {
    pixcSendSigned(request, signer, 404, CONTENT_TYPE_JSON, "{\"error\":\"NOT_FOUND\"}");
    return true;
  }
  JsonVariant lease = root["pixc"]["rt_lease"];
  if (!lease.isNull()) {
    const int want = lease.as<int>();
    const uint32_t ip = pixcCallerIp(request);
    const uint16_t secs = want <= 0 ? 0 : (want > kLeaseMaxS ? kLeaseMaxS : static_cast<uint16_t>(want));
    // Its own slot, else a free or expired one, else the one ending soonest.
    uint8_t slot = 0;
    for (uint8_t i = 0; i < kLeases; i++) {
      if (leases[i].ip == ip) { slot = i; break; }
      if (leases[i].ip == 0 || (long)(millis() - leases[i].until) >= 0) slot = i;
      else if (leases[slot].ip != 0 && (long)(leases[i].until - leases[slot].until) < 0) slot = i;
    }
    if (secs == 0) { if (leases[slot].ip == ip) leases[slot].ip = 0; }
    else { leases[slot].ip = ip; leases[slot].until = millis() + secs * 1000UL; }
  }
  root.remove("pixc");
  if (!lease.isNull() && root.size() == 0) {
    pixcSendSigned(request, signer, 200, CONTENT_TYPE_JSON, "{\"success\":true}");
    return true;
  }
  return false;
}

bool pixcRealtimeAllowed(uint32_t ip) {
  if (ip == 0) return false;
  for (uint8_t i = 0; i < kLeases; i++)
    if (leases[i].ip == ip && (long)(millis() - leases[i].until) < 0) return true;
  return false;
}

void pixcSanitizeLanCfg(JsonObject root) {
  JsonObject ifs = root["if"];
  if (!ifs.isNull()) ifs.remove("mqtt");
  root.remove("ap");
  root.remove("ota");
  root.remove("pin");
  root.remove("pixc");
  JsonObject um = root["um"];
  if (!um.isNull()) um.remove("PixcConnect");
}
// AI: end

#endif  // PIXC_LAN_AUTH
