#include "wled.h"

#ifdef PIXC_MQTT_ESP_IDF

#include "pixc_mqtt_client.h"
#include "../usermods/pixc_connect_blink/pixc_roots.h"
#include "../usermods/pixc_connect_blink/pixc_logic.h"   // backoffWithJitter()
#include <esp_random.h>

// TLS ONLY (audit S10). This used to choose TLS by port - 8883 TLS, anything else plaintext - and
// the port comes from the provisioning reply, from the PIN-gated /json/cfg and (then) from any
// cloud /cfg push. So one config value turned the per-device MQTT credential into plaintext on the
// wire, the same "a config value revokes the guarantee" defect ticket 33 closed for provisioning.
//
// A release image now has no plaintext MQTT path compiled in: it speaks TLS, and only to 8883, the
// registered MQTTS port and the only one ePixC publishes. Any other port is refused. The bench
// broker in epixc-backend's compose.local.yaml is plaintext on 1883, so PixC_V1_dev - and only it -
// defines EPIXC_ALLOW_PLAINTEXT_MQTT, the same one-way pattern as EPIXC_ALLOW_PLAINTEXT_PROVISION.
static constexpr uint16_t kMqttsPort = 8883;

PixcMqttClient& PixcMqttClient::setServer(const char* host, uint16_t port) {
  if (_host != host || _port != port) {
    _host = host;
    _port = port;
    _dirty = true;
  }
  return *this;
}

PixcMqttClient& PixcMqttClient::setServer(IPAddress ip, uint16_t port) {
  return setServer(ip.toString().c_str(), port);
}

PixcMqttClient& PixcMqttClient::setClientId(const char* clientId) {
  if (_clientId != clientId) { _clientId = clientId; _dirty = true; }
  return *this;
}

PixcMqttClient& PixcMqttClient::setCredentials(const char* username, const char* password) {
  const char* u = username ? username : "";
  const char* p = password ? password : "";
  if (_user != u || _pass != p) { _user = u; _pass = p; _dirty = true; }
  return *this;
}

PixcMqttClient& PixcMqttClient::setKeepAlive(uint16_t seconds) {
  if (_keepAlive != seconds) { _keepAlive = seconds; _dirty = true; }
  return *this;
}

// Compares before dirtying, like every other setter, and that matters more here than it looks:
// WLED re-runs `initMqtt()` every 30 seconds while disconnected, calling all of these each time.
// A setter that dirtied unconditionally would tear the client down and rebuild it on every one of
// those passes — aborting an in-flight TLS handshake and restarting esp-mqtt's reconnect backoff
// from zero, so a device on a slow link could never finish connecting.
PixcMqttClient& PixcMqttClient::setWill(const char* topic, uint8_t qos, bool retain,
                                        const char* payload) {
  const char* t = topic ? topic : "";
  const char* p = payload ? payload : "";
  if (_willTopic != t || _willPayload != p || _willQos != qos || _willRetain != retain) {
    _willTopic = t;
    _willPayload = p;
    _willQos = qos;
    _willRetain = retain;
    _dirty = true;
  }
  return *this;
}

// AI: below section was generated by an AI

namespace {
// One queued esp-mqtt event, copied out of esp-mqtt's buffers. `buf` holds the NUL-terminated topic
// followed by the NUL-terminated payload chunk.
struct QueuedEvent {
  uint8_t kind;             // kEvConnected / kEvDisconnected / kEvData
  uint8_t qos;
  bool retain;
  bool dup;
  bool sessionPresent;
  uint16_t topicLen;
  uint32_t len, index, total;
  char buf[1];
};
constexpr uint8_t kEvConnected = 1, kEvDisconnected = 2, kEvData = 3;
constexpr UBaseType_t kQueueDepth = 24;
// The largest inbound message worth reassembling. A /cfg or /api payload is a few hundred bytes; a
// preset list can reach a few KB. Anything past this is dropped rather than allocated.
constexpr uint32_t kMaxMessage = 16384;
// At most this many events per loop() call, so a burst of messages cannot stall the LED loop.
constexpr uint8_t kDrainPerLoop = 8;
constexpr uint32_t kBackoffBaseMs = 2000, kBackoffMaxMs = 300000;   // 2 s doubling to 5 min
}  // namespace

esp_err_t PixcMqttClient::eventHandler(esp_mqtt_event_handle_t event) {
  auto* self = static_cast<PixcMqttClient*>(event->user_context);
  if (self != nullptr) self->handle(event);
  return ESP_OK;
}

// Runs on the esp-mqtt task. Copies and queues; never calls into WLED.
void PixcMqttClient::handle(esp_mqtt_event_handle_t event) {
  switch (event->event_id) {
    case MQTT_EVENT_CONNECTED:    enqueue(kEvConnected, event); break;
    case MQTT_EVENT_DISCONNECTED: enqueue(kEvDisconnected, event); break;
    case MQTT_EVENT_DATA: {
      // A continuation chunk carries no topic (topic_len == 0); the topic arrives only with the
      // first. Remembering it is what lets a payload larger than the receive buffer survive.
      if (event->topic_len > 0) {
        _lastTopic = String();
        _lastTopic.concat(event->topic, event->topic_len);
      }
      if (_lastTopic.length() == 0) break;
      if ((uint32_t)event->total_data_len > kMaxMessage) break;
      enqueue(kEvData, event);
      break;
    }
    case MQTT_EVENT_ERROR:
      // Worth a line: a TLS failure here is otherwise a silent reconnect loop, and the two causes
      // that matter - a certificate the pinned roots do not cover, and credentials the broker
      // rejects - look identical from the outside without it.
      if (event->error_handle != nullptr) {
        DEBUG_PRINTF("[ePixC] MQTT error type=%d tls=%d sock_errno=%d\n",
                     (int)event->error_handle->error_type,
                     (int)event->error_handle->esp_tls_last_esp_err,
                     (int)event->error_handle->esp_transport_sock_errno);
      }
      break;
    default:
      break;
  }
}

bool PixcMqttClient::enqueue(uint8_t kind, esp_mqtt_event_handle_t event) {
  if (_events == nullptr) return false;
  const size_t topicLen = kind == kEvData ? _lastTopic.length() : 0;
  const size_t dataLen = kind == kEvData ? (size_t)event->data_len : 0;
  auto* ev = static_cast<QueuedEvent*>(malloc(sizeof(QueuedEvent) + topicLen + 1 + dataLen + 1));
  if (ev == nullptr) { _dropped++; return false; }
  ev->kind = kind;
  ev->qos = (uint8_t)event->qos;
  ev->retain = event->retain;
  ev->dup = event->dup;
  ev->sessionPresent = event->session_present != 0;
  ev->topicLen = (uint16_t)topicLen;
  ev->len = (uint32_t)dataLen;
  ev->index = kind == kEvData ? (uint32_t)event->current_data_offset : 0;
  ev->total = kind == kEvData ? (uint32_t)event->total_data_len : 0;
  if (topicLen) memcpy(ev->buf, _lastTopic.c_str(), topicLen);
  ev->buf[topicLen] = 0;
  if (dataLen) memcpy(ev->buf + topicLen + 1, event->data, dataLen);
  ev->buf[topicLen + 1 + dataLen] = 0;
  // Connection state changes wait briefly for room; a data chunk that finds the queue full is
  // dropped (WLED's reassembly discards a message whose first chunk never arrived).
  const TickType_t wait = kind == kEvData ? 0 : pdMS_TO_TICKS(50);
  if (xQueueSend(_events, &ev, wait) != pdTRUE) { free(ev); _dropped++; return false; }
  return true;
}

void PixcMqttClient::scheduleReconnect() {
  const uint32_t delayMs = pixc::backoffWithJitter(_attempt, kBackoffBaseMs, kBackoffMaxMs, esp_random());
  if (_attempt < 16) _attempt++;
  _reconnectDue = true;
  _nextAttemptAt = millis() + delayMs;
  DEBUG_PRINTF("[ePixC] MQTT reconnect in %u ms (attempt %u)\n", (unsigned)delayMs, (unsigned)_attempt);
}

void PixcMqttClient::loop() {
  if (_events != nullptr) {
    for (uint8_t n = 0; n < kDrainPerLoop; n++) {
      QueuedEvent* ev = nullptr;
      if (xQueueReceive(_events, &ev, 0) != pdTRUE || ev == nullptr) break;
      switch (ev->kind) {
        case kEvConnected:
          _connected = true;
          _attempt = 0;
          _reconnectDue = false;
          if (_onConnect) _onConnect(ev->sessionPresent);
          break;
        case kEvDisconnected:
          // Also what esp-mqtt reports after a failed connection attempt, so this is the one place
          // the next attempt is scheduled.
          _connected = false;
          if (_started) scheduleReconnect();
          break;
        case kEvData:
          if (_onMessage) {
            AsyncMqttClientMessageProperties props;
            props.qos = ev->qos;
            props.retain = ev->retain;
            props.dup = ev->dup;
            _onMessage(ev->buf, ev->buf + ev->topicLen + 1, props, ev->len, ev->index, ev->total);
          }
          break;
      }
      free(ev);
    }
  }
  if (_started && !_connected && _reconnectDue && (int32_t)(millis() - _nextAttemptAt) >= 0) {
    // Valid only while esp-mqtt waits in its reconnect state; otherwise it is still connecting and
    // will report the outcome as an event, so just look again shortly.
    if (esp_mqtt_client_reconnect(_client) == ESP_OK) _reconnectDue = false;
    else _nextAttemptAt = millis() + 1000;
  }
}
// AI: end

bool PixcMqttClient::start() {
  if (_host.length() == 0) return false;
  if (_events == nullptr) {
    _events = xQueueCreate(kQueueDepth, sizeof(QueuedEvent*));
    if (_events == nullptr) return false;
  }

  esp_mqtt_client_config_t cfg = {};
  cfg.event_handle = &PixcMqttClient::eventHandler;
  cfg.user_context = this;
  cfg.host = _host.c_str();
  cfg.port = _port;
  cfg.keepalive = _keepAlive;
  // esp-mqtt defaults to a 1 KB buffer for both directions. AsyncMqttClient had no such limit, so
  // the default would silently shrink two things WLED already does: a full state publish with
  // several segments, and an inbound preset or config push. Inbound over the limit is chunked and
  // reassembled; **outbound over the limit simply fails**, which is the one that would have been
  // hard to see. 2 KB in, 4 KB out, at a one-off cost of about 6 KB of RAM.
  cfg.buffer_size = 2048;
  cfg.out_buffer_size = 4096;
  // WLED's handlers no longer run here (see loop()); what is left is the TLS handshake - an
  // RSA-4096 chain verify for ISRG Root X1 - and socket I/O. 7 KB over esp-mqtt's 6 KB default
  // for the pinned-root verify callback. Check uxTaskGetStackHighWaterMark on the bench.
  cfg.task_stack = 7168;
  // Our own reconnect schedule (loop()). With auto reconnect off, esp-mqtt waits for
  // esp_mqtt_client_reconnect(), waking every reconnect_timeout_ms/2 only to notice a stop - so a
  // short value keeps esp_mqtt_client_stop() from blocking the caller for long.
  cfg.disable_auto_reconnect = true;
  cfg.reconnect_timeout_ms = 1000;
  if (_clientId.length() > 0) cfg.client_id = _clientId.c_str();
  if (_user.length() > 0) cfg.username = _user.c_str();
  if (_pass.length() > 0) cfg.password = _pass.c_str();
  if (_willTopic.length() > 0) {
    cfg.lwt_topic = _willTopic.c_str();
    cfg.lwt_msg = _willPayload.c_str();
    cfg.lwt_qos = _willQos;
    cfg.lwt_retain = _willRetain ? 1 : 0;
  }
  if (_port == kMqttsPort) {
    cfg.transport = MQTT_TRANSPORT_OVER_SSL;
    // The same pinned roots the provisioning fetch uses. Not the certificate bundle: a bundle
    // trusts every public CA, which means any of them can mint a certificate for our broker.
    cfg.cert_pem = PIXC_TRUSTED_ROOTS;
  } else {
#ifdef EPIXC_ALLOW_PLAINTEXT_MQTT
    cfg.transport = MQTT_TRANSPORT_OVER_TCP;   // PixC_V1_dev bench broker only
#else
    DEBUG_PRINTF("[ePixC] MQTT refused: port %u is not TLS (8883)\n", (unsigned)_port);
    return false;
#endif
  }

  _client = esp_mqtt_client_init(&cfg);
  if (_client == nullptr) return false;
  if (esp_mqtt_client_start(_client) != ESP_OK) {
    esp_mqtt_client_destroy(_client);
    _client = nullptr;
    return false;
  }
  _dirty = false;
  _started = true;
  _reconnectDue = false;
  return true;
}

void PixcMqttClient::connect() {
  // esp-mqtt reads host, credentials and TLS settings once, at start. A changed broker — which is
  // what re-provisioning does — therefore needs a restart, not a reconnect.
  if (_client != nullptr && _dirty) {
    esp_mqtt_client_stop(_client);
    esp_mqtt_client_destroy(_client);
    _client = nullptr;
    _connected = false;
    _started = false;
    flushEvents();
  }
  // A pending backoff applies to a (re)start as well, so WLED's 30-second initMqtt() calls cannot
  // bypass it.
  if (_reconnectDue && (int32_t)(millis() - _nextAttemptAt) < 0) return;
  if (_client == nullptr) {
    // The very first connection after boot waits a random 0-3 s: when power returns to a street,
    // every unit on it boots in the same second, and this spreads the first TLS handshakes out.
    if (!_bootJitterDone) {
      _bootJitterDone = true;
      _reconnectDue = true;
      _nextAttemptAt = millis() + esp_random() % 3000;
      return;
    }
    if (!start()) scheduleReconnect();
    return;
  }
  // Allocated but stopped. This is the path re-provisioning takes: the usermod calls
  // `disconnect()` and then `initMqtt()`, and when the broker has not actually changed there is
  // nothing dirty to trigger a rebuild — so without this the client would sit stopped forever and
  // the device would never come back to the broker it was already using.
  if (!_started) {
    _started = esp_mqtt_client_start(_client) == ESP_OK;
    return;
  }
  // Already running: loop() drives reconnects on the backoff schedule, so there is nothing to do.
}

void PixcMqttClient::disconnect(bool) {
  if (_client == nullptr || !_started) return;
  esp_mqtt_client_stop(_client);
  _connected = false;
  _started = false;
  _reconnectDue = false;
  flushEvents();
}

// Discard events queued by a client that has just been stopped: its CONNECTED or DISCONNECTED
// arriving after a restart would describe a connection that no longer exists.
void PixcMqttClient::flushEvents() {
  if (_events == nullptr) return;
  void* ev = nullptr;
  while (xQueueReceive(_events, &ev, 0) == pdTRUE) free(ev);
}

uint16_t PixcMqttClient::publish(const char* topic, uint8_t qos, bool retain, const char* payload) {
  return publish(topic, qos, retain, payload, payload ? strlen(payload) : 0);
}

uint16_t PixcMqttClient::publish(const char* topic, uint8_t qos, bool retain, const char* payload,
                                 size_t length) {
  if (_client == nullptr || !_connected) return 0;
  int id = esp_mqtt_client_publish(_client, topic, payload, (int)length, qos, retain ? 1 : 0);
  // QoS 0 returns 0 on success, which is also the failure value. Only -1 is a failure, so it is
  // mapped to 0 and everything else to something non-zero, matching what callers expect.
  return id < 0 ? 0 : (uint16_t)(id == 0 ? 1 : id);
}

uint16_t PixcMqttClient::subscribe(const char* topic, uint8_t qos) {
  if (_client == nullptr) return 0;
  int id = esp_mqtt_client_subscribe(_client, topic, qos);
  return id < 0 ? 0 : (uint16_t)(id == 0 ? 1 : id);
}

#endif  // PIXC_MQTT_ESP_IDF
