#pragma once

// AI: below section was generated by an AI
//
// Pairing and LAN security v2: request authentication and reply signing for the LAN JSON API.
// Vault: 05-Firmware/Pairing and LAN security v2, "LAN requests". Byte-for-byte contract:
// epixc-backend shared/lan-auth/vectors.json, copied to test/pixc/vectors/ and checked by
// test/pixc/test_pixc.cpp against THIS code - the same code the device runs.
//
//   X-PixC-Auth: v2 <client_id>:<boot_id>:<ctr>:<mac_b64>
//   mac = HMAC-SHA256(K_lan, "req\n" METHOD "\n" PATH_AND_QUERY "\n" boot_id "\n" ctr "\n"
//                            client_id "\n" hex(sha256(body)))
//   X-PixC-Sig:  v2 <b64(HMAC(K_lan, "resp\n" boot_id "\n" ctr "\n" client_id "\n"
//                                   hex(sha256(reply_body))))>
//
// K_lan is the 16 BYTES its 32 hex characters encode. client_id is 16 lowercase hex, boot_id 8,
// ctr decimal without leading zeros from 1, mac_b64 standard base64 with padding.
//
// Pure C++, no Arduino or ESP-IDF: SHA-256 and HMAC are implemented here (FIPS 180-4, RFC 2104)
// rather than taken from mbedTLS, so the host test exercises the exact code that ships. The cost on
// the device is microseconds for a JSON body.

#include <stddef.h>
#include <stdint.h>
#include <string.h>

namespace pixc {
namespace lan {

// ---------------------------------------------------------------------------------------------
// SHA-256 (FIPS 180-4)
// ---------------------------------------------------------------------------------------------
class Sha256 {
 public:
  Sha256() { reset(); }
  void reset() {
    static const uint32_t h0[8] = {0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a,
                                   0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19};
    memcpy(_h, h0, sizeof(_h));
    _len = 0;
    _fill = 0;
  }
  void update(const void* data, size_t n) {
    const uint8_t* p = static_cast<const uint8_t*>(data);
    _len += n;
    while (n > 0) {
      const size_t take = (64 - _fill) < n ? (64 - _fill) : n;
      memcpy(_buf + _fill, p, take);
      _fill += take; p += take; n -= take;
      if (_fill == 64) { block(_buf); _fill = 0; }
    }
  }
  void finish(uint8_t out[32]) {
    const uint64_t bits = _len * 8;
    const uint8_t one = 0x80, zero = 0;
    update(&one, 1);
    while (_fill != 56) update(&zero, 1);
    uint8_t lenBytes[8];
    for (int i = 0; i < 8; i++) lenBytes[i] = static_cast<uint8_t>(bits >> (56 - 8 * i));
    update(lenBytes, 8);
    for (int i = 0; i < 8; i++) {
      out[4 * i] = static_cast<uint8_t>(_h[i] >> 24);
      out[4 * i + 1] = static_cast<uint8_t>(_h[i] >> 16);
      out[4 * i + 2] = static_cast<uint8_t>(_h[i] >> 8);
      out[4 * i + 3] = static_cast<uint8_t>(_h[i]);
    }
  }

 private:
  static uint32_t rotr(uint32_t x, int n) { return (x >> n) | (x << (32 - n)); }
  void block(const uint8_t* b) {
    static const uint32_t k[64] = {
      0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
      0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
      0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
      0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
      0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
      0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
      0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
      0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2};
    uint32_t w[64];
    for (int i = 0; i < 16; i++)
      w[i] = (uint32_t(b[4 * i]) << 24) | (uint32_t(b[4 * i + 1]) << 16) | (uint32_t(b[4 * i + 2]) << 8) | b[4 * i + 3];
    for (int i = 16; i < 64; i++) {
      const uint32_t s0 = rotr(w[i - 15], 7) ^ rotr(w[i - 15], 18) ^ (w[i - 15] >> 3);
      const uint32_t s1 = rotr(w[i - 2], 17) ^ rotr(w[i - 2], 19) ^ (w[i - 2] >> 10);
      w[i] = w[i - 16] + s0 + w[i - 7] + s1;
    }
    uint32_t a = _h[0], bb = _h[1], c = _h[2], d = _h[3], e = _h[4], f = _h[5], g = _h[6], h = _h[7];
    for (int i = 0; i < 64; i++) {
      const uint32_t S1 = rotr(e, 6) ^ rotr(e, 11) ^ rotr(e, 25);
      const uint32_t ch = (e & f) ^ (~e & g);
      const uint32_t t1 = h + S1 + ch + k[i] + w[i];
      const uint32_t S0 = rotr(a, 2) ^ rotr(a, 13) ^ rotr(a, 22);
      const uint32_t mj = (a & bb) ^ (a & c) ^ (bb & c);
      const uint32_t t2 = S0 + mj;
      h = g; g = f; f = e; e = d + t1; d = c; c = bb; bb = a; a = t1 + t2;
    }
    _h[0] += a; _h[1] += bb; _h[2] += c; _h[3] += d; _h[4] += e; _h[5] += f; _h[6] += g; _h[7] += h;
  }
  uint32_t _h[8];
  uint64_t _len;
  uint8_t _buf[64];
  size_t _fill;
};

// ---------------------------------------------------------------------------------------------
// HMAC-SHA256 (RFC 2104), streaming
// ---------------------------------------------------------------------------------------------
class HmacSha256 {
 public:
  HmacSha256(const uint8_t* key, size_t keyLen) {
    uint8_t k[64] = {0};
    if (keyLen > 64) { Sha256 s; s.update(key, keyLen); s.finish(k); }
    else if (keyLen) memcpy(k, key, keyLen);
    for (int i = 0; i < 64; i++) { _ipad[i] = k[i] ^ 0x36; _opad[i] = k[i] ^ 0x5c; }
    _inner.update(_ipad, 64);
  }
  void update(const void* d, size_t n) { _inner.update(d, n); }
  void update(const char* s) { _inner.update(s, strlen(s)); }
  void finish(uint8_t out[32]) {
    uint8_t ih[32];
    _inner.finish(ih);
    Sha256 o;
    o.update(_opad, 64);
    o.update(ih, 32);
    o.finish(out);
  }

 private:
  Sha256 _inner;
  uint8_t _ipad[64], _opad[64];
};

// ---------------------------------------------------------------------------------------------
// Encodings
// ---------------------------------------------------------------------------------------------
inline void toHex(const uint8_t* in, size_t n, char* out /* 2n+1 */) {
  static const char* H = "0123456789abcdef";
  for (size_t i = 0; i < n; i++) { out[2 * i] = H[in[i] >> 4]; out[2 * i + 1] = H[in[i] & 15]; }
  out[2 * n] = 0;
}

inline int hexNibble(char c) {
  if (c >= '0' && c <= '9') return c - '0';
  if (c >= 'a' && c <= 'f') return c - 'a' + 10;
  return -1;                                             // lowercase only, by contract
}

// Decode exactly `n` bytes from 2n lowercase hex characters (and nothing after them).
inline bool fromHex(const char* in, uint8_t* out, size_t n) {
  if (in == nullptr || strlen(in) != 2 * n) return false;
  for (size_t i = 0; i < n; i++) {
    const int hi = hexNibble(in[2 * i]), lo = hexNibble(in[2 * i + 1]);
    if (hi < 0 || lo < 0) return false;
    out[i] = static_cast<uint8_t>((hi << 4) | lo);
  }
  return true;
}

inline bool isLowerHex(const char* s, size_t n) {
  if (s == nullptr || strlen(s) != n) return false;
  for (size_t i = 0; i < n; i++) if (hexNibble(s[i]) < 0) return false;
  return true;
}

// Standard base64 with padding. 32 bytes -> 44 characters.
inline void base64(const uint8_t* in, size_t n, char* out /* 4*ceil(n/3)+1 */) {
  static const char* T = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  size_t o = 0;
  for (size_t i = 0; i < n; i += 3) {
    const uint32_t v = (uint32_t(in[i]) << 16) | (i + 1 < n ? uint32_t(in[i + 1]) << 8 : 0) | (i + 2 < n ? in[i + 2] : 0);
    out[o++] = T[(v >> 18) & 63];
    out[o++] = T[(v >> 12) & 63];
    out[o++] = i + 1 < n ? T[(v >> 6) & 63] : '=';
    out[o++] = i + 2 < n ? T[v & 63] : '=';
  }
  out[o] = 0;
}

inline bool equalConstTime(const char* a, const char* b, size_t n) {
  uint8_t d = 0;
  for (size_t i = 0; i < n; i++) d |= static_cast<uint8_t>(a[i] ^ b[i]);
  return d == 0;
}

// ---------------------------------------------------------------------------------------------
// The scheme
// ---------------------------------------------------------------------------------------------
constexpr size_t kKeyHexLen = 32, kKeyLen = 16;
constexpr size_t kClientIdLen = 16, kBootIdLen = 8, kMacB64Len = 44;

struct ParsedAuth {
  char clientId[kClientIdLen + 1];
  char bootId[kBootIdLen + 1];
  uint32_t ctr;
  char mac[kMacB64Len + 1];
};

// Parse "v2 <client_id>:<boot_id>:<ctr>:<mac_b64>". Strict: any deviation is a failure.
inline bool parseAuthHeader(const char* h, ParsedAuth& out) {
  if (h == nullptr || strncmp(h, "v2 ", 3) != 0) return false;
  const char* p = h + 3;
  const char* c1 = strchr(p, ':');
  if (c1 == nullptr || static_cast<size_t>(c1 - p) != kClientIdLen) return false;
  memcpy(out.clientId, p, kClientIdLen); out.clientId[kClientIdLen] = 0;
  const char* q = c1 + 1;
  const char* c2 = strchr(q, ':');
  if (c2 == nullptr || static_cast<size_t>(c2 - q) != kBootIdLen) return false;
  memcpy(out.bootId, q, kBootIdLen); out.bootId[kBootIdLen] = 0;
  const char* r = c2 + 1;
  const char* c3 = strchr(r, ':');
  if (c3 == nullptr || c3 == r || c3 - r > 10 || *r == '0') return false;   // 1..4294967295
  uint64_t ctr = 0;
  for (const char* x = r; x < c3; x++) {
    if (*x < '0' || *x > '9') return false;
    ctr = ctr * 10 + static_cast<uint64_t>(*x - '0');
  }
  if (ctr == 0 || ctr > 0xFFFFFFFFULL) return false;
  out.ctr = static_cast<uint32_t>(ctr);
  const char* m = c3 + 1;
  if (strlen(m) != kMacB64Len) return false;
  memcpy(out.mac, m, kMacB64Len + 1);
  if (!isLowerHex(out.clientId, kClientIdLen) || !isLowerHex(out.bootId, kBootIdLen)) return false;
  return true;
}

inline void bodyHashHex(const uint8_t* body, size_t len, char out[65]) {
  Sha256 s;
  if (len) s.update(body, len);
  uint8_t d[32];
  s.finish(d);
  toHex(d, 32, out);
}

// The request MAC, base64. `bodyHash` is hex(sha256(body)).
inline bool requestMac(const char* keyHex, const char* method, const char* pathAndQuery,
                       const char* bootId, uint32_t ctr, const char* clientId,
                       const char* bodyHash, char out[kMacB64Len + 1]) {
  uint8_t key[kKeyLen];
  if (!fromHex(keyHex, key, kKeyLen)) return false;
  char ctrText[11];
  {
    char tmp[11]; int n = 0; uint32_t v = ctr;
    do { tmp[n++] = static_cast<char>('0' + v % 10); v /= 10; } while (v);
    for (int i = 0; i < n; i++) ctrText[i] = tmp[n - 1 - i];
    ctrText[n] = 0;
  }
  HmacSha256 h(key, kKeyLen);
  h.update("req\n"); h.update(method); h.update("\n"); h.update(pathAndQuery); h.update("\n");
  h.update(bootId); h.update("\n"); h.update(ctrText); h.update("\n"); h.update(clientId);
  h.update("\n"); h.update(bodyHash);
  uint8_t mac[32];
  h.finish(mac);
  base64(mac, 32, out);
  memset(key, 0, sizeof(key));
  return true;
}

// The reply signature, base64 (without the "v2 " prefix).
inline bool replySig(const char* keyHex, const char* bootId, uint32_t ctr, const char* clientId,
                     const char* bodyHash, char out[kMacB64Len + 1]) {
  uint8_t key[kKeyLen];
  if (!fromHex(keyHex, key, kKeyLen)) return false;
  char ctrText[11];
  {
    char tmp[11]; int n = 0; uint32_t v = ctr;
    do { tmp[n++] = static_cast<char>('0' + v % 10); v /= 10; } while (v);
    for (int i = 0; i < n; i++) ctrText[i] = tmp[n - 1 - i];
    ctrText[n] = 0;
  }
  HmacSha256 h(key, kKeyLen);
  h.update("resp\n"); h.update(bootId); h.update("\n"); h.update(ctrText); h.update("\n");
  h.update(clientId); h.update("\n"); h.update(bodyHash);
  uint8_t mac[32];
  h.finish(mac);
  base64(mac, 32, out);
  memset(key, 0, sizeof(key));
  return true;
}

// ---------------------------------------------------------------------------------------------
// Replay protection: the highest counter seen per client id, 16 most recent clients, LRU out.
// ---------------------------------------------------------------------------------------------
class ReplayTable {
 public:
  static constexpr uint8_t kSlots = 16;
  // True if `ctr` is above the one remembered for `clientId` (or the client is new). Does NOT
  // record it: call accept() once the request's MAC has verified, so a forged request cannot
  // advance a real client's counter.
  bool fresh(const char* clientId, uint32_t ctr) const {
    const int8_t i = find(clientId);
    return i < 0 || ctr > _s[i].ctr;
  }
  void accept(const char* clientId, uint32_t ctr) {
    int8_t i = find(clientId);
    if (i < 0) {
      i = 0;
      for (uint8_t k = 0; k < kSlots; k++) {
        if (!_s[k].used) { i = static_cast<int8_t>(k); break; }
        if (_s[k].tick < _s[i].tick) i = static_cast<int8_t>(k);
      }
      memcpy(_s[i].id, clientId, kClientIdLen);
      _s[i].used = true;
    }
    _s[i].ctr = ctr;
    _s[i].tick = ++_tick;
  }
  void clear() { for (uint8_t k = 0; k < kSlots; k++) _s[k].used = false; }

 private:
  struct Slot { char id[kClientIdLen]; uint32_t ctr; uint32_t tick; bool used; };
  int8_t find(const char* id) const {
    for (uint8_t k = 0; k < kSlots; k++)
      if (_s[k].used && memcmp(_s[k].id, id, kClientIdLen) == 0) return static_cast<int8_t>(k);
    return -1;
  }
  Slot _s[kSlots] = {};
  uint32_t _tick = 0;
};

// ---------------------------------------------------------------------------------------------
// Routing of the ePixC namespace on the signed API
// ---------------------------------------------------------------------------------------------
// /json/pixc/pair is registered as its own (unsigned, hotspot-only) handler. Every OTHER path under
// /json/pixc reaching the signed /json handlers is not served: the same signed 404 for all of them.
// There is deliberately no LAN factory reset (founder, 2026-09-25): anyone holding the LAN key -
// every member, a guest until rotation, the Sync host - could have wiped the light. Reset is the
// cloud's {"reset":true} (admin, checked by the server) and five power-ons in a row.
constexpr const char* kNotFoundBody = "{\"error\":\"NOT_FOUND\"}";
inline bool isPixcNamespace(const char* url) {
  return url != nullptr && strncmp(url, "/json/pixc", 10) == 0;
}

enum class Verdict : uint8_t { Ok, NoKey, Unauthorised, StaleBoot, Replay, PreviousKey };

inline const char* verdictCode(Verdict v) {
  switch (v) {
    case Verdict::StaleBoot: return "STALE_BOOT";
    case Verdict::Replay:    return "REPLAY";
    default:                 return "UNAUTHORISED";
  }
}

// Verify one request. `keyHex` is the light's K_lan (32 hex) or empty; `previousKeyHex` the key
// before the last rotation or empty - a request signed with it is refused as Unauthorised but
// reported as PreviousKey, so the caller does not count it against the sender (clients try the old
// key once after every rotation, by design). On Ok the counter is recorded in `replay`.
inline Verdict verify(const char* authHeader, const char* keyHex, const char* previousKeyHex,
                      const char* myBootId, const char* method, const char* pathAndQuery,
                      const uint8_t* body, size_t bodyLen, ReplayTable& replay, ParsedAuth* outParsed) {
  if (keyHex == nullptr || strlen(keyHex) != kKeyHexLen) return Verdict::NoKey;
  ParsedAuth a;
  if (!parseAuthHeader(authHeader, a)) return Verdict::Unauthorised;
  if (strcmp(a.bootId, myBootId) != 0) return Verdict::StaleBoot;
  char bh[65];
  bodyHashHex(body, bodyLen, bh);
  char want[kMacB64Len + 1];
  if (!requestMac(keyHex, method, pathAndQuery, a.bootId, a.ctr, a.clientId, bh, want)) return Verdict::NoKey;
  if (!equalConstTime(want, a.mac, kMacB64Len)) {
    if (previousKeyHex != nullptr && strlen(previousKeyHex) == kKeyHexLen &&
        requestMac(previousKeyHex, method, pathAndQuery, a.bootId, a.ctr, a.clientId, bh, want) &&
        equalConstTime(want, a.mac, kMacB64Len)) return Verdict::PreviousKey;
    return Verdict::Unauthorised;
  }
  if (!replay.fresh(a.clientId, a.ctr)) return Verdict::Replay;
  replay.accept(a.clientId, a.ctr);
  if (outParsed != nullptr) *outParsed = a;
  return Verdict::Ok;
}

}  // namespace lan
}  // namespace pixc
// AI: end
