#pragma once

// AI: below section was generated by an AI
//
// Brute-force limiter for the LAN settings PIN (audit S3, 2026-09). Pure logic: time and addresses
// are passed in, so it is host-tested in test/pixc/ and holds no Arduino dependency.
//
// WHAT IT REPLACES. The LAN gate had a DEVICE-WIDE lockout: more than ten wrong PINs a minute from
// anybody locked out every caller not already remembered - and since D304 the app and ePixC Sync
// are never remembered (they send the PIN with every request), so any host on the Wi-Fi could keep
// the owner's own app and Sync locked out indefinitely without knowing anything. A denial of
// service that needed no credential.
//
// THE RULES, and the property each one buys:
//
//  1. Per-address exponential backoff. The n-th consecutive wrong PIN from one address makes that
//     address wait min(kBackoffBaseMs << (n-1), kBackoffMaxMs) before its next PIN is even looked
//     at. One host alone gets about 36 guesses a day. A right PIN clears the address's record.
//
//  2. A small global budget of wrong guesses: a token bucket of kBudgetBurst tokens refilled one
//     per kBudgetRefillMs (16 + 96 a day). Every wrong guess, from anyone, spends a token if one is
//     left. It caps what an attacker gains by spreading guesses over many addresses.
//
//  3. When the budget is spent, an address that has sent a wrong PIN during the current day is
//     refused without evaluation - but an address that has NOT is still evaluated. That is the rule
//     that protects the owner: the attacker's failures never stop a correct PIN from a different
//     host, because a host with no failures of its own is always heard. The "has failed today"
//     memory is one bit per fourth octet (256 bits), cleared every kEpochMs, so on a home /24 the
//     attacker can buy at most one extra guess per address per day this way.
//
//  4. A wrong PIN that equals the PIN this device held before its last change is not counted at all
//     (the caller decides that and calls neither onWrong nor onRight). The app and Sync, by design,
//     keep sending the old PIN until they see a 401 and then switch to the pending one (D305), and
//     that single stale try must not cost them anything.
//
// WORST CASE, all addresses of a /24 and an attacker who never stops: 16 + 96 budgeted guesses plus
// at most 256 more (one per unburned address) = at most ~368 wrong guesses a day against a 4-digit
// PIN - 50 % found in about two weeks. A single host: ~36 a day, about 140 days for 50 %. The real
// fix is a long LAN secret instead of a PIN (Pairing and LAN security v2, in the vault).
//
// What it does not claim: an address is not an identity. A host that can impersonate the owner's
// address on the LAN can burn that address - and could also read the PIN off the wire, since the
// LAN API is plain HTTP. The rules above are for attackers that cannot, which is everybody else.

#include <stddef.h>
#include <stdint.h>

namespace pixc {

class PinGuard {
 public:
  // `globalBudget` turns rules 2-3 on (needed for a 4-digit PIN). Pairing v2's 128-bit LAN key
  // cannot be guessed at any rate, so there it is off - no ceiling a stranger could spend - and
  // the guard is only a per-address brake on a misbehaving host, with `freeFails` wrong requests
  // in a row allowed before any backoff (a client tries the pre-rotation key once, by design).
  explicit PinGuard(bool globalBudget = true, uint8_t freeFails = 0)
      : _globalBudget(globalBudget), _freeFails(freeFails) {}

  static constexpr uint64_t kBackoffBaseMs = 1000;                  // first wrong PIN: wait 1 s
  static constexpr uint64_t kBackoffMaxMs = 60ULL * 60 * 1000;      // never more than 1 h
  static constexpr uint64_t kForgetAfterMs = 24ULL * 60 * 60 * 1000; // a quiet day forgives
  static constexpr uint8_t  kBudgetBurst = 16;
  static constexpr uint64_t kBudgetRefillMs = 15ULL * 60 * 1000;    // 96 tokens a day
  static constexpr uint64_t kEpochMs = 24ULL * 60 * 60 * 1000;      // burned bits cleared daily
  static constexpr uint8_t  kSlots = 16;

  // The byte of `ip` that tells hosts on one /24 apart. lwIP keeps an IPv4 address in network
  // order, so on the little-endian ESP32 `(uint32_t)IPAddress` holds the first octet in the low
  // byte and the fourth octet in the high byte.
  static uint8_t hostKey(uint32_t ip) { return static_cast<uint8_t>(ip >> 24); }

  // May this address's PIN be evaluated now? When it may not, `retryAfterMs` (if given) says how
  // long until it might, for a Retry-After header.
  bool mayTry(uint32_t ip, uint64_t now, uint64_t* retryAfterMs = nullptr) {
    tick(now);
    uint64_t wait = 0;
    const Slot* s = find(ip);
    if (s != nullptr && now < s->nextAt) wait = s->nextAt - now;
    if (wait == 0 && _globalBudget && _tokens == 0 && burned(ip)) {
      // Budget spent and this address has already failed today: wait for the next token.
      wait = kBudgetRefillMs - (now - _lastRefill);
    }
    if (retryAfterMs != nullptr) *retryAfterMs = wait;
    return wait == 0;
  }

  // A wrong PIN from `ip`, which mayTry() had allowed.
  void onWrong(uint32_t ip, uint64_t now) {
    tick(now);
    if (_globalBudget) {
      if (_tokens > 0) _tokens--;
      burn(ip);
    }
    Slot* s = slotFor(ip, now);
    if (s == nullptr) return;           // table full of addresses still backing off: rules 2-3 hold
    if (s->fails < 60) s->fails++;
    s->lastAt = now;
    if (s->fails <= _freeFails) { s->nextAt = now; return; }
    const uint8_t over = static_cast<uint8_t>(s->fails - _freeFails);
    const uint8_t shift = over - 1 > 40 ? 40 : static_cast<uint8_t>(over - 1);
    uint64_t backoff = kBackoffBaseMs << shift;
    if (backoff > kBackoffMaxMs) backoff = kBackoffMaxMs;
    s->lastAt = now;
    s->nextAt = now + backoff;
  }

  // A right PIN from `ip`: its own record is cleared. The global budget and burned bits are not.
  void onRight(uint32_t ip) {
    Slot* s = findMutable(ip);
    if (s != nullptr) *s = Slot{};
  }

  uint8_t tokens() const { return _tokens; }

 private:
  struct Slot { uint32_t ip = 0; uint8_t fails = 0; uint64_t lastAt = 0; uint64_t nextAt = 0; };

  void tick(uint64_t now) {
    if (!_started) { _started = true; _lastRefill = now; _epochStart = now; }
    while (_tokens < kBudgetBurst && now - _lastRefill >= kBudgetRefillMs) {
      _tokens++;
      _lastRefill += kBudgetRefillMs;
    }
    if (_tokens == kBudgetBurst) _lastRefill = now;   // a full bucket does not bank time
    if (now - _epochStart >= kEpochMs) {
      for (uint8_t i = 0; i < sizeof(_burned) / sizeof(_burned[0]); i++) _burned[i] = 0;
      _epochStart = now;
    }
    for (uint8_t i = 0; i < kSlots; i++) {
      if (_slots[i].ip != 0 && now >= _slots[i].nextAt && now - _slots[i].lastAt >= kForgetAfterMs)
        _slots[i] = Slot{};
    }
  }

  bool burned(uint32_t ip) const { const uint8_t k = hostKey(ip); return (_burned[k >> 5] >> (k & 31)) & 1U; }
  void burn(uint32_t ip) { const uint8_t k = hostKey(ip); _burned[k >> 5] |= 1UL << (k & 31); }

  const Slot* find(uint32_t ip) const {
    for (uint8_t i = 0; i < kSlots; i++) if (_slots[i].ip == ip) return &_slots[i];
    return nullptr;
  }
  Slot* findMutable(uint32_t ip) {
    for (uint8_t i = 0; i < kSlots; i++) if (_slots[i].ip == ip) return &_slots[i];
    return nullptr;
  }

  // The address's own slot, else a free one, else the longest-quiet slot that is no longer backing
  // off. Null when every slot is an address still waiting out its backoff.
  Slot* slotFor(uint32_t ip, uint64_t now) {
    Slot* s = findMutable(ip);
    if (s != nullptr) return s;
    Slot* pick = nullptr;
    for (uint8_t i = 0; i < kSlots; i++) {
      if (_slots[i].ip == 0) { pick = &_slots[i]; break; }
      if (now >= _slots[i].nextAt && (pick == nullptr || _slots[i].lastAt < pick->lastAt)) pick = &_slots[i];
    }
    if (pick != nullptr) { *pick = Slot{}; pick->ip = ip; }
    return pick;
  }

  bool _globalBudget;
  uint8_t _freeFails;
  Slot _slots[kSlots];
  uint32_t _burned[8] = {0, 0, 0, 0, 0, 0, 0, 0};
  uint8_t _tokens = kBudgetBurst;
  uint64_t _lastRefill = 0;
  uint64_t _epochStart = 0;
  bool _started = false;
};

}  // namespace pixc
// AI: end
