#include "wled.h"

#ifdef PIXC_LAN_AUTH

// AI: below section was generated by an AI
#include "pixc_device.h"
#include "../usermods/pixc_connect_blink/pixc_logic.h"

#include <Preferences.h>
#include <esp_random.h>
#include <esp_system.h>
#include <esp_wifi.h>
#include <nvs_flash.h>

namespace {
constexpr const char* kNsReset = "pixc_rst";      // the power-cycle counter
constexpr const char* kNsFactory = "pixc_fac";    // written by tools/factory_provision.py
constexpr uint32_t kPowerCycleClearMs = 10000;    // a boot this long is not part of a reset gesture

bool resetPending = false;
uint32_t rebootAt = 0;
bool counterCleared = false;
const char* resetWhy = "";
char bootId[9] = "";

void flashAmberThreeTimes() {
  // Blocking on purpose: nothing else matters now, and the loop watchdog is 20 s.
  const uint16_t n = strip.getLengthTotal();
  strip.setBrightness(160, true);
  for (uint8_t k = 0; k < 3; k++) {
    for (uint16_t i = 0; i < n; i++) strip.setPixelColor(i, RGBW32(255, 110, 0, 0));
    strip.show();
    delay(350);
    for (uint16_t i = 0; i < n; i++) strip.setPixelColor(i, 0);
    strip.show();
    delay(250);
  }
}
}  // namespace

void pixcRequestFactoryReset(const char* why) {
  if (resetPending) return;
  resetPending = true;
  resetWhy = why ? why : "";
  DEBUG_PRINTF("[ePixC] factory reset requested (%s)\n", resetWhy);
}

bool pixcFactoryResetPending() { return resetPending; }

void pixcFactoryWipeNow() {
  DEBUG_PRINTF("[ePixC] factory reset: wiping (%s)\n", resetWhy);
  // Wi-Fi configuration the ESP32 keeps in its own NVS namespace (WLED stores credentials there
  // with WiFi.persistent(true) on first connect).
  esp_wifi_restore();
  {
    Preferences p;
    if (p.begin(kNsReset, false)) { p.clear(); p.end(); }
  }
  // Everything on the filesystem: cfg.json, wsec.json (Wi-Fi PSK, device key, LAN key, broker
  // password), presets.json and any other file.
  WLED_FS.format();
  delay(100);
  ESP.restart();
  for (;;) {}
}

void pixcBootCounterOnBoot() {
  // Only a power-up counts. RTC memory does not survive a power cut, which is the very event being
  // counted, so the count lives in NVS (one small write per boot). A crash, watchdog or software
  // reboot clears it, so a crash loop can never wipe a unit.
  const esp_reset_reason_t r = esp_reset_reason();
  const bool powerUp = (r == ESP_RST_POWERON || r == ESP_RST_BROWNOUT);
  Preferences p;
  if (!p.begin(kNsReset, false)) return;
  const pixc::BootCount next = pixc::nextBootCount(p.getUChar("n", 0), powerUp);
  p.putUChar("n", next.stored);
  p.end();
  DEBUG_PRINTF("[ePixC] power-up count %u\n", (unsigned)next.stored);
  if (next.reset) pixcRequestFactoryReset("power-cycle");
}

void pixcRebootAfter(uint32_t ms) { rebootAt = millis() + (ms ? ms : 1); }

void pixcDeviceLoop() {
  if (rebootAt != 0 && (long)(millis() - rebootAt) >= 0) { rebootAt = 0; doReboot = true; }
  if (!counterCleared && millis() > kPowerCycleClearMs) {
    counterCleared = true;
    Preferences p;
    if (p.begin(kNsReset, false)) {
      if (p.getUChar("n", 0) != 0) p.putUChar("n", 0);
      p.end();
    }
  }
  if (resetPending) {
    flashAmberThreeTimes();
    pixcFactoryWipeNow();
  }
}

bool pixcFactoryApPsk(char* out, size_t cap) {
  if (out == nullptr || cap < 9) return false;
  out[0] = 0;
  Preferences p;
  if (p.begin(kNsFactory, true)) {
    p.getString("ap_psk", out, cap);
    p.end();
  }
  if (pixc::validApPsk(out)) return true;
#ifdef PIXC_DEV_AP_PSK
  strlcpy(out, PIXC_DEV_AP_PSK, cap);
  return pixc::validApPsk(out);
#else
  out[0] = 0;
  return false;
#endif
}

const char* pixcBootId() {
  if (bootId[0] == 0) snprintf(bootId, sizeof(bootId), "%08x", (unsigned)esp_random());
  return bootId;
}
// AI: end

#endif  // PIXC_LAN_AUTH
