#pragma once

// AI: below section was generated by an AI
//
// ePixC device lifecycle: factory reset (every path funnels here), the power-cycle reset counter,
// the factory hotspot password, and this boot's random id. Compiled with PIXC_LAN_AUTH.
//
// One wipe for every trigger - the cloud (`<base>/reset` with {"reset":true}), the signed LAN
// endpoint (POST /json/pixc/reset) and five short power-ups in a row - so they cannot drift apart.
// The old usermod reset removed cfg.json and wsec.json only, leaving presets, every other file and
// the Wi-Fi credentials the ESP32 keeps in NVS (audit S12).

#include <stddef.h>
#include <stdint.h>

// Ask for a factory reset. The strip flashes amber three times, then pixcFactoryWipeNow() runs
// from the loop. `why` goes to the debug log ("cloud", "lan", "power-cycle").
void pixcRequestFactoryReset(const char* why);
bool pixcFactoryResetPending();

// Format LittleFS (cfg, wsec with every key, presets, everything), erase the Wi-Fi configuration
// in NVS and the usermod's own NVS namespaces, then restart. Keeps `pixc_fac` (the factory hotspot
// password) and `pixc_ota` (the anti-rollback floor): a reset must not make a unit accept an older
// signed image, and the password printed on its label must keep working. Does not return.
[[noreturn]] void pixcFactoryWipeNow();

// Call once, early in setup: counts short power-ups in NVS, and requests a reset on the fifth.
void pixcBootCounterOnBoot();
// Call every loop: clears the counter once this boot has lasted kPowerCycleClearMs, and runs a
// pending reset.
void pixcDeviceLoop();

// The per-unit hotspot password from factory NVS (`pixc_fac/ap_psk`), or the dev fallback
// PIXC_DEV_AP_PSK. False when there is none: a release build then does not open the hotspot.
bool pixcFactoryApPsk(char* out, size_t cap);

// A random 32-bit value drawn at boot, as 8 lowercase hex characters. Returned by GET /json/id and
// bound into every LAN request signature, so a request captured before a reboot never replays.
const char* pixcBootId();
// AI: end
