#include "wled.h"

#ifdef PIXC_LAN_AUTH

// AI: below section was generated by an AI
#include "pixc_lan.h"
#include "pixc_lan_guard.h"
#include "pixc_lan_logic.h"
#include "pixc_device.h"
#include "../usermods/pixc_connect_blink/pixc_logic.h"

namespace {

pixc::lan::ReplayTable replay;
// Guards pixcLanKey, previousLanKey and `replay`: verify runs on the async_tcp task, a rotation from
// the cloud on the loop task. Created once by pixcLanBegin(), from initServer() before the server
// starts and before MQTT can deliver a rotation. It was created on first use, so a verify and a
// rotation racing to be first could each make one: one leaked, and that window had no exclusion
// (audit L6). Before pixcLanBegin() only the setup task runs, so there is nothing to exclude.
SemaphoreHandle_t keyMutex = nullptr;
struct KeyLock {
  KeyLock() { if (keyMutex) xSemaphoreTake(keyMutex, portMAX_DELAY); }
  ~KeyLock() { if (keyMutex) xSemaphoreGive(keyMutex); }
};

// A pairing POST, validated on the async_tcp task and applied on the loop (pixcLanLoop).
struct PendingPair {
  volatile bool ready = false;
  char ssid[33];
  char psk[65];
  char kDev[65];
  char kLan[33];
  char apiHost[64];
} pendingPair;
// A per-address brake on hosts sending bad signatures - no global ceiling (a 128-bit key cannot be
// guessed at any rate) and two free failures, so the one request a client signs with the key
// before a rotation costs nothing.
pixc::PinGuard authGuard(false, 2);
char previousLanKey[pixc::lan::kKeyHexLen + 1] = "";

// DDP leases (pixc::lan::LeaseTable). Granted on the async_tcp task, read on the UDP path; a lease
// is two aligned words, and a torn read can only refuse or admit one packet around a renewal.
pixc::lan::LeaseTable leases;

uint64_t nowMs64() { return static_cast<uint64_t>(esp_timer_get_time() / 1000); }

void sendError(AsyncWebServerRequest* request, int code, const char* err) {
  char body[48];
  snprintf(body, sizeof(body), "{\"error\":\"%s\"}", err);
  request->send(code, FPSTR(CONTENT_TYPE_JSON), body);
}

void sendLimited(AsyncWebServerRequest* request, uint64_t retryAfterMs) {
  const uint32_t secs = static_cast<uint32_t>(retryAfterMs / 1000) + 1;
  char body[48];
  snprintf(body, sizeof(body), "{\"error\":\"RATE_LIMITED\",\"retry_after\":%u}", (unsigned)secs);
  AsyncWebServerResponse* response = request->beginResponse(429, FPSTR(CONTENT_TYPE_JSON), body);
  response->addHeader(F("Retry-After"), String(secs));
  request->send(response);
}

// PATH_AND_QUERY as sent, or empty when it cannot be rebuilt exactly (pixc::lan::buildPathAndQuery).
String pathAndQuery(AsyncWebServerRequest* request) {
  String out;
  const bool ok = pixc::lan::buildPathAndQuery(out, request->url().c_str(), request->params(),
      [request](size_t i) {
        const AsyncWebParameter* p = request->getParam(i);
        if (p == nullptr || p->isPost() || p->isFile()) return pixc::lan::QueryParam{nullptr, nullptr, true};
        return pixc::lan::QueryParam{p->name().c_str(), p->value().c_str(), false};
      });
  return ok ? out : String();
}

bool validKey(const char* s, size_t n) { return pixc::lan::isLowerHex(s, n); }

// ---------------------------------------------------------------------------------------------
// /json/pixc/pair
// ---------------------------------------------------------------------------------------------

// The endpoint exists only on the hotspot, for a caller on the hotspot's own subnet.
bool pairReachable(AsyncWebServerRequest* request) {
  return apActive && pixc::lan::onHotspotSubnet(pixcCallerIp(request));
}

void handlePairGet(AsyncWebServerRequest* request) {
  if (!pairReachable(request)) { request->send(404); return; }
  char body[160];
  snprintf(body, sizeof(body), "{\"mac\":\"%s\",\"fw\":\"%s\",\"leds\":%u,\"state\":\"%s\"}",
           escapedMac.c_str(), versionString, (unsigned)strip.getLengthTotal(),
           pixcIsKeyed() ? "keyed" : "new");
  request->send(200, FPSTR(CONTENT_TYPE_JSON), body);
}

void handlePairPost(AsyncWebServerRequest* request) {
  if (!pairReachable(request)) { request->send(404); return; }
  const size_t len = request->contentLength();
  if (request->_tempObject == nullptr || !pixc::lan::pairBodySizeOk(len)) { sendError(request, 400, "BAD_REQUEST"); return; }
  StaticJsonDocument<768> doc;
  if (deserializeJson(doc, static_cast<const char*>(request->_tempObject), len)) { sendError(request, 400, "BAD_REQUEST"); return; }
  const char* ssid = doc["ssid"] | "";
  const char* psk = doc["psk"] | "";
  const char* kDev = doc["k_dev"] | "";
  const char* kLan = doc["k_lan"] | "";
  // Validate everything before storing anything: a malformed body stores nothing.
  if (!pixc::lan::validPairBody(ssid, psk, kDev, kLan)) {
    sendError(request, 400, "BAD_REQUEST");
    return;
  }
  // A keyed light takes a new Wi-Fi password only from the phone that paired it (same k_lan AND
  // k_dev, the wrong-password retry); anyone else must factory-reset it first.
  {
    KeyLock lock;
    if (pixc::lan::pairConflicts(pixcIsKeyed(), pixcLanKey, pixcDeviceKey, kLan, kDev)) {
      sendError(request, 409, "ALREADY_PAIRED");
      return;
    }
  }
  if (pendingPair.ready) { sendError(request, 409, "BUSY"); return; }
  strlcpy(pendingPair.ssid, ssid, sizeof(pendingPair.ssid));
  strlcpy(pendingPair.psk, psk, sizeof(pendingPair.psk));
  strlcpy(pendingPair.kDev, kDev, sizeof(pendingPair.kDev));
  strlcpy(pendingPair.kLan, kLan, sizeof(pendingPair.kLan));
  strlcpy(pendingPair.apiHost, doc["api_host"] | "", sizeof(pendingPair.apiHost));
  pendingPair.ready = true;   // applied by pixcLanLoop() on the loop task
  char body[40];
  snprintf(body, sizeof(body), "{\"mac\":\"%s\"}", escapedMac.c_str());
  request->send(200, FPSTR(CONTENT_TYPE_JSON), body);
}

// Apply a validated pairing on the loop task: Wi-Fi and both keys in one save, then reboot.
void applyPendingPair() {
  PendingPair& pp = pendingPair;
  // One network, the one the phone gave. Static addressing is not offered at pairing.
  selectedWiFi = 0;
  multiWiFi.resize(1);
  memset(multiWiFi[0].clientSSID, 0, sizeof(multiWiFi[0].clientSSID));
  memset(multiWiFi[0].clientPass, 0, sizeof(multiWiFi[0].clientPass));
  strlcpy(multiWiFi[0].clientSSID, pp.ssid, sizeof(multiWiFi[0].clientSSID));
  strlcpy(multiWiFi[0].clientPass, pp.psk, sizeof(multiWiFi[0].clientPass));
  multiWiFi[0].staticIP = IPAddress(0, 0, 0, 0);
  memset(multiWiFi[0].bssid, 0, sizeof(multiWiFi[0].bssid));
  {
    KeyLock lock;
    const bool sameKeys = strcmp(pixcLanKey, pp.kLan) == 0 && strcmp(pixcDeviceKey, pp.kDev) == 0;
    strlcpy(pixcDeviceKey, pp.kDev, sizeof(pixcDeviceKey));
    strlcpy(pixcLanKey, pp.kLan, sizeof(pixcLanKey));
    previousLanKey[0] = 0;
    if (!sameKeys) {
      // A new pairing starts with no broker login: the light pulls its own once registered. The
      // wrong-password retry (same keys) keeps whatever login it already has.
      mqttUser[0] = 0;
      mqttPass[0] = 0;
      mqttServer[0] = 0;
    }
  }
#ifdef EPIXC_ALLOW_PLAINTEXT_PROVISION
  // Bench only: the app may point the light at a local API ("host" or "host:port").
  if (pp.apiHost[0]) {
    StaticJsonDocument<192> um;
    char host[64];
    strlcpy(host, pp.apiHost, sizeof(host));
    char* colon = strchr(host, ':');
    JsonObject top = um.createNestedObject("PixcConnect");
    if (colon) { *colon = 0; top["apiPort"] = atoi(colon + 1); }
    top["apiHost"] = host;
    JsonObject umRoot = um.as<JsonObject>();
    UsermodManager::readFromConfig(umRoot);
  }
#endif
  memset(&pp, 0, sizeof(pp));   // clears `ready` too
  configNeedsWrite = true;      // cfg.json (SSID) + wsec.json (PSK, keys); WLED::loop() saves
  pixcRebootAfter(1500);        // let the reply leave before the hotspot goes
}

}  // namespace

// ---------------------------------------------------------------------------------------------

uint32_t pixcCallerIp(AsyncWebServerRequest* request) {
  AsyncClient* c = request ? request->client() : nullptr;
  return c ? static_cast<uint32_t>(c->remoteIP()) : 0;
}

bool pixcIsKeyed() { return validKey(pixcLanKey, pixc::lan::kKeyHexLen); }

bool pixcSetLanKey(const char* keyHex) {
  KeyLock lock;
  if (!validKey(keyHex, pixc::lan::kKeyHexLen) || strcmp(keyHex, pixcLanKey) == 0) return false;
  strlcpy(previousLanKey, pixcLanKey, sizeof(previousLanKey));
  strlcpy(pixcLanKey, keyHex, sizeof(pixcLanKey));
  // The replay table is NOT cleared: counters are per client and boot, not per key, and clearing
  // it would let a request captured under the pending key (clients try it by design) replay once.
  return true;
}

void pixcLanLoop() {
  if (pendingPair.ready) applyPendingPair();
}

bool pixcPreAuthorise(AsyncWebServerRequest* request) {
  uint64_t retry = 0;
  if (!authGuard.mayTry(pixcCallerIp(request), nowMs64(), &retry)) { sendLimited(request, retry); return false; }
  if (!pixcIsKeyed()) { sendError(request, 401, "UNAUTHORISED"); return false; }
  const AsyncWebHeader* h = request->getHeader(F("X-PixC-Auth"));
  pixc::lan::ParsedAuth pa;
  if (h == nullptr || !pixc::lan::parseAuthHeader(h->value().c_str(), pa)) {
    authGuard.onWrong(pixcCallerIp(request), nowMs64());
    sendError(request, 401, "UNAUTHORISED");
    return false;
  }
  if (strcmp(pa.bootId, pixcBootId()) != 0) { sendError(request, 401, "STALE_BOOT"); return false; }
  return true;
}

void pixcSerializeSecrets(JsonObject root) {
  JsonObject p = root.createNestedObject("pixc");
  p["lan"] = pixcLanKey;
  p["dev"] = pixcDeviceKey;
}

void pixcDeserializeSecrets(JsonObject root) {
  JsonObject p = root["pixc"];
  if (p.isNull()) return;
  const char* lan = p["lan"] | "";
  const char* dev = p["dev"] | "";
  strlcpy(pixcLanKey, validKey(lan, pixc::lan::kKeyHexLen) ? lan : "", sizeof(pixcLanKey));
  strlcpy(pixcDeviceKey, validKey(dev, 64) ? dev : "", sizeof(pixcDeviceKey));
}

bool pixcAuthorise(AsyncWebServerRequest* request, const uint8_t* body, size_t len, PixcReplySigner& out) {
  out.active = false;
  const uint32_t ip = pixcCallerIp(request);
  uint64_t retry = 0;
  if (!authGuard.mayTry(ip, nowMs64(), &retry)) { sendLimited(request, retry); return false; }
  const AsyncWebHeader* h = request->getHeader(F("X-PixC-Auth"));
  const String path = pathAndQuery(request);
  const String method(request->methodToString());   // "GET", "POST", ... upper case
  pixc::lan::ParsedAuth pa;
  pixc::lan::Verdict v;
  {
    KeyLock lock;
    v = pixc::lan::verify(h ? h->value().c_str() : nullptr, pixcLanKey, previousLanKey,
        pixcBootId(), method.c_str(), path.c_str(), body, len, replay, &pa);
  }
  if (v == pixc::lan::Verdict::Ok) {
    authGuard.onRight(ip);
    out.active = true;
    strlcpy(out.clientId, pa.clientId, sizeof(out.clientId));
    out.ctr = pa.ctr;
    return true;
  }
  // A bad signature slows its sender down. A stale boot id or a replayed counter is what an honest
  // client sees after a reboot or a lost reply, and the stale key what it sends once after a
  // rotation: none of those is counted.
  if (v == pixc::lan::Verdict::Unauthorised) authGuard.onWrong(ip, nowMs64());
  sendError(request, 401, pixc::lan::verdictCode(v));
  return false;
}

void pixcSignResponse(AsyncWebServerResponse* response, const PixcReplySigner& signer, const char* bodyHashHex) {
  if (!signer.active || response == nullptr) return;
  char sig[pixc::lan::kMacB64Len + 1];
  bool ok;
  { KeyLock lock; ok = pixc::lan::replySig(pixcLanKey, pixcBootId(), signer.ctr, signer.clientId, bodyHashHex, sig); }
  if (!ok) return;
  String v = F("v2 ");
  v += sig;
  response->addHeader(F("X-PixC-Sig"), v);
}

void pixcSendSigned(AsyncWebServerRequest* request, const PixcReplySigner& signer, int code,
                    const char* contentType, const char* body) {
  char bh[65];
  pixc::lan::bodyHashHex(reinterpret_cast<const uint8_t*>(body), strlen(body), bh);
  AsyncWebServerResponse* response = request->beginResponse(code, contentType, body);
  pixcSignResponse(response, signer, bh);
  request->send(response);
}

void pixcLanBegin() {
  if (keyMutex == nullptr) keyMutex = xSemaphoreCreateMutex();
}

void pixcRegisterRoutes(AsyncWebServer& srv) {
  // Who am I, unauthenticated: the MAC (which anyone on the LAN sees in ARP anyway) and this boot's
  // id, which every signed request must carry. A client reads it before its first request and after
  // any 401 STALE_BOOT. Registered before /json, whose handlers match every /json/... prefix.
  srv.on(F("/json/id"), HTTP_GET, [](AsyncWebServerRequest* request) {
    char body[80];
    snprintf(body, sizeof(body), "{\"mac\":\"%s\",\"boot_id\":\"%s\",\"v\":2}", escapedMac.c_str(), pixcBootId());
    request->send(200, FPSTR(CONTENT_TYPE_JSON), body);
  });
  srv.on(F("/json/pixc/pair"), HTTP_GET, handlePairGet);
  AsyncCallbackJsonWebHandler* pair = new AsyncCallbackJsonWebHandler(F("/json/pixc/pair"), handlePairPost);
  pair->setMaxContentLength(1024);
  srv.addHandler(pair);
}

bool pixcHandleAuthedPost(AsyncWebServerRequest* request, JsonObject root, const PixcReplySigner& signer) {
  // No LAN factory reset and no other /json/pixc/... action: one signed 404 for all (see
  // pixc::lan::isPixcNamespace). The realtime lease below travels on POST /json itself.
  if (pixc::lan::isPixcNamespace(request->url().c_str())) {
    pixcSendSigned(request, signer, 404, CONTENT_TYPE_JSON, pixc::lan::kNotFoundBody);
    return true;
  }
  JsonVariant lease = root["pixc"]["rt_lease"];
  if (!lease.isNull()) {
    leases.grant(pixcCallerIp(request), lease.as<int>(), millis());
  }
  root.remove("pixc");
  if (!lease.isNull() && root.size() == 0) {
    pixcSendSigned(request, signer, 200, CONTENT_TYPE_JSON, "{\"success\":true}");
    return true;
  }
  return false;
}

bool pixcRealtimeAllowed(uint32_t ip) { return leases.allowed(ip, millis()); }

void pixcSanitizeLanCfg(JsonObject root) { pixc::lan::sanitizeLanCfg(root); }
// AI: end

#endif  // PIXC_LAN_AUTH
