#pragma once

// AI: below section was generated by an AI
//
// The decisions in pixc_lan.cpp that need no web server: what the pairing endpoint accepts, which
// lease slot a caller gets, the signed path, and what a LAN config write may not touch. Pure, like
// pixc_lan_auth.h, so the host tests in test/pixc/ prove them (the final audit found none of
// pixc_lan.cpp tested). pixc_lan.cpp is the glue that feeds them from AsyncWebServer.

#include <stddef.h>
#include <stdint.h>
#include <string.h>

#include "pixc_lan_auth.h"

namespace pixc {
namespace lan {

// ---------------------------------------------------------------------------------------------
// PATH_AND_QUERY
// ---------------------------------------------------------------------------------------------

// RFC 3986 unreserved characters, plus '/' in a path.
inline bool unreserved(const char* s, bool path) {
  if (s == nullptr) return true;
  for (; *s; s++) {
    const char c = *s;
    const bool alnum = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9');
    if (alnum || c == '-' || c == '.' || c == '_' || c == '~' || (path && c == '/')) continue;
    return false;
  }
  return true;
}

// One query parameter as the server parsed it. `skip` for a POST body field or a file.
struct QueryParam {
  const char* name;
  const char* value;
  bool skip;
};

// PATH_AND_QUERY as sent. AsyncWebServer keeps only the percent-DECODED path and parsed parameters,
// not the request line, so the query is rebuilt from them in order as name=value joined by '&'.
// That is exact only when nothing was decoded, so a path or parameter outside RFC 3986's unreserved
// set (anything that needs %xx, or '+') is refused: false, and the request fails to verify.
// ePixC's clients send /json, /json/state, /json/cfg, /json/info and ?v=1-style queries only.
// A parameter sent with no '=' ("?flag") cannot be told from "?flag=" and is signed as the latter.
//
// `Str` is Arduino's String on the device and std::string in the tests; `get(i)` returns the i-th
// parameter as a QueryParam.
template <class Str, class GetParam>
bool buildPathAndQuery(Str& out, const char* path, size_t nParams, GetParam get) {
  if (path == nullptr || !unreserved(path, true)) return false;
  out = path;
  bool first = true;
  for (size_t i = 0; i < nParams; i++) {
    const QueryParam p = get(i);
    if (p.skip) continue;
    if (!unreserved(p.name, false) || !unreserved(p.value, false)) return false;
    out += first ? '?' : '&';
    first = false;
    out += p.name ? p.name : "";
    out += '=';
    out += p.value ? p.value : "";
  }
  return true;
}

// ---------------------------------------------------------------------------------------------
// /json/pixc/pair
// ---------------------------------------------------------------------------------------------

constexpr size_t kPairBodyMax = 1024;
constexpr size_t kDevKeyHexLen = 64;

// The hotspot's own subnet, 4.3.2.0/24, with lwIP's byte order (first octet lowest).
inline bool onHotspotSubnet(uint32_t ip) {
  return (ip & 0x00FFFFFFu) == (4u | (3u << 8) | (2u << 16));
}

inline bool pairBodySizeOk(size_t len) { return len > 0 && len <= kPairBodyMax; }

// A pairing body is stored only if every field is valid: SSID 1-32 bytes, a WPA2 key (8-63
// characters, 64 hex, or empty for an open network), K_dev 64 lowercase hex, K_lan 32 lowercase
// hex. Anything else is 400 and nothing is stored.
inline bool validPairBody(const char* ssid, const char* psk, const char* kDev, const char* kLan) {
  if (ssid == nullptr || psk == nullptr || kDev == nullptr || kLan == nullptr) return false;
  const size_t ssidLen = strlen(ssid);
  if (ssidLen == 0 || ssidLen > 32) return false;
  if (!validPsk(psk, strlen(psk))) return false;
  return isLowerHex(kDev, kDevKeyHexLen) && isLowerHex(kLan, kKeyHexLen);   // exact lengths
}

// A keyed light takes a new Wi-Fi password only from the phone that paired it: the same k_lan AND
// the same k_dev (the wrong-password retry). Anyone else - including a member or Sync, who hold
// k_lan but never k_dev - must factory-reset it first: true means 409 ALREADY_PAIRED. Both keys
// are compared in constant time. Call with a body validPairBody() accepted.
inline bool pairConflicts(bool keyed, const char* storedLan, const char* storedDev,
                          const char* kLan, const char* kDev) {
  if (!keyed) return false;
  const bool lanOk = equalConstTime(storedLan, kLan, kKeyHexLen);
  const bool devOk = equalConstTime(storedDev, kDev, kDevKeyHexLen);
  return !(lanOk && devOk);
}

// ---------------------------------------------------------------------------------------------
// Realtime (DDP) leases
// ---------------------------------------------------------------------------------------------

// Who may send DDP: an address that holds a lease from an authenticated POST /json
// {"pixc":{"rt_lease":N}}. Times are millis(), compared by unsigned difference so the wrap at
// ~49.7 days neither expires nor extends a lease.
class LeaseTable {
 public:
  static constexpr uint8_t kSlots = 4;
  static constexpr uint16_t kMaxS = 120;

  // Grant `ip` a lease of `wantS` seconds (capped at kMaxS), or release it with wantS <= 0. The
  // caller gets its own slot, else a free or expired one, else the one ending soonest.
  void grant(uint32_t ip, int wantS, uint32_t now) {
    if (ip == 0) return;
    const uint16_t secs = wantS <= 0 ? 0 : (wantS > kMaxS ? kMaxS : static_cast<uint16_t>(wantS));
    uint8_t slot = 0;
    for (uint8_t i = 0; i < kSlots; i++) {
      if (_l[i].ip == ip) { slot = i; break; }
      if (_l[i].ip == 0 || !live(i, now)) slot = i;
      else if (_l[slot].ip != 0 && live(slot, now) &&
               static_cast<int32_t>(_l[i].until - _l[slot].until) < 0) slot = i;
    }
    if (secs == 0) { if (_l[slot].ip == ip) _l[slot].ip = 0; return; }
    _l[slot].ip = ip;
    _l[slot].until = now + secs * 1000u;
  }

  bool allowed(uint32_t ip, uint32_t now) const {
    if (ip == 0) return false;
    for (uint8_t i = 0; i < kSlots; i++) if (_l[i].ip == ip && live(i, now)) return true;
    return false;
  }

 private:
  bool live(uint8_t i, uint32_t now) const { return static_cast<int32_t>(now - _l[i].until) < 0; }
  struct Lease { uint32_t ip; uint32_t until; };
  Lease _l[kSlots] = {};
};

// ---------------------------------------------------------------------------------------------
// LAN /json/cfg writes
// ---------------------------------------------------------------------------------------------

// Remove what a LAN config write may not change: the broker (if.mqtt), the access point, OTA
// settings, the settings PIN, ePixC's own section and the usermod's provisioning keys. The keys
// are written only at pairing and by the cloud. `Obj` is ArduinoJson's JsonObject.
template <class Obj>
void sanitizeLanCfg(Obj root) {
  Obj ifs = root["if"];
  if (!ifs.isNull()) ifs.remove("mqtt");
  root.remove("ap");
  root.remove("ota");
  root.remove("pin");
  root.remove("pixc");
  Obj um = root["um"];
  if (!um.isNull()) um.remove("PixcConnect");
}

}  // namespace lan
}  // namespace pixc
// AI: end
