#pragma once

// AI: below section was generated by an AI
//
// Pure decision logic for the ePixC usermod, kept free of Arduino, WLED and ESP-IDF headers so it
// compiles on a desktop and is exercised by the host tests in test/pixc/ (run: test/pixc/run.sh).
//
// The rule for what lives here: anything whose failure is silent on the device. S1 of the
// 2026-09 firmware audit was a string comparison that could never match - the usermod compared the
// FULL topic after WLED had already stripped the device prefix - and it disabled cloud config,
// factory reset and OTA for every unit without a single error message. A one-line host test would
// have caught it. Functions that touch hardware stay in the .cpp; the arithmetic and parsing they
// depend on comes here, where it can be proved.

#include <stddef.h>
#include <stdint.h>
#include <string.h>

namespace pixc {

// ---------------------------------------------------------------------------------------------
// MQTT topic routing
// ---------------------------------------------------------------------------------------------

enum class Topic : uint8_t { None, Cfg, Reset, Ota };

// Classify a topic as delivered to Usermod::onMqttMessage().
//
// WLED's MQTT handler (wled00/mqtt.cpp, onMqttMessage) strips `mqttDeviceTopic` before calling
// the usermods, so a subscription to `epixc/v1/d/<mac>/cfg` arrives here as "/cfg". A topic that
// did NOT start with the device prefix arrives unstripped. Both forms are accepted, and each is
// compared EXACTLY: "/ota/progress" is a topic this device publishes and must never be mistaken
// for an OTA command, and "/cfgX" is nothing.
//
// `deviceTopic` may be null or empty, in which case only the stripped form can match.
inline Topic classifyTopic(const char* topic, const char* deviceTopic) {
  if (topic == nullptr) return Topic::None;
  const char* rest = topic;
  const size_t baseLen = deviceTopic ? strlen(deviceTopic) : 0;
  if (baseLen > 0 && strncmp(topic, deviceTopic, baseLen) == 0) rest = topic + baseLen;
  if (strcmp(rest, "/cfg") == 0) return Topic::Cfg;
  if (strcmp(rest, "/reset") == 0) return Topic::Reset;
  if (strcmp(rest, "/ota") == 0) return Topic::Ota;
  return Topic::None;
}


// ---------------------------------------------------------------------------------------------
// Secret redaction for debug output
// ---------------------------------------------------------------------------------------------

namespace detail {
inline char lower(char c) { return (c >= 'A' && c <= 'Z') ? static_cast<char>(c - 'A' + 'a') : c; }

inline bool keyEquals(const char* k, size_t n, const char* lit) {
  size_t i = 0;
  for (; i < n && lit[i] != 0; i++) if (lower(k[i]) != lit[i]) return false;
  return i == n && lit[i] == 0;
}

inline bool keyContains(const char* k, size_t n, const char* lit) {
  const size_t m = strlen(lit);
  for (size_t i = 0; i + m <= n; i++) {
    size_t j = 0;
    while (j < m && lower(k[i + j]) == lit[j]) j++;
    if (j == m) return true;
  }
  return false;
}

inline bool keyEndsWith(const char* k, size_t n, const char* lit) {
  const size_t m = strlen(lit);
  return n >= m && keyEquals(k + n - m, m, lit);
}
}  // namespace detail

// True for a JSON key whose value is a credential: the settings PIN (`pin`, `settingsPin`), Wi-Fi
// and MQTT pre-shared keys (`psk`), passwords (`pass`, `password`, `pwd`, `mqttPass`, `otaPass`),
// and anything named like a key, token or secret. Case-insensitive. Deliberately broad: a false
// positive costs one starred-out debug value, a false negative prints a customer's Wi-Fi password.
inline bool isSecretKey(const char* k, size_t n) {
  using namespace detail;
  return keyEndsWith(k, n, "pin") || keyContains(k, n, "psk") || keyContains(k, n, "pass") ||
         keyContains(k, n, "pwd") || keyContains(k, n, "secret") || keyContains(k, n, "token") ||
         keyEquals(k, n, "key") || keyEndsWith(k, n, "_key") || keyEndsWith(k, n, "apikey");
}

// Overwrite, in place, the value of every secret-named key in a JSON text with '*' - string values
// between their quotes, bare values (numbers, true/false) up to the next delimiter. The text keeps
// its length and structure, so a debug print still shows which fields arrived. Not a JSON parser:
// it only has to be right for the keys that matter and never read past the terminator.
inline void redactJsonSecrets(char* s) {
  if (s == nullptr) return;
  char* p = s;
  while (*p) {
    if (*p != '"') { p++; continue; }
    char* keyStart = ++p;                              // candidate key: scan to its closing quote
    while (*p && *p != '"') { if (*p == '\\' && p[1]) p++; p++; }
    if (!*p) return;
    const size_t keyLen = static_cast<size_t>(p - keyStart);
    p++;                                               // past the closing quote
    char* q = p;
    while (*q == ' ' || *q == '\t' || *q == '\r' || *q == '\n') q++;
    if (*q != ':') continue;                           // it was a string value, not a key
    q++;
    while (*q == ' ' || *q == '\t' || *q == '\r' || *q == '\n') q++;
    if (!isSecretKey(keyStart, keyLen)) { p = q; continue; }
    if (*q == '"') {
      q++;
      while (*q && *q != '"') {
        if (*q == '\\' && q[1]) { *q++ = '*'; }
        *q++ = '*';
      }
      p = *q ? q + 1 : q;
    } else if (*q != '{' && *q != '[') {
      while (*q && *q != ',' && *q != '}' && *q != ']' && *q != ' ' && *q != '\n') *q++ = '*';
      p = q;
    } else {
      p = q;                                           // an object/array under a secret name: descend
    }
  }
}

// ---------------------------------------------------------------------------------------------
// Retry timing
// ---------------------------------------------------------------------------------------------

// Exponential backoff with jitter: the attempt-th retry waits a random time in [d/2, d], where
// d = min(baseMs * 2^attempt, maxMs). `rnd` is any 32-bit random value (esp_random() on the device).
//
// The jitter is the point. After a broker restart or a neighbourhood power cut the whole fleet
// disconnects in the same second; with a fixed retry they all come back in the same second too,
// each doing an RSA-4096 chain verification, and the broker sees a thundering herd on every retry.
// Spreading each wave over half its interval turns that spike into a ramp.
inline uint32_t backoffWithJitter(uint8_t attempt, uint32_t baseMs, uint32_t maxMs, uint32_t rnd) {
  uint64_t d = baseMs;
  for (uint8_t i = 0; i < attempt && d < maxMs; i++) d <<= 1;
  if (d > maxMs) d = maxMs;
  const uint64_t half = d / 2;
  const uint64_t span = d - half + 1;
  return static_cast<uint32_t>(half + (rnd % span));
}

// The pairing v2 provisioning schedule: d = min(base * 2^attempt, max), then +-20 % jitter
// (vault: Pairing and LAN security v2, "Provisioning on the light").
inline uint32_t backoffPlusMinus20(uint8_t attempt, uint32_t baseMs, uint32_t maxMs, uint32_t rnd) {
  uint64_t d = baseMs;
  for (uint8_t i = 0; i < attempt && d < maxMs; i++) d <<= 1;
  if (d > maxMs) d = maxMs;
  const uint64_t lo = d * 8 / 10, span = d * 4 / 10 + 1;
  return static_cast<uint32_t>(lo + (rnd % span));
}

// ---------------------------------------------------------------------------------------------
// JSON string escaping
// ---------------------------------------------------------------------------------------------

// Write `in` into `out` as the inside of a JSON string: quote, backslash and control characters
// escaped, everything else (UTF-8 included) copied. Always NUL-terminates; never splits an escape;
// stops early rather than overflow. Returns the number of characters written.
//
// Audit C2: an SSID is up to 32 arbitrary bytes, and one containing `"` or `\` made the health
// JSON invalid, so the backend dropped the whole message and the network screen went blank.
inline size_t jsonEscape(const char* in, char* out, size_t cap) {
  if (out == nullptr || cap == 0) return 0;
  size_t o = 0;
  static const char* hex = "0123456789abcdef";
  for (const unsigned char* p = reinterpret_cast<const unsigned char*>(in ? in : ""); *p; p++) {
    char esc[7];
    size_t n = 0;
    switch (*p) {
      case '"':  esc[0] = '\\'; esc[1] = '"';  n = 2; break;
      case '\\': esc[0] = '\\'; esc[1] = '\\'; n = 2; break;
      case '\n': esc[0] = '\\'; esc[1] = 'n';  n = 2; break;
      case '\r': esc[0] = '\\'; esc[1] = 'r';  n = 2; break;
      case '\t': esc[0] = '\\'; esc[1] = 't';  n = 2; break;
      default:
        if (*p < 0x20) {
          esc[0] = '\\'; esc[1] = 'u'; esc[2] = '0'; esc[3] = '0';
          esc[4] = hex[*p >> 4]; esc[5] = hex[*p & 0xF]; n = 6;
        } else {
          esc[0] = static_cast<char>(*p); n = 1;
        }
    }
    if (o + n >= cap) break;
    for (size_t i = 0; i < n; i++) out[o++] = esc[i];
  }
  out[o] = 0;
  return o;
}

// ---------------------------------------------------------------------------------------------
// Factory reset gesture and factory data
// ---------------------------------------------------------------------------------------------

// Five power-ups in a row, each cut before it has run 10 s, request a factory reset (Pairing and
// LAN security v2, "Factory reset"). `prev` is the stored count; any boot that is not a power-up
// (crash, watchdog, software reboot) clears it, so only a person at the switch can do it.
struct BootCount { uint8_t stored; bool reset; };
constexpr uint8_t kPowerCyclesToReset = 5;
inline BootCount nextBootCount(uint8_t prev, bool powerUp) {
  if (!powerUp) return {0, false};
  const uint8_t n = prev >= kPowerCyclesToReset ? kPowerCyclesToReset : static_cast<uint8_t>(prev + 1);
  if (n >= kPowerCyclesToReset) return {0, true};
  return {n, false};
}

// The factory hotspot password: 8-63 printable ASCII for WPA2. The factory tool writes 10
// characters from [a-z2-9]; anything outside WPA2's rules is treated as absent.
inline bool validApPsk(const char* s) {
  if (s == nullptr) return false;
  const size_t n = strlen(s);
  if (n < 8 || n > 63) return false;
  for (size_t i = 0; i < n; i++) if (s[i] < 0x20 || s[i] > 0x7e) return false;
  return true;
}

// The hotspot name, "ePixC-" plus the last four hex digits of the MAC in upper case. `mac` is the
// 12-hex escapedMac. Two units in range are told apart, and the app joins the one it scanned.
inline void hotspotName(const char* mac, char* out, size_t cap) {
  if (out == nullptr || cap == 0) return;
  const size_t n = mac ? strlen(mac) : 0;
  char tail[5] = "0000";
  if (n >= 4) {
    for (int i = 0; i < 4; i++) {
      const char c = mac[n - 4 + i];
      tail[i] = (c >= 'a' && c <= 'f') ? static_cast<char>(c - 'a' + 'A') : c;
    }
  }
  const char* base = "ePixC-";
  size_t o = 0;
  for (const char* b = base; *b && o + 1 < cap; b++) out[o++] = *b;
  for (int i = 0; i < 4 && o + 1 < cap; i++) out[o++] = tail[i];
  out[o] = 0;
}

// ---------------------------------------------------------------------------------------------
// OTA anti-rollback (audit S6)
// ---------------------------------------------------------------------------------------------
//
// Every image carries one BuildDesc, a 16-byte magic followed by its build number and security
// version. It sits inside the image bytes, so the detached ECDSA signature the backend already
// makes (SigningService, SHA256withECDSA over the whole image) covers it: the version cannot be
// changed without breaking the signature, and no backend change is needed to bind it. The OTA
// download scans the stream for the magic and refuses an image that is older than the running one
// (build) or below the stored anti-rollback floor (security), before it is ever made bootable.

// Raise by hand, in a release that fixes a vulnerability which must never be installable again.
// A unit stores the highest value it has run (NVS pixc_ota/sec, kept across factory reset) and
// refuses any image below it - even one signed by us.
#ifndef PIXC_SECURITY_VERSION
#define PIXC_SECURITY_VERSION 1
#endif

constexpr size_t kBuildMagicLen = 16;
// The magic, spelled as bytes so the only copy of the sequence in an image is the descriptor.
#define PIXC_BUILD_MAGIC {'e','P','i','X','C','-','B','U','I','L','D','D','E','S','C', 0x01}

struct BuildDesc {
  uint8_t magic[kBuildMagicLen];
  uint32_t build;      // little endian, monotonic (pio-scripts/pixc_build_id.py)
  uint32_t security;   // little endian, anti-rollback floor
};

// Finds the first BuildDesc in a byte stream fed in arbitrary chunks. `magic` is the running
// image's own descriptor magic (so the pattern exists once in each image, as the descriptor).
// The first byte of the magic occurs nowhere else in it, so restarting a partial match at the
// current byte is exact.
class DescScanner {
 public:
  explicit DescScanner(const uint8_t* magic) : _magic(magic) {}
  void feed(const uint8_t* p, size_t n) {
    for (size_t i = 0; i < n && !_found; i++) step(p[i]);
  }
  bool found() const { return _found; }
  uint32_t build() const { return _build; }
  uint32_t security() const { return _security; }

 private:
  void step(uint8_t b) {
    if (_matched < kBuildMagicLen) {
      if (b == _magic[_matched]) { _matched++; return; }
      _matched = (b == _magic[0]) ? 1 : 0;
      return;
    }
    const size_t k = _matched - kBuildMagicLen;      // 0..7: the two little-endian words
    if (k < 4) _build |= static_cast<uint32_t>(b) << (8 * k);
    else       _security |= static_cast<uint32_t>(b) << (8 * (k - 4));
    if (++_matched == kBuildMagicLen + 8) _found = true;
  }
  const uint8_t* _magic;
  size_t _matched = 0;
  bool _found = false;
  uint32_t _build = 0, _security = 0;
};

// Why an image may not be installed, or nullptr if it may.
inline const char* otaRefusal(bool found, uint32_t newBuild, uint32_t newSecurity,
                              uint32_t runningBuild, uint32_t securityFloor) {
  if (!found) return "no build descriptor";
  if (newSecurity < securityFloor) return "security downgrade";
  if (newBuild < runningBuild) return "downgrade";
  return nullptr;
}

}  // namespace pixc
// AI: end
