#include "wled.h"
#include <HTTPClient.h>
#include <Preferences.h>
#include <Update.h>
#include "mbedtls/sha256.h"
#include "mbedtls/pk.h"
#include "mbedtls/md.h"
// The public half of the firmware signing key. Empty by default, which refuses every update.
#include "pixc_ota_pubkey.h"
// esp_reset_reason(). Reached through Arduino's headers on ESP32 anyway, but named here because
// this file uses it directly and an implicit include is a trap when the framework moves.
#include <esp_system.h>
// esp_ota_get_state_partition() / esp_ota_mark_app_valid_cancel_rollback(): the app half of
// bootloader rollback. See confirmImageIfPending().
#include <esp_ota_ops.h>
// CONFIG_APP_ROLLBACK_ENABLE. Reached implicitly through Arduino's headers, but named here for
// the same reason esp_system.h is: this file reads it directly, and the value comes from the
// prebuilt framework's sdkconfig rather than from anything in this repository.
#include <sdkconfig.h>
// The TLS fetch lives in its own translation unit: ESP-IDF's HTTP client header and
// ESPAsyncWebServer both declare HTTP_GET/HTTP_PATCH, and a WLED usermod needs both. See
// pixc_https.cpp for why Arduino's WiFiClientSecure is not an option here.
#include "pixc_https.h"
// The RGB/RGBW width table, and the build-time assertion that the compiled-in bus is a width the
// cloud is able to set. Read the header before touching applyLedWidth().
#include "pixc_led_bus.h"
// Host-testable decisions (topic routing, ...). See test/pixc/.
#include "pixc_logic.h"
// Factory reset, power-cycle counter, factory hotspot password, boot id.
#include "../../wled00/pixc_device.h"
#ifdef PIXC_LAN_AUTH
#include "../../wled00/pixc_lan.h"
#endif

// ePixC API host the device calls to learn its MQTT broker (see provision()).
// Normally written by the app during pairing (um.PixcConnect.apiHost); this is
// only the fallback for a unit that never completed setup. The broker itself is
// never hardcoded — it is always fetched from this API.
//
// The default used to be a host on the pre-rename domain, which ePixC does not own. Anyone who
// registered it would have been asked, by every un-paired unit, which MQTT broker
// to connect to. The real host is api.epixc.in (see deploy/caddy/Caddyfile).
//
// The dev LAN address lives in the PixC_V1_dev build env, not here, so it cannot
// reach a release build by being the value someone forgot to change back.
#ifndef PIXC_API_HOST
  #define PIXC_API_HOST "api.epixc.in"
#endif
#ifndef PIXC_API_PORT
  #define PIXC_API_PORT 443
#endif
// Last-resort broker fallback ONLY if the API can't be reached at all.
#ifndef PIXC_MQTT_HOST
  #define PIXC_MQTT_HOST ""
#endif
// The broker port when the provisioning reply names none: 8883, MQTT over TLS - the only port ePixC
// publishes and the only one a release build will connect to (pixc_mqtt_client.cpp). It was 1883,
// so a reply missing `mqtt_port` sent the per-device credential in plaintext (audit S10).
#ifndef PIXC_MQTT_PORT
  #define PIXC_MQTT_PORT 8883
#endif

// ePixC device-edge usermod. Two jobs:
//
//  1. MQTT bridge to the ePixC cloud (epixc-mqtt broker). WLED's native MQTT
//     topics/payloads don't match the ePixC contract, so this usermod:
//       - forces the device topic to `epixc/v1/d/{mac}` (full MAC, lowercase) so
//         WLED subscribes `epixc/v1/d/{mac}/api` for commands;
//       - publishes `announce` (once on connect), `state` and `health` to
//         `epixc/v1/d/{mac}/{kind}` in the shapes epixc-mqtt expects.
//
//  2. On the first successful MQTT (cloud) connect after Wi-Fi is up — i.e.
//     right after initial setup / pairing — flash the strip solid green for
//     3 seconds, then restore the previous color / brightness / effect.
//
// Requires MQTT compiled in (do NOT set WLED_DISABLE_MQTT).

#ifdef PIXC_CONFIRM_ON_BROKER
// D35: the framework's initArduino() confirms a PENDING_VERIFY image before setup() unless this weak
// hook (cores/esp32/esp32-hal-misc.c) says to verify later. The usermod confirms on broker connect.
extern "C" bool verifyRollbackLater() { return true; }
#endif

// The build identity (pio-scripts/pixc_build_id.py). Absent in a build without that script.
#ifndef PIXC_FW_BUILD
  #define PIXC_FW_BUILD 0
#endif
#ifndef PIXC_FW_GIT
  #define PIXC_FW_GIT "unknown"
#endif

// This image's build descriptor (audit S6, pixc_logic.h). Inside the signed bytes, so an OTA image
// cannot lie about its version without failing the signature. Referenced by the OTA scanner, which
// also keeps the linker from dropping it.
extern "C" __attribute__((used)) const pixc::BuildDesc pixc_build_desc = {
  PIXC_BUILD_MAGIC, (uint32_t)PIXC_FW_BUILD, (uint32_t)PIXC_SECURITY_VERSION
};

// AI: below section was generated by an AI
// =============================================================================================
// NETWORK WORKER (audit R1)
// =============================================================================================
// Every blocking network operation the usermod makes - the provisioning HTTPS call and the OTA
// download, verify and flash - runs on this one FreeRTOS task, never on the LED loop.
//
// Before this, provisioning ran from loop() every 10 s until it succeeded, blocking up to 8 s for a
// TLS handshake plus DNS: with the API unreachable, effects and transitions froze for most of every
// ten seconds, and the watchdog was switched off (WLED_WATCHDOG_TIMEOUT=0) so that blocking was
// "allowed". OTA froze the strip for the whole download.
//
// The worker touches NO WLED state. The loop posts a self-contained job (every string copied into
// fixed buffers, so a second MQTT command cannot free what the worker is reading - the use-after-
// free audit R2 found in the old _otaUrl/_otaSha Strings) and drains results on its own schedule,
// applying them to WLED globals itself. Update.* is used only here; nothing else writes the
// inactive OTA partition.
namespace pixc_net {

constexpr size_t kUrlMax = 256;

struct Job {
  enum Kind : uint8_t { Provision, Ota } kind;
  bool tls;                         // Provision: HTTPS (always, in a release build)
  char url[kUrlMax];                // Provision: the full provisioning URL; Ota: the image URL
  char sigUrl[kUrlMax];             // Ota
  char jobId[48];                   // Ota
  char sha256[65];                  // Ota
  char version[33];                 // Ota (for the log only)
};

struct Result {
  enum Kind : uint8_t { ProvisionOk, ProvisionFailed, OtaProgress } kind;
  char host[MQTT_MAX_SERVER_LEN + 1];   // ProvisionOk
  uint16_t port;                         // ProvisionOk
  bool registered;                       // ProvisionOk
  char jobId[48];                        // OtaProgress
  char status[16];                       // OtaProgress: downloading/installing/done/failed
  int8_t percent;                        // OtaProgress
  char err[48];                          // OtaProgress / ProvisionFailed
};

// The anti-rollback floor: the highest security version this unit has run (NVS pixc_ota/sec).
// Set on the loop task in setup(), before the worker starts; read-only afterwards.
uint32_t securityFloor = PIXC_SECURITY_VERSION;

QueueHandle_t jobs = nullptr;
QueueHandle_t results = nullptr;
volatile bool busy = false;             // a job is running; read by the loop, written here

void post(const Result& r) { xQueueSend(results, &r, pdMS_TO_TICKS(200)); }

void otaProgress(const Job& j, const char* status, int pct, const char* err = nullptr) {
  Result r = {};
  r.kind = Result::OtaProgress;
  strlcpy(r.jobId, j.jobId, sizeof(r.jobId));
  strlcpy(r.status, status, sizeof(r.status));
  r.percent = (int8_t)pct;
  if (err) strlcpy(r.err, err, sizeof(r.err));
  post(r);
}

#ifdef EPIXC_ALLOW_PLAINTEXT_PROVISION
// Plaintext GET, bench only - and absent from a release image rather than merely unreachable in
// it. Unreachable-by-argument is how the ticket 33 defect survived, so it is compiled out instead.
int httpGet(const char* url, char* out, size_t cap) {
  WiFiClient client;
  HTTPClient http;
  http.setConnectTimeout(4000);
  if (!http.begin(client, url)) return -1;
  int len = -1;
  if (http.GET() == 200) {
    String payload = http.getString();
    len = payload.length() < cap ? payload.length() : cap - 1;
    memcpy(out, payload.c_str(), len);
    out[len] = 0;
  }
  http.end();
  return len;
}
#endif

void doProvision(const Job& j) {
  Result r = {};
  r.kind = Result::ProvisionFailed;
  // A TLS handshake needs roughly 40 KB of heap for the record buffers and the certificate chain.
  // Attempting one below that does not fail cleanly - it fails somewhere inside mbedTLS.
  if (j.tls && ESP.getFreeHeap() < 50000) { strlcpy(r.err, "low memory", sizeof(r.err)); post(r); return; }

  char body[768];
#ifdef EPIXC_ALLOW_PLAINTEXT_PROVISION
  const int len = j.tls ? pixcHttpsGet(j.url, body, sizeof(body)) : httpGet(j.url, body, sizeof(body));
#else
  const int len = pixcHttpsGet(j.url, body, sizeof(body));
#endif
  if (len <= 0) { strlcpy(r.err, "fetch", sizeof(r.err)); post(r); return; }

  DynamicJsonDocument doc(640);
  if (deserializeJson(doc, body, len)) { strlcpy(r.err, "json", sizeof(r.err)); post(r); return; }
  JsonObject d = doc["data"].isNull() ? doc.as<JsonObject>() : doc["data"].as<JsonObject>();
  // API serializes snake_case (mqtt_host/mqtt_port); accept camelCase too.
  const char* host = d["mqtt_host"] | (d["mqttHost"] | "");
  const int port = d["mqtt_port"] | (d["mqttPort"] | 0);
  if (host == nullptr || host[0] == 0 || strlen(host) > MQTT_MAX_SERVER_LEN) {
    strlcpy(r.err, "no mqtt_host", sizeof(r.err)); post(r); return;
  }
  r.kind = Result::ProvisionOk;
  strlcpy(r.host, host, sizeof(r.host));
  r.port = (port > 0 && port < 65536) ? (uint16_t)port : 0;   // 0 = not given; the loop decides
  r.registered = d["registered"] | false;
  post(r);
}

void hex32(const uint8_t* d, char* out /* >=65 */) {
  static const char* H = "0123456789abcdef";
  for (int i = 0; i < 32; i++) { out[i*2] = H[d[i] >> 4]; out[i*2+1] = H[d[i] & 0xF]; }
  out[64] = 0;
}

// Verify a detached ECDSA P-256 signature over the image's SHA-256 digest.
//
// This is the check that makes an OTA safe to apply: the SHA-256 alone only proves the image
// arrived intact from whoever sent it, and the digest travels in the same MQTT command as the
// URL. The signature proves it came from the holder of the ePixC signing key, which no broker,
// proxy or DNS answer can forge.
//
// The signature is small - a P-256 signature is 70-72 bytes of DER - so it is read whole, by
// LENGTH (DER contains NUL bytes), over TLS against the pinned roots. Fetched *after* the image so
// it cannot be swapped between the check and the flash. Returns a failure reason, or nullptr.
const char* verifySignature(const char* sigUrl, const uint8_t* digest) {
  if (sizeof(PIXC_OTA_PUBKEY_PEM) <= 1) return "no signing key in firmware";
  if (sigUrl == nullptr || sigUrl[0] == 0) return "signature fetch";

  uint8_t sig[80];
  const int got = pixcHttpsGetBinary(sigUrl, sig, sizeof(sig), 10000);
  if (got <= 0) return "signature fetch";

  mbedtls_pk_context pk;
  mbedtls_pk_init(&pk);
  // The length includes the terminating NUL: mbedtls treats a PEM as a NUL-counted buffer.
  int rc = mbedtls_pk_parse_public_key(&pk, (const unsigned char*)PIXC_OTA_PUBKEY_PEM,
                                       sizeof(PIXC_OTA_PUBKEY_PEM));
  if (rc != 0) { mbedtls_pk_free(&pk); return "bad signing key"; }

  rc = mbedtls_pk_verify(&pk, MBEDTLS_MD_SHA256, digest, 32, sig, (size_t)got);
  mbedtls_pk_free(&pk);
  return rc == 0 ? nullptr : "signature mismatch";
}

  // Download the firmware image over TLS and flash it to the inactive OTA partition, verifying
  // SHA-256 and then the detached signature before committing the new image as bootable.
  // Streams in chunks so a ~1.8MB image never has to fit in RAM. Runs on the network worker task,
  // never on the LED loop (audit R1): the loop keeps rendering while ~1.5 MB downloads.
  //
  // **Why this is TLS with the same pinned roots as everything else**, rather than the plaintext
  // fetch it used to be, or a deliberately weaker transport chosen to keep CA risk apart.
  //
  // It used to build a bare `WiFiClient` and hand it to `HTTPClient::begin()` with an https URL.
  // That call ACCEPTS the scheme — it sets `_port = 443` and `_secure = true` and returns true —
  // but `_secure` only ever reaches cookie handling; `connect()` calls `_client->connect()` on
  // the plain client it was given. So the device opened a TCP socket to Caddy's TLS listener and
  // wrote a plaintext request into it. That connection cannot complete, which means the cloud
  // OTA download could never have worked against production at all.
  //
  // The reflex worry about fixing it this way is blast radius: PIXC_TRUSTED_ROOTS also gates the
  // provisioning fetch, `PixC_V1` sets WLED_DISABLE_OTA so a shipped unit has no local update
  // path, and the only repair channel for a bad root is an OTA — so putting the download behind
  // the same roots looks like betting both halves on one CA event.
  //
  // It is not, because the download is already strictly downstream of those roots. Reaching this
  // function requires, in order: provisioning (doProvision()) to succeed over HTTPS pinned to
  // PIXC_TRUSTED_ROOTS (and `connected()` clears `_provisioned` on every Wi-Fi connect, so this
  // happens every boot — the broker is never remembered across one); then an MQTT connection on
  // 8883, which `pixc_mqtt_client.cpp` also pins to PIXC_TRUSTED_ROOTS; then an `ota` command
  // arriving on that connection to be staged as a job. If both roots go bad, no OTA command is ever delivered and the fleet is unreachable
  // long before the download's trust store matters.
  //
  // That also disposes of the alternatives, which all pay something for nothing:
  //   - plaintext, leaning on the signature: gives up confidentiality and lets a network
  //     attacker choose which signed version a unit installs (an old one with a known bug is
  //     still correctly signed), and buys no recoverability, since the command that starts the
  //     download still needs the roots.
  //   - `setInsecure()`: encrypts against a passive observer but authenticates nobody, so an
  //     active attacker substitutes the image freely — and again buys no recoverability.
  //   - a DIFFERENT root pinned for the firmware host: strictly worse. It cannot help (the
  //     command channel still needs the original roots) and it ADDS a second independent CA that
  //     can break OTA, turning one failure mode into two.
  //
  // The signature is what makes a bad image unflashable; TLS is what makes the download reach
  // the right server at all. They answer different questions, and this one is reachability.

void doOta(const Job& j) {
  if (ESP.getFreeHeap() < 50000) { otaProgress(j, "failed", 0, "low memory"); return; }

  DEBUG_PRINTF("[ePixC] OTA start v%s <- %s\n", j.version, j.url);
  otaProgress(j, "downloading", 0);

  int status = 0;
  int total = -1;                                   // -1 if chunked/unknown
  PixcHttpsStream* stream = pixcHttpsOpen(j.url, &status, &total, 20000);
  if (stream == nullptr) {
    char e[32];
    if (status > 0) snprintf(e, sizeof(e), "http %d", status);
    else            snprintf(e, sizeof(e), "tls/connect");
    otaProgress(j, "failed", 0, e);
    return;
  }

  if (!Update.begin(total > 0 ? (size_t)total : UPDATE_SIZE_UNKNOWN)) {
    otaProgress(j, "failed", 0, "no space"); pixcHttpsClose(stream); return;
  }

  mbedtls_sha256_context sha;
  mbedtls_sha256_init(&sha);
  mbedtls_sha256_starts(&sha, 0);                   // 0 = SHA-256 (not SHA-224)

  static uint8_t buf[1024];                         // one worker task, one OTA at a time
  size_t written = 0;
  int lastPct = -1;
  bool ok = true;
  const char* failMsg = nullptr;
  // Anti-rollback (S6): find the new image's build descriptor as it streams past.
  pixc::DescScanner desc(pixc_build_desc.magic);

  while (true) {
    const int n = pixcHttpsRead(stream, buf, sizeof(buf));
    if (n < 0) { ok = false; failMsg = "read"; break; }
    if (n == 0) break;                              // end of body, clean or otherwise
    if (Update.write(buf, n) != (size_t)n) { ok = false; failMsg = "flash write"; break; }
    mbedtls_sha256_update(&sha, buf, n);
    written += n;
    if (!desc.found()) {
      desc.feed(buf, n);
      // Found and older: stop now rather than download the rest of an image that will be refused.
      if (desc.found()) {
        const char* why = pixc::otaRefusal(true, desc.build(), desc.security(), PIXC_FW_BUILD, securityFloor);
        if (why != nullptr) { ok = false; failMsg = why; break; }
      }
    }
    if (total > 0) {
      int pct = (int)((written * 90ULL) / (size_t)total);   // 0..90 while downloading
      if (pct != lastPct && pct % 10 == 0) { otaProgress(j, "downloading", pct); lastPct = pct; }
      if (written >= (size_t)total) break;
    }
    vTaskDelay(1);                                  // let IDLE run; the LED loop is on the other core
  }

  // A connection cut mid-image ends the loop exactly like a clean finish. The SHA-256 below would
  // catch it anyway, but "stalled" is a far more useful thing to put in front of support.
  if (ok && !pixcHttpsComplete(stream)) { ok = false; failMsg = "stalled"; }
  pixcHttpsClose(stream);

  uint8_t digest[32];
  mbedtls_sha256_finish(&sha, digest);
  mbedtls_sha256_free(&sha);

  // Integrity first, then provenance. The digest is required: it used to be skipped entirely if the
  // command carried no `sha256`, so a command with the field omitted flashed whatever arrived.
  if (ok) {
    if (strlen(j.sha256) != 64) {
      ok = false;
      failMsg = "no sha256 in command";
    } else {
      char got[65]; hex32(digest, got);
      if (strcasecmp(j.sha256, got) != 0) { ok = false; failMsg = "sha256 mismatch"; }
    }
  }

  if (ok) {
    const char* why = pixc::otaRefusal(desc.found(), desc.build(), desc.security(), PIXC_FW_BUILD, securityFloor);
    if (why != nullptr) { ok = false; failMsg = why; }
  }

  if (ok) {
    const char* sigFail = verifySignature(j.sigUrl, digest);
    if (sigFail != nullptr) { ok = false; failMsg = sigFail; }
  }

  if (!ok) {
    Update.abort();
    DEBUG_PRINTF("[ePixC] OTA failed: %s\n", failMsg ? failMsg : "?");
    otaProgress(j, "failed", 0, failMsg);
    return;
  }

  otaProgress(j, "installing", 95);
  if (!Update.end(true)) {           // commit: set the new image bootable
    char e[40]; snprintf(e, sizeof(e), "finalize %u", Update.getError());
    otaProgress(j, "failed", 0, e);
    return;
  }
  DEBUG_PRINTLN("[ePixC] OTA done; reboot scheduled");
  otaProgress(j, "done", 100);      // the loop publishes it, then reboots
}

void task(void*) {
  for (;;) {
    Job* j = nullptr;
    if (xQueueReceive(jobs, &j, portMAX_DELAY) != pdTRUE || j == nullptr) continue;
    busy = true;
    if (j->kind == Job::Provision) doProvision(*j);
    else                           doOta(*j);
    busy = false;
    free(j);
  }
}

bool start() {
  if (jobs != nullptr) return true;
  jobs = xQueueCreate(2, sizeof(Job*));
  results = xQueueCreate(16, sizeof(Result));
  if (jobs == nullptr || results == nullptr) return false;
  // 10 KB: esp_http_client + an mbedTLS handshake (RSA-4096 chain verify for ISRG Root X1) +
  // ECDSA verify. Internal RAM, not PSRAM: Update.write() disables the flash cache, and a task
  // whose stack lives in PSRAM cannot run while it is off. Core 0 at priority 1, away from the LED
  // loop on core 1.
  return xTaskCreatePinnedToCore(task, "pixc_net", 10240, nullptr, 1, nullptr, 0) == pdPASS;
}

// Hand a job to the worker. False when the worker is busy or the queue is full: the caller retries.
bool submit(const Job& job) {
  if (jobs == nullptr || busy || uxQueueMessagesWaiting(jobs) > 0) return false;
  Job* j = static_cast<Job*>(malloc(sizeof(Job)));
  if (j == nullptr) return false;
  memcpy(j, &job, sizeof(Job));
  if (xQueueSend(jobs, &j, 0) != pdTRUE) { free(j); return false; }
  return true;
}

}  // namespace pixc_net
// AI: end

class PixcConnectBlink : public Usermod {
  private:
    bool _blinkDone = false;   // green blink only on the first connect
    bool _flashing = false;
    bool _announced = false;
    unsigned long _start = 0;
    unsigned long _lastState = 0;
    unsigned long _lastHealth = 0;
    unsigned long _lastPower = 0;
    bool _statePending = false;      // set by onStateChange, drained in loop()
    // Last seen realtimeMode, so a stream starting or stopping publishes immediately instead of
    // waiting for the 5 s timer. WLED does not call onStateChange for realtime lock: the segment
    // config never changes, only what is being drawn over it.
    uint8_t _lastRealtime = 0;
    // Whether the boot event has gone out yet. One per power cycle, not per MQTT reconnect:
    // "this unit restarted" and "this unit lost the broker for a moment" are different facts and
    // support needs to tell them apart.
    bool _bootReported = false;

    // A config push changed the bus width and the re-init has not finished yet. The cloud's record
    // of `led_channels` is written from the announce, so until this goes out the server still
    // believes the device is whatever width it was before — and `led_channels` is the only
    // evidence anywhere that the push actually landed. Set by applyLedWidth(), drained in loop()
    // once WLED::loop() has cleared doInitBusses.
    bool _reannouncePending = false;

    // True when this boot is running an image the bootloader has marked PENDING_VERIFY — i.e. a
    // freshly installed OTA that will be rolled back on the next boot unless this firmware says it
    // is working.
    //
    // With PIXC_CONFIRM_ON_BROKER (D35) nothing confirms the image before this usermod runs, so after
    // an OTA this is true until the image reaches the broker. See confirmImageIfPending().
    bool _awaitingConfirm = false;
    bool _confirmed = false;
    // This boot obtained broker credentials from the API (provisioning 200): the network and TLS
    // work, so a broker that stays unreachable is evidence against the image. See loop().
    bool _gotCredentialsThisBoot = false;

    // Whether the framework this image linked against has bootloader rollback compiled in — a
    // BUILD fact, taken from the prebuilt Arduino framework's sdkconfig, which is the same value
    // CI asserts (.github/workflows/epixc-firmware.yaml, "Check bootloader rollback is compiled
    // in").
    //
    // Reported alongside the runtime state rather than instead of it, because the two answer
    // different questions and were previously conflated: "can this fleet revert at all" is decided
    // at build time, "is this particular boot on probation" is decided at run time, and reading
    // the second as the first makes a device that auto-confirmed look identical to a framework
    // with the option switched off.
    #ifdef CONFIG_APP_ROLLBACK_ENABLE
    static constexpr bool kRollbackSupported = true;
    #else
    static constexpr bool kRollbackSupported = false;
    #endif
    byte _savedCol[4] = {0, 0, 0, 0};
    byte _savedBri = 0;
    uint8_t _savedFx = 0;

    // ePixC API host (provisioned by the app, persisted in usermod config). The
    // device calls GET {apiHost}:{apiPort}/api/v1/provision?mac=... to learn the
    // MQTT broker, then hands off to MQTT.
    String _apiHost = PIXC_API_HOST;
    uint16_t _apiPort = PIXC_API_PORT;
    bool _provisioned = false;          // got the broker from the API yet?
    bool _provisionInFlight = false;    // a provisioning job is with the network worker
    uint8_t _provisionAttempt = 0;      // consecutive failures, for the backoff
    unsigned long _nextProvisionAt = 0; // millis() before which no new attempt is made

    // OTA (cloud-triggered, MQTT-pull). The trigger arrives on `epixc/v1/d/{mac}/ota` and is handed
    // to the network worker (pixc_net) as a self-contained job; progress comes back as results and
    // is published on `.../ota/progress` from loop(). A command while one is running is refused.
    bool _otaRunning = false;
    unsigned long _rebootAt = 0;        // OTA done: reboot once the "done" publish has had a moment

    // True when this image was built with no signing key baked in. Compile-time constant, so the
    // release build pays nothing for it and the branches below vanish.
    //
    // Derived from the key itself, not from EPIXC_OTA_UNSIGNED_DEV_BUILD: the flag says what
    // someone intended, the key says what actually got compiled in, and only the second one
    // decides whether verifySignature() can ever return nullptr. On such an image OTA is not
    // "likely to fail" — every update is refused, permanently, and the only fix is a cable.
    static constexpr bool kOtaDisabled = (sizeof(PIXC_OTA_PUBKEY_PEM) <= 1);

    // The version this firmware reports — to the app, to the cloud, and to whoever is reading a
    // support ticket. An image that can never take an update says so here, because this is the
    // one field every consumer of a device's state already looks at. Without it, a bench build
    // and a shipping build are distinguishable only by reading the binary, and a dev image
    // flashed onto a customer unit would look exactly like a healthy one until the day an update
    // was published and that single device silently refused it.
    static const char* fwVersion() {
      if (!kOtaDisabled) return versionString;
      static char v[WLED_VERSION_MAX_LEN + 16];
      if (v[0] == '\0') snprintf(v, sizeof(v), "%s-UNSIGNED-DEV", versionString);
      return v;
    }

    static constexpr unsigned long kStateIntervalMs  = 5000;
    static constexpr unsigned long kHealthIntervalMs = 30000;
    static constexpr unsigned long kPowerIntervalMs  = 30000;
    // Provisioning retry: 5 s doubling to 5 min, jittered (pixc::backoffWithJitter).
    static constexpr uint32_t kProvisionBaseMs = 5000;
    static constexpr uint32_t kProvisionMaxMs = 300000;
    // A state change can be a slider being dragged. Without a floor, one drag is a
    // publish per frame; with it, the cloud still sees the change within 250 ms.
    static constexpr unsigned long kStateChangeMinMs = 250;

    void publishKind(const char* kind, const char* payload) {
      if (!WLED_MQTT_CONNECTED) return;
      char topic[MQTT_MAX_TOPIC_LEN + 16];
      snprintf(topic, sizeof(topic), "%s/%s", mqttDeviceTopic, kind);
      mqtt->publish(topic, 0, false, payload);
    }

    void publishAnnounce() {
      char buf[224];
      // led_channels, NOT a chip name. hasWhiteChannel() only reveals the channel
      // count; it cannot tell a 5 V WS2812B from a 12 V WS2815. Publishing a guessed
      // chip name meant the device overwrote the strip model the app had set
      // accurately, destroying the one value the server needs to know the voltage.
      // The app owns led_chip; the device owns led_channels, which is what it knows.
      const char* ledChannels = strip.hasWhiteChannel() ? "RGBW" : "RGB";
      snprintf(buf, sizeof(buf),
        "{\"fw_version\":\"%s\",\"fw_build\":%u,\"fw_git\":\"%s\",\"led_channels\":\"%s\",\"led_count\":%u}",
        fwVersion(), (unsigned)PIXC_FW_BUILD, PIXC_FW_GIT, ledChannels, strip.getLengthTotal());
      publishKind("announce", buf);
    }

    // Estimated current draw. AMPS ONLY — deliberately not watts.
    //
    // BusManager::currentMilliamps() is WLED's Automatic Brightness Limiter estimate
    // ("estimate used current from summed colors"); there is no shunt on the board, so
    // this is arithmetic over the framebuffer, not a measurement. Voltage is NOT applied
    // here: the strip could be 5 V, 12 V or 24 V, the device cannot tell, and a
    // hardcoded 5.0 made reported power wrong by up to 4.8x. The server multiplies by
    // the voltage implied by led_chip, so a wrong voltage is a config change instead of
    // a fleet reflash.
    void publishPower() {
      char buf[96];
      snprintf(buf, sizeof(buf), "{\"amps\":%.3f,\"estimated\":true}",
               BusManager::currentMilliamps() / 1000.0f);
      publishKind("power", buf);
    }

    // WLED's name for whatever is streaming, matching the strings its own UI shows so the app and
    // the device's web page never disagree about what took the strip over.
    static const char* realtimeSourceName(uint8_t mode) {
      switch (mode) {
        case REALTIME_MODE_UDP:      return "UDP";
        case REALTIME_MODE_HYPERION: return "Hyperion";
        case REALTIME_MODE_E131:     return "E1.31";
        case REALTIME_MODE_ADALIGHT: return "USB Adalight/TPM2";
        case REALTIME_MODE_ARTNET:   return "Art-Net";
        case REALTIME_MODE_TPM2NET:  return "tpm2.net";
        case REALTIME_MODE_DDP:      return "DDP";
        case REALTIME_MODE_DMX:      return "DMX";
        default:                     return "";
      }
    }

    void publishState() {
      char buf[288];
      Segment& seg = strip.getSegment(strip.getMainSegmentId());
      // `live` is not decoration, and it is not the same question as `on`.
      //
      // While something streams over DDP or E1.31, WLED holds a realtimeLock and draws that
      // instead of the segment. Everything else in this payload — bri, col, fx — is the
      // *configured* state, which is no longer what is on the strip. Without this flag the cloud
      // cannot tell the difference, so the app confidently showed the last colour it set while a
      // PC played video on the wall, and a brightness drag appeared to work and changed nothing
      // anyone could see. Ticket 37.
      //
      // `lor` (WLED's live override) is reported too, because it decides who wins: with an
      // override set, cloud commands do take effect despite the stream.
      snprintf(buf, sizeof(buf),
        "{\"on\":%s,\"bri\":%u,\"seg\":[{\"col\":[[%u,%u,%u,%u]],\"fx\":%u,\"pal\":%u,\"sx\":%u,\"ix\":%u}]"
        ",\"live\":%s,\"live_source\":\"%s\",\"live_override\":%u}",
        (bri > 0 ? "true" : "false"), bri,
        colPri[0], colPri[1], colPri[2], colPri[3], effectCurrent,
        seg.palette, seg.speed, seg.intensity,
        (realtimeMode ? "true" : "false"), realtimeSourceName(realtimeMode),
        (unsigned)realtimeOverride);
      publishKind("state", buf);
    }

    // Something worth writing down happened. Lands in `device_events` via the gateway and is read
    // back by the app's device history.
    //
    // The topic has been ingested since the broker cutover and **nothing has ever published it**,
    // so the table could only ever be empty. Two events to start, both answering the question
    // support actually gets when a customer says "it stopped working": did it restart, and did it
    // lose Wi-Fi.
    void publishEvent(const char* type, const char* extraJson = nullptr) {
      char buf[192];
      if (extraJson != nullptr) {
        snprintf(buf, sizeof(buf), "{\"type\":\"%s\",%s}", type, extraJson);
      } else {
        snprintf(buf, sizeof(buf), "{\"type\":\"%s\"}", type);
      }
      publishKind("event", buf);
    }

    // Why this boot happened, in esp_reset_reason()'s terms. A panic or a brownout loop is the
    // single most useful thing to know about a unit that "keeps going offline", and it is
    // indistinguishable from a Wi-Fi problem from the outside.
    static const char* resetReasonName() {
      switch (esp_reset_reason()) {
        case ESP_RST_POWERON:  return "power_on";
        case ESP_RST_SW:       return "software";
        case ESP_RST_PANIC:    return "panic";
        case ESP_RST_INT_WDT:  return "int_watchdog";
        case ESP_RST_TASK_WDT: return "task_watchdog";
        case ESP_RST_WDT:      return "watchdog";
        case ESP_RST_BROWNOUT: return "brownout";
        case ESP_RST_DEEPSLEEP:return "deep_sleep";
        case ESP_RST_EXT:      return "external";
        default:               return "unknown";
      }
    }

    void publishHealth() {
      char buf[320];
      // Escaped: an SSID is 32 arbitrary bytes, and a `"` or `\` in one made this invalid JSON, so
      // the backend dropped the whole health message (audit C2). 32 bytes escape to at most 192.
      char ssid[200];
      pixc::jsonEscape(WiFi.SSID().c_str(), ssid, sizeof(ssid));
      String ip = WiFi.localIP().toString();
      int signal = constrain(2 * (WiFi.RSSI() + 100), 0, 100);
      snprintf(buf, sizeof(buf),
        "{\"rssi\":%d,\"signal\":%d,\"ssid\":\"%s\",\"ip\":\"%s\",\"free_heap\":%u,\"uptime\":%lu,\"fw_version\":\"%s\"}",
        (int)WiFi.RSSI(), signal, ssid, ip.c_str(),
        (unsigned)ESP.getFreeHeap(),
        (unsigned long)(millis() / 1000), fwVersion());
      publishKind("health", buf);
    }

    // Put the LED bus on the width the cloud says the customer's reel is: "RGB" or "RGBW".
    //
    // The device keeps its own wiring. Pin, length, colour order, reversal, skip, frequency and
    // both current limits are read back off the LIVE buses and handed straight back — the only
    // fields this rewrites are the bus type and the auto-white mode. That is the whole reason the
    // cloud sends a two-value string instead of an `hw.led.ins` array: it cannot express a pin, so
    // it cannot get one wrong. See pixc_led_bus.h.
    //
    // Returns true if a re-init was staged.
    //
    // The equality check at the top is load-bearing, not an optimisation. This runs on EVERY
    // config push, and a config push happens whenever anything about the device changes in the
    // cloud — a rename, a room move, a brightness plan. Re-initialising the buses tears down and
    // rebuilds them (WLED::loop() -> WS2812FX::finalizeInit(), wled00/wled.cpp:217-226), and with
    // `autoSegments` on, makeAutoSegments() clears and rebuilds the segment list
    // (wled00/FX_fcn.cpp:1988-1998). Doing that on every rename would drop a customer's segments
    // because they renamed their lamp. So: same width, no work, no visible event at all.
    bool applyLedWidth(const char* channels) {
      const pixc_led_bus::Width* want = pixc_led_bus::find(channels);
      if (want == nullptr) return false;   // unknown width: leave the strip exactly as it is

      size_t busCount = BusManager::getNumBusses();
      if (busCount == 0) return false;

      // The auto-white mode counts as part of the width, not as a separate preference. It decides
      // where the white byte comes from, and a four-channel bus with the wrong mode is a strip
      // whose white die is driven by the wrong thing — which is a fault of the same kind as not
      // driving it at all.
      //
      // It is also the state some units are already in. The app used to rewrite the bus over the
      // LAN with rgbwm=1 (AUTO_BRIGHTER), which derives white from RGB and *ignores* the app's own
      // white value — so on those units the white control was plumbed end to end and did nothing.
      // Comparing the mode as well as the type is what lets a push correct them; comparing only
      // the type would leave them alone forever, because their type is already right.
      //
      // The cost is that a mode set by hand in WLED's own LED settings page is overwritten by the
      // next cloud push. That is the deliberate consequence of the cloud owning the width.
      bool changed = false;
      for (size_t i = 0; i < busCount; i++) {
        const Bus* bus = BusManager::getBus(i);
        if (bus == nullptr) continue;
        // getType() keeps bit 7 (the off-refresh hack); the width lives in the low seven bits.
        if ((bus->getType() & 0x7F) != want->type ||
            bus->getAutoWhiteMode() != want->autoWhite) { changed = true; break; }
      }
      if (!changed) return false;

      // Rebuild the staged config from the live buses. busConfigs is a leftover-prone global —
      // WLED's own deserializer appends to it without clearing (wled00/cfg.cpp:220-253), so two
      // pushes inside one loop iteration would produce duplicate buses. Clear it first.
      busConfigs.clear();
      for (size_t i = 0; i < busCount; i++) {
        const Bus* bus = BusManager::getBus(i);
        if (bus == nullptr) break;
        uint8_t pins[OUTPUT_MAX_PINS] = {255, 255, 255, 255, 255};
        bus->getPins(pins);
        // Bit 7 back on if this bus needed off-refresh, because BusConfig's constructor reads the
        // flag out of the type byte rather than taking it separately.
        uint8_t type = want->type | (bus->isOffRefreshRequired() ? 0x80 : 0x00);
        busConfigs.emplace_back(type, pins, bus->getStart(), bus->getLength(),
                                bus->getColorOrder(), bus->isReversed(), bus->skippedLeds(),
                                want->autoWhite, bus->getFrequency(), bus->getLEDCurrent(),
                                bus->getMaxCurrent(), bus->getDriverType());
      }
      // Finalisation is deferred to WLED::loop(), which is also where the result gets written to
      // cfg.json (configNeedsWrite). Doing it here would tear the buses down underneath whatever
      // is drawing.
      doInitBusses = true;
      _reannouncePending = true;
      DEBUG_PRINTF("[ePixC] LED bus -> %s (type %u, aw %u)\n",
                   want->channels, (unsigned)want->type, (unsigned)want->autoWhite);
      return true;
    }

    // Apply a config fragment pushed by the cloud over `epixc/v1/d/{mac}/cfg`.
    //
    // A WHITELIST, not WLED's config parser (audit S11). This used to hand the whole payload to
    // deserializeConfig(), which accepts the Wi-Fi list, the access point, the broker and its
    // topics, the LED pins and the power limiter - so anyone who could publish on the device's
    // /cfg (a broker or backend compromise) owned the unit persistently, without the OTA key. And
    // because deserializeConfig() resets keys a fragment omits (gamma, target FPS, global
    // auto-white mode), every legitimate push quietly reset them too.
    //
    // What the backend sends (epixc-backend DeviceService.buildCfg), and all that is applied:
    //   def.bri, def.on      power plan brightness cap and restore-on-power
    //   light.tr.dur         slow-fade, in 100 ms units
    //   pixc.led_channels    "RGB" / "RGBW" - see applyLedWidth() and pixc_led_bus.h
    //   um.PixcConnect.settingsPin   the LAN credential, see applyLanKey()
    // Everything else, including pixc.ind_led / pixc.ind_blink (no indicator LED is fitted), is
    // ignored.
    void applyCfg(const char* payload) {
      DynamicJsonDocument doc(2048);
      if (deserializeJson(doc, payload)) return;
      JsonObject root = doc.as<JsonObject>();
      if (root.isNull()) return;
      bool changed = false;

      JsonObject def = root["def"];
      if (!def.isNull()) {
        if (def["bri"].is<int>()) {
          const int b = def["bri"];
          if (b >= 1 && b <= 255 && briS != b) { briS = (byte)b; changed = true; }
        }
        if (def["on"].is<bool>() && turnOnAtBoot != def["on"].as<bool>()) {
          turnOnAtBoot = def["on"]; changed = true;
        }
      }
      JsonVariant dur = root["light"]["tr"]["dur"];
      if (dur.is<int>()) {
        const int d = dur;
        if (d >= 0 && d <= 655 && transitionDelayDefault != (uint16_t)(d * 100)) {
          transitionDelay = transitionDelayDefault = (uint16_t)(d * 100);
          strip.setTransition(transitionDelayDefault);
          changed = true;
        }
      }
      if (applyLanKey(root["um"]["PixcConnect"]["settingsPin"] | (const char*)nullptr)) changed = true;

      bool busChange = applyLedWidth(root["pixc"]["led_channels"] | (const char*)nullptr);

      // Only write when something changed (the backend re-sends the same fragment for its PIN
      // sweep), and only if the buses are staying put. When they are not, WLED::loop() re-inits
      // them and sets configNeedsWrite itself; serializing now would persist the buses as they are
      // about to stop being (WLED's own deserializer refuses the save for the same reason).
      if (busChange) return;
      if (changed) serializeConfigToFS();
    }

    // Factory reset from the cloud: `<base>/reset` carrying exactly {"reset":true} (epixc-backend
    // services/mqtt RESET_PAYLOAD, QoS 1, never retained). Any other payload is ignored (audit
    // S12): the topic used to wipe on ANY payload, so a stray or retained message was a reset loop.
    // The wipe itself is shared with the LAN and power-cycle paths - wled00/pixc_device.cpp - and is
    // complete: LittleFS formatted, Wi-Fi NVS erased.
    void factoryReset(const char* payload) {
      StaticJsonDocument<64> doc;
      if (deserializeJson(doc, payload)) return;
      JsonVariant v = doc["reset"];
      if (!doc.is<JsonObject>() || !v.is<bool>() || !v.as<bool>()) {
        DEBUG_PRINTLN(F("[ePixC] /reset ignored: payload is not {\"reset\":true}"));
        return;
      }
      pixcRequestFactoryReset("cloud");
    }

    // Report OTA progress to the cloud on `epixc/v1/d/{mac}/ota/progress`. `status`
    // is one of downloading/installing/done/failed (epixc-mqtt treats done|failed
    // as terminal). Failures carry the reason in `err`.
    void publishOtaProgress(const char* jobId, const char* status, int percent, const char* err = nullptr) {
      if (!WLED_MQTT_CONNECTED) return;
      char buf[224];
      if (err && err[0]) {
        char e[64];
        pixc::jsonEscape(err, e, sizeof(e));
        snprintf(buf, sizeof(buf), "{\"job_id\":\"%s\",\"status\":\"%s\",\"percent\":%d,\"error\":\"%s\"}",
                 jobId, status, percent, e);
      } else {
        snprintf(buf, sizeof(buf), "{\"job_id\":\"%s\",\"status\":\"%s\",\"percent\":%d}",
                 jobId, status, percent);
      }
      publishKind("ota/progress", buf);
    }

    // Build and submit the provisioning job. The transport is a COMPILE-TIME decision (founder's
    // call, 2026-08-28, ticket 33): `PixC_V1` has no plaintext path compiled in at all, so no
    // config value an attacker can write produces one. See the provisioning notes above
    // applyProvision().
    void startProvisioning(unsigned long now) {
      if (_apiHost.length() == 0) return;
#ifdef EPIXC_ALLOW_PLAINTEXT_PROVISION
      const bool useTls = (_apiPort == 443);   // PixC_V1_dev only
#else
      const bool useTls = true;
#endif
      pixc_net::Job job = {};
      job.kind = pixc_net::Job::Provision;
      job.tls = useTls;
      snprintf(job.url, sizeof(job.url), "%s://%s:%u/api/v1/provision?mac=%s",
               useTls ? "https" : "http", _apiHost.c_str(), _apiPort, escapedMac.c_str());
      if (pixc_net::submit(job)) {
        _provisionInFlight = true;
      } else {
        _nextProvisionAt = now + 1000;         // worker busy (an OTA?): look again shortly
      }
    }

    void provisionFailed(unsigned long now, const char* why) {
      _provisionInFlight = false;
      const uint32_t wait = pixc::backoffWithJitter(_provisionAttempt, kProvisionBaseMs, kProvisionMaxMs, esp_random());
      if (_provisionAttempt < 16) _provisionAttempt++;
      _nextProvisionAt = now + wait;
      DEBUG_PRINTF("[ePixC] provisioning failed (%s); retry in %u ms\n", why, (unsigned)wait);
    }

    // Ask the ePixC API which broker to use, then point WLED's MQTT at it. The broker is dynamic
    // (the bench Mac's address rotates, and production can move it without reflashing), so it is
    // never hardcoded — always fetched.
    //
    // **This call decides which MQTT broker the device trusts**, which makes it the most
    // security-sensitive request the firmware makes: whoever answers it names the broker, and a
    // wrong answer bypasses both the per-device credential and MQTT TLS at once. Ticket 33.
    //
    // Production therefore goes over **HTTPS with a pinned ISRG Root X1** and refuses on a failed
    // chain. It never falls back to plaintext — a fallback would mean an attacker who can break
    // the TLS connection (trivially, by refusing it) gets the plaintext path back, which is the
    // same as having no TLS at all.
    //
    // Port 80/8080 stays plaintext for bench work. That is deliberate and safe in the shipped
    // build because `default_envs` names only `PixC_V1`, whose compiled default is
    // `api.epixc.in:443`; the LAN address lives in `PixC_V1_dev`, which a release build cannot
    // reach.
    void applyProvision(const pixc_net::Result& r) {
      _provisionInFlight = false;
      _gotCredentialsThisBoot = true;
      _provisionAttempt = 0;
      uint16_t port = r.port ? r.port : PIXC_MQTT_PORT;
#ifdef PIXC_DEV_FORCE_MQTT_PORT
      // Bench: epixc-backend's local stack answers 8883 but its EMQX listens plaintext on 1883.
      port = PIXC_DEV_FORCE_MQTT_PORT;
#endif
#ifndef EPIXC_ALLOW_PLAINTEXT_MQTT
      if (port != 8883) {
        // Not a TLS port. Refused here, loudly, rather than handed to a client that would refuse
        // it anyway and leave the unit quietly offline.
        provisionFailed(millis(), "mqtt_port is not 8883");
        return;
      }
#endif
      const bool changed = strcmp(mqttServer, r.host) != 0 || mqttPort != port;
      strlcpy(mqttServer, r.host, MQTT_MAX_SERVER_LEN + 1);
      mqttPort = port;
      mqttEnabled = true;
      _provisioned = true;
      DEBUG_PRINTF("[ePixC] broker from API: %s:%u (registered=%d)\n", mqttServer, mqttPort, (int)r.registered);
      // Re-point MQTT only when the broker actually changed. Forcing a disconnect on every Wi-Fi
      // reconnect (as this did) restarted a healthy session for nothing (audit P4); the client
      // itself rebuilds when host or port differ (PixcMqttClient::setServer marks it dirty).
      if (changed || !WLED_MQTT_CONNECTED) initMqtt();
    }

    // Results from the network worker, applied on the loop task.
    void drainNetResults(unsigned long now) {
      if (pixc_net::results == nullptr) return;
      pixc_net::Result r;
      for (uint8_t n = 0; n < 4 && xQueueReceive(pixc_net::results, &r, 0) == pdTRUE; n++) {
        switch (r.kind) {
          case pixc_net::Result::ProvisionOk:     applyProvision(r); break;
          case pixc_net::Result::ProvisionFailed: provisionFailed(now, r.err); break;
          case pixc_net::Result::OtaProgress:
            publishOtaProgress(r.jobId, r.status, r.percent, r.err);
            if (strcmp(r.status, "done") == 0) {
              _rebootAt = now + 1500;           // let the QoS0 "done" publish flush first
            } else if (strcmp(r.status, "failed") == 0) {
              _otaRunning = false;
            }
            break;
        }
      }
    }

  public:
    void setup() override {
      // Five short power-ups in a row are the no-app, no-cloud factory reset (wled00/pixc_device).
      pixcBootCounterOnBoot();
      // The anti-rollback floor only ever rises: this image's security version, once it has run.
      {
        Preferences p;
        if (p.begin("pixc_ota", false)) {
          uint32_t floor = p.getUInt("sec", 0);
          if (floor < PIXC_SECURITY_VERSION) { floor = PIXC_SECURITY_VERSION; p.putUInt("sec", floor); }
          pixc_net::securityFloor = floor;
          p.end();
        }
      }
      // The network worker (provisioning, OTA) - off the LED loop. See pixc_net above.
      if (!pixc_net::start()) DEBUG_PRINTLN(F("[ePixC] network worker failed to start"));
      // Say it out loud, once, at boot. The build-time guard in pixc_ota_pubkey.h means nobody
      // reaches this state by accident — only by setting EPIXC_OTA_UNSIGNED_DEV_BUILD — but the
      // image outlives the decision, and the person holding the board later is not necessarily
      // the person who built it.
      if (kOtaDisabled) {
        DEBUG_PRINTLN(F("[ePixC] ********************************************************"));
        DEBUG_PRINTLN(F("[ePixC] *  UNSIGNED DEV BUILD - NO OTA SIGNING KEY COMPILED IN  *"));
        DEBUG_PRINTLN(F("[ePixC] *  Every firmware update WILL BE REFUSED on this unit.  *"));
        DEBUG_PRINTLN(F("[ePixC] *  Not shippable. Do not flash onto a customer device.  *"));
        DEBUG_PRINTLN(F("[ePixC] ********************************************************"));
      }

      // ePixC-AP is a recovery hotspot, not an always-on beacon: once the device
      // joins the home Wi-Fi the AP is torn down (WLED shuts it on connect for
      // any non-ALWAYS behaviour). It only (re)opens when the station can't
      // connect — after the ~30s grace below — so a mispaired/dropped device is
      // still reachable for re-provisioning.
      apBehavior = AP_BEHAVIOR_NO_CONN;
      mqttEnabled = true;

      // Is this boot on probation? Only true when the bootloader actually armed rollback, which
      // makes this a runtime fact rather than a claim about a prebuilt binary: the Tasmota
      // framework this fork used to build against had CONFIG_BOOTLOADER_APP_ROLLBACK_ENABLE off,
      // so the rollback API linked and did nothing.
      esp_ota_img_states_t otaState;
      const esp_partition_t* running = esp_ota_get_running_partition();
      if (running != nullptr && esp_ota_get_state_partition(running, &otaState) == ESP_OK) {
        _awaitingConfirm = (otaState == ESP_OTA_IMG_PENDING_VERIFY);
      }
      // Broker is NOT hardcoded — it is fetched from the ePixC API (see
      // startProvisioning) on every Wi-Fi connect. Only seed the last-resort
      // fallback if a build-time broker was explicitly provided.
      if (strlen(PIXC_MQTT_HOST) > 0 && strlen(mqttServer) == 0) {
        strlcpy(mqttServer, PIXC_MQTT_HOST, MQTT_MAX_SERVER_LEN + 1);
        mqttPort = PIXC_MQTT_PORT;
      }
      // Force the ePixC topic scheme before MQTT connects so WLED subscribes
      // epixc/v1/d/{mac}/api and publishes its LWT under the same prefix.
      // "epixc/v1/d/" (11) + 12-char MAC = 23 chars, within MQTT_MAX_TOPIC_LEN (32).
      // The version lives in the TOPIC, not in the payload: the topic is already the
      // routing key, so the broker ACL, the subscriber and the version all move
      // together, and a device publishing every few seconds carries no extra field.
      snprintf(mqttDeviceTopic, MQTT_MAX_TOPIC_LEN + 1, "epixc/v1/d/%s",
               escapedMac.c_str());

      // WLED core subscribes mqttGroupTopic plus its /col and /api children, and the
      // default is "wled/all" — a channel EVERY device joins, on which one compromised
      // device could command the entire fleet. Nothing in ePixC ever publishes there.
      // The broker ACL also denies wled/#, so this is the first of two layers.
      mqttGroupTopic[0] = 0;

      // The full MAC as the MQTT client id. WLED's default is "WLED-" plus the last three MAC
      // bytes, which collides across Espressif OUIs; the broker then kicks the older session and
      // the two units take turns disconnecting each other. EMQX has no client-id rule of its own
      // (auth is on the username), so the id only has to be unique.
      snprintf(mqttClientID, sizeof(mqttClientID), "epixc-%s", escapedMac.c_str());
    }

    // Called by WLED when the station connects to Wi-Fi — fetch the broker.
    void connected() override {
      _provisioned = false;
      _provisionAttempt = 0;
      _nextProvisionAt = 0;    // provision asap in loop(), on the network worker
    }

    // Persist the ePixC API host/port so the app provisions it once and it
    // survives reboots (cfg.json -> um.PixcConnect.{apiHost,apiPort}).
    void addToConfig(JsonObject& root) override {
      JsonObject top = root.createNestedObject("PixcConnect");
      top["apiHost"] = _apiHost;
      top["apiPort"] = _apiPort;
      // `settingsPin` is deliberately NOT written back. This same function answers
      // `GET /json/cfg`, and echoing the PIN here would publish the credential to exactly the
      // caller it exists to stop. WLED keeps settingsPIN in wsec.json for the same reason, and
      // that is where this one is persisted.
      //
      // That read is NO LONGER UNAUTHENTICATED, as this comment said until 2026-09-05 - the GET
      // gate added with `PIXC_LAN_AUTH` covers `/json` and every sub-path, `cfg` among them
      // (`serveJson` picks the target from the URL, so one handler answers them all). The rule
      // above stands anyway, and deliberately: a credential that is only safe because of a check
      // somewhere else is one flag away from not being safe, and this is the flag.
    }

    bool readFromConfig(JsonObject& root) override {
      JsonObject top = root["PixcConnect"];
      if (top.isNull()) return false;
#ifdef EPIXC_ALLOW_PLAINTEXT_PROVISION
      // Bench builds keep the host configurable, which is the entire reason the dev env exists:
      // the bench Mac's address rotates.
      _apiHost = top["apiHost"] | _apiHost;
      _apiPort = top["apiPort"] | _apiPort;
#else
      // A release unit provisions from the compiled host and nothing else. Founder's call,
      // 2026-08-28, ticket 33.
      //
      // Pinning ISRG Root X1 proves the peer holds a Let's Encrypt certificate. It does NOT
      // prove the peer is ePixC — an attacker with a domain and a free certificate satisfies a
      // root pin completely. Binding to the CA was never the goal; binding to api.epixc.in is,
      // and the only way to do that is to stop letting a config write choose the host.
      //
      // Nothing legitimate is lost: the app writes exactly this value already
      // (`app_config.dart` -> provisionApiHost/provisionApiPort, 443 in a release build), so
      // ignoring the write is a no-op on the real pairing path and a refusal on every other.
      // The keys are still ACCEPTED and still serialized, so an app that writes them gets its
      // 200 and the config round-trips; they simply do not move the host.
#endif

      // `settingsPin` is deliberately NOT read here any more. readFromConfig() is also what
      // POST /json/cfg reaches from the LAN, and the LAN credential must only ever be set by the
      // cloud (applyCfg -> applyLanKey) or at pairing - otherwise one LAN client could change the
      // key and shut every other member out.
      return true;
    }

    // The LAN credential from the cloud (`um.PixcConnect.settingsPin`): since pairing v2 the 32-hex
    // LAN key (the wire name is kept so the rename touches no other repo). The server rotates it when
    // somebody who held it leaves the home. Persisted at once in wsec.json.
    bool applyLanKey(const char* key) {
#ifdef PIXC_LAN_AUTH
      if (key == nullptr || !pixcSetLanKey(key)) return false;
      serializeConfigSec();
      DEBUG_PRINTLN(F("[ePixC] LAN key rotated by the cloud"));
#else
      (void)key;
#endif
      return false;   // already persisted; nothing for serializeConfigToFS()
    }

    // Tell the bootloader this image works, so it stops being a candidate for rollback (D35).
    //
    // "Works" means: it reached the broker. A build that boots but cannot talk to the cloud is the
    // build that should be rolled back, and it is the failure a bad OTA most plausibly produces.
    //
    // Until 2026-09-25 this was a no-op, because two callers confirmed every image first:
    // initArduino() (framework, under CONFIG_APP_ROLLBACK_ENABLE) and WLED's markOTAvalid() at the
    // end of WLED::setup(). With PIXC_CONFIRM_ON_BROKER both are neutralised - the framework's weak
    // verifyRollbackLater() hook is overridden to return true (below, at file scope), and
    // markOTAvalid() is skipped (wled00/wled.cpp) - so a freshly installed image boots
    // PENDING_VERIFY and the bootloader reverts it on the next reset unless this runs first.
    //
    // What reverts it:
    //   - any reset before the broker is reached: a crash, a panic, the 20 s loop watchdog, a
    //     brownout, or the customer switching it off. The last one reverts a good image too; that
    //     costs one re-download (the backend re-offers the release), never a broken unit.
    //   - loop(): credentials fetched over TLS this boot (the network and the API are fine) but no
    //     broker connection kRollbackDeadlineMs after boot. The image is marked invalid and the
    //     unit reboots into the previous one.
    // Bench: time boot-to-broker on a real network, confirm a crash-on-boot image reverts, and
    // confirm a good image survives an OTA followed by a normal power cycle after connecting.
    void confirmImageIfPending() {
      if (!_awaitingConfirm || _confirmed) return;
      _confirmed = true;
      if (esp_ota_mark_app_valid_cancel_rollback() == ESP_OK) {
        DEBUG_PRINTLN("[ePixC] OTA image confirmed; rollback cancelled");
      } else {
        DEBUG_PRINTLN("[ePixC] OTA image confirm FAILED; this image may be rolled back");
      }
    }

    static constexpr unsigned long kRollbackDeadlineMs = 15UL * 60 * 1000;

    void checkRollbackDeadline(unsigned long now) {
      if (!_awaitingConfirm || _confirmed || !_gotCredentialsThisBoot) return;
      if (now < kRollbackDeadlineMs || WLED_MQTT_CONNECTED) return;
      DEBUG_PRINTLN(F("[ePixC] new image never reached the broker: rolling back"));
      _confirmed = true;   // once
      esp_ota_mark_app_invalid_rollback_and_reboot();   // returns only if there is nothing to revert to
    }

    void onMqttConnect(bool /*sessionPresent*/) override {
      _announced = false; // re-announce on every (re)connect

      // First broker connection since power-on is a boot; every later one is a reconnect. The
      // uptime is carried because it turns "it rebooted" into "it rebooted four minutes in",
      // which is the difference between a power problem and a firmware one.
      char extra[256];
      if (!_bootReported) {
        _bootReported = true;
        // Two facts, published separately, because reading one as the other is what hid the
        // problem for as long as it was hidden.
        //
        //   rollback_supported — the linked framework has bootloader rollback compiled in.
        //   rollback_armed     — THIS boot was still on probation by the time the usermod looked.
        //
        // The pair is the diagnostic:
        //   !supported             the fleet cannot revert at all, whatever the code intends.
        //   supported && armed     rollback is real and this boot is an image on trial.
        //   supported && !armed    something confirmed the image before the usermod ran. This is
        //                          the state of every current build — see confirmImageIfPending().
        //
        // Only rollback_armed used to go out, described as "the only honest way to know" whether
        // the bootloader has rollback. It is not, and it never was: it is structurally always
        // false here, so it read as "the framework has the option off" — flatly contradicting the
        // CI gate that asserts it is on, and sending the next person to audit the build when the
        // answer is in the boot order.
        snprintf(extra, sizeof(extra),
                 "\"reason\":\"%s\",\"fw_version\":\"%s\",\"fw_build\":%u,\"rollback_armed\":%s,"
                 "\"rollback_supported\":%s",
                 resetReasonName(), fwVersion(), (unsigned)PIXC_FW_BUILD,
                 _awaitingConfirm ? "true" : "false",
                 kRollbackSupported ? "true" : "false");
        publishEvent("boot", extra);
      } else {
        snprintf(extra, sizeof(extra), "\"uptime\":%lu", (unsigned long)(millis() / 1000));
        publishEvent("reconnect", extra);
      }

      // Reaching the broker is meant to be the proof, and this is where it would be applied.
      // Done after the event publish so the record of this boot exists before the image stops
      // being reversible. Today it is a no-op — read confirmImageIfPending() before changing
      // anything here, including the placement of this call.
      confirmImageIfPending();

      // Subscribe the ePixC control subtopics the core doesn't handle. `/api`
      // (state commands) is subscribed by WLED core; `/cfg` carries config
      // fragments (power plan, restore-on-power, default brightness, slow-fade)
      // and `/reset` triggers a factory wipe.
      if (mqtt != nullptr) {
        String base = mqttDeviceTopic;
        // QoS 1 on all three, matching what the backend publishes (services/mqtt/src/mqtt.rs:
        // /cfg, /ota and /api all go out AtLeastOnce). A subscription grants min(pub, sub), so a
        // QoS 0 subscription silently downgraded every command: /cfg carries the rotated settings
        // PIN (D305), /ota a job the backend waits on, /reset the owner's wipe.
        mqtt->subscribe((base + "/cfg").c_str(), 1);
        mqtt->subscribe((base + "/reset").c_str(), 1);
        mqtt->subscribe((base + "/ota").c_str(), 1);
      }

      if (!_blinkDone) {
        _blinkDone = true;
        memcpy(_savedCol, colPri, 4);
        _savedBri = bri;
        _savedFx = effectCurrent;
        colPri[0] = 0; colPri[1] = 255; colPri[2] = 0; colPri[3] = 0;
        effectCurrent = FX_MODE_STATIC;
        bri = 255;
        colorUpdated(CALL_MODE_DIRECT_CHANGE);
        _start = millis();
        _flashing = true;
      }
    }

    bool onMqttMessage(char* topic, char* payload) override {
      // WLED has already stripped `mqttDeviceTopic` from `topic` (wled00/mqtt.cpp), so what arrives
      // here is "/cfg", not "epixc/v1/d/<mac>/cfg". This used to strstr() for the FULL topic inside
      // the stripped one, which can never match: cloud config, factory reset and OTA were all
      // silently dead (audit S1). The classification is exact and host-tested - test/pixc/.
      switch (pixc::classifyTopic(topic, mqttDeviceTopic)) {
        case pixc::Topic::Cfg:
          applyCfg(payload);
          return true;
        case pixc::Topic::Reset:
          factoryReset(payload);
          return true;
        case pixc::Topic::Ota:
          stageOta(payload);
          return true;
        case pixc::Topic::None:
          break;
      }
      return false;
    }

    // Copy an OTA command into a self-contained job for the network worker.
    void stageOta(const char* payload) {
      DynamicJsonDocument doc(768);
      if (deserializeJson(doc, payload)) return;
      pixc_net::Job job = {};
      job.kind = pixc_net::Job::Ota;
      strlcpy(job.jobId, doc["job_id"] | "", sizeof(job.jobId));
      strlcpy(job.url, doc["url"] | "", sizeof(job.url));
      strlcpy(job.version, doc["version"] | "", sizeof(job.version));
      strlcpy(job.sha256, doc["sha256"] | "", sizeof(job.sha256));
      // The signature the image has to carry. The gateway has always sent this field and the
      // firmware ignored it, which is why an unsigned image was applied without complaint.
      strlcpy(job.sigUrl, doc["sig_url"] | "", sizeof(job.sigUrl));
      if (job.url[0] == 0) return;
      // The job id is echoed into JSON on ota/progress; the backend drops a progress whose id is
      // not a UUID anyway, so anything else is refused here rather than escaped.
      for (const char* c = job.jobId; *c; c++) {
        if (!isxdigit((unsigned char)*c) && *c != '-') { job.jobId[0] = 0; break; }
      }
      if (_otaRunning || !pixc_net::submit(job)) {
        publishOtaProgress(job.jobId, "failed", 0, "busy");
        return;
      }
      _otaRunning = true;
    }

    void loop() override {
      const unsigned long now = millis();
      pixcDeviceLoop();   // clears the power-up counter at 10 s; runs a pending factory reset
      checkRollbackDeadline(now);
      drainNetResults(now);
      if (_rebootAt != 0 && (long)(now - _rebootAt) >= 0) { _rebootAt = 0; doReboot = true; }

      if (_flashing && (now - _start > 3000)) {
        memcpy(colPri, _savedCol, 4);
        bri = _savedBri;
        effectCurrent = _savedFx;
        colorUpdated(CALL_MODE_DIRECT_CHANGE);
        _flashing = false;
      }

      // Once on Wi-Fi, fetch the broker from the ePixC API on the network worker, retrying with
      // backoff and jitter until it sticks. The broker is never hardcoded.
      if (!_provisioned && !_provisionInFlight && WiFi.status() == WL_CONNECTED &&
          (long)(now - _nextProvisionAt) >= 0) {
        startProvisioning(now);
      }

      if (!WLED_MQTT_CONNECTED) return;

      if (!_announced) {
        _announced = true;
        publishAnnounce();
        publishState();
        publishPower();
        _lastState = now;
        _lastHealth = now;
        _lastPower = now;
      }
      // A bus-width change has finished re-initialising. Say so.
      //
      // `led_channels` is device-reported by design — it is the one part of the strip's identity
      // the device can actually observe (strip.hasWhiteChannel()). That property is now also the
      // only receipt that a width push worked: the cloud asked for RGBW, and this is the device
      // answering with what it ended up on. If the re-init fell back to a placeholder bus for want
      // of memory (wled00/FX_fcn.cpp:1231-1236) the announce says RGB, and the disagreement is
      // visible in the devices table instead of only on the customer's wall.
      //
      // Gated on doInitBusses because WLED::loop() runs the re-init AFTER usermods
      // (wled00/wled.cpp:82 vs :217), so on the iteration the push arrives the buses are still the
      // old ones. One extra loop is nothing; announcing the old width would be wrong forever.
      if (_reannouncePending && !doInitBusses) {
        _reannouncePending = false;
        publishAnnounce();
      }

      // A state change reported by WLED — an Alexa command, a LAN call, a physical
      // button, a preset firing. Publishing only on the timer meant any of those was
      // invisible to the cloud for up to kStateIntervalMs, so the app could show
      // lights on moments after they were turned off by voice.
      // A stream starting or stopping is a state change WLED never reports, because the segment
      // config is untouched — only what is drawn over it changes. Publishing on the 5 s timer alone
      // meant up to five seconds of the app showing a colour that is not on the wall.
      if (realtimeMode != _lastRealtime) {
        _lastRealtime = realtimeMode;
        _statePending = true;
      }
      if (_statePending && now - _lastState >= kStateChangeMinMs) {
        _statePending = false;
        _lastState = now;
        publishState();
      }
      if (now - _lastState >= kStateIntervalMs) {
        _lastState = now;
        publishState();
      }
      if (now - _lastHealth >= kHealthIntervalMs) {
        _lastHealth = now;
        publishHealth();
      }
      if (now - _lastPower >= kPowerIntervalMs) {
        _lastPower = now;
        publishPower();
      }
    }

    // WLED fires this on every state change, from led.cpp. Only a flag is set: this
    // runs inside the state-change path, and publishing from here would put MQTT I/O
    // on it. loop() does the actual publish.
    void onStateChange(uint8_t) override {
      _statePending = true;
    }

    uint16_t getId() override { return USERMOD_ID_UNSPECIFIED; }
};

static PixcConnectBlink pixc_connect_blink;
REGISTER_USERMOD(pixc_connect_blink);
