#pragma once

// AI: below section was generated by an AI
//
// Pure decision logic for the ePixC usermod, kept free of Arduino, WLED and ESP-IDF headers so it
// compiles on a desktop and is exercised by the host tests in test/pixc/ (run: test/pixc/run.sh).
//
// The rule for what lives here: anything whose failure is silent on the device. S1 of the
// 2026-09 firmware audit was a string comparison that could never match - the usermod compared the
// FULL topic after WLED had already stripped the device prefix - and it disabled cloud config,
// factory reset and OTA for every unit without a single error message. A one-line host test would
// have caught it. Functions that touch hardware stay in the .cpp; the arithmetic and parsing they
// depend on comes here, where it can be proved.

#include <stddef.h>
#include <stdint.h>
#include <string.h>

namespace pixc {

// ---------------------------------------------------------------------------------------------
// MQTT topic routing
// ---------------------------------------------------------------------------------------------

enum class Topic : uint8_t { None, Cfg, Reset, Ota };

// Classify a topic as delivered to Usermod::onMqttMessage().
//
// WLED's MQTT handler (wled00/mqtt.cpp, onMqttMessage) strips `mqttDeviceTopic` before calling
// the usermods, so a subscription to `epixc/v1/d/<mac>/cfg` arrives here as "/cfg". A topic that
// did NOT start with the device prefix arrives unstripped. Both forms are accepted, and each is
// compared EXACTLY: "/ota/progress" is a topic this device publishes and must never be mistaken
// for an OTA command, and "/cfgX" is nothing.
//
// `deviceTopic` may be null or empty, in which case only the stripped form can match.
inline Topic classifyTopic(const char* topic, const char* deviceTopic) {
  if (topic == nullptr) return Topic::None;
  const char* rest = topic;
  const size_t baseLen = deviceTopic ? strlen(deviceTopic) : 0;
  if (baseLen > 0 && strncmp(topic, deviceTopic, baseLen) == 0) rest = topic + baseLen;
  if (strcmp(rest, "/cfg") == 0) return Topic::Cfg;
  if (strcmp(rest, "/reset") == 0) return Topic::Reset;
  if (strcmp(rest, "/ota") == 0) return Topic::Ota;
  return Topic::None;
}


// ---------------------------------------------------------------------------------------------
// Secret redaction for debug output
// ---------------------------------------------------------------------------------------------

namespace detail {
inline char lower(char c) { return (c >= 'A' && c <= 'Z') ? static_cast<char>(c - 'A' + 'a') : c; }

inline bool keyEquals(const char* k, size_t n, const char* lit) {
  size_t i = 0;
  for (; i < n && lit[i] != 0; i++) if (lower(k[i]) != lit[i]) return false;
  return i == n && lit[i] == 0;
}

inline bool keyContains(const char* k, size_t n, const char* lit) {
  const size_t m = strlen(lit);
  for (size_t i = 0; i + m <= n; i++) {
    size_t j = 0;
    while (j < m && lower(k[i + j]) == lit[j]) j++;
    if (j == m) return true;
  }
  return false;
}

inline bool keyEndsWith(const char* k, size_t n, const char* lit) {
  const size_t m = strlen(lit);
  return n >= m && keyEquals(k + n - m, m, lit);
}
}  // namespace detail

// True for a JSON key whose value is a credential: the settings PIN (`pin`, `settingsPin`), Wi-Fi
// and MQTT pre-shared keys (`psk`), passwords (`pass`, `password`, `pwd`, `mqttPass`, `otaPass`),
// and anything named like a key, token or secret. Case-insensitive. Deliberately broad: a false
// positive costs one starred-out debug value, a false negative prints a customer's Wi-Fi password.
inline bool isSecretKey(const char* k, size_t n) {
  using namespace detail;
  return keyEndsWith(k, n, "pin") || keyContains(k, n, "psk") || keyContains(k, n, "pass") ||
         keyContains(k, n, "pwd") || keyContains(k, n, "secret") || keyContains(k, n, "token") ||
         keyEquals(k, n, "key") || keyEndsWith(k, n, "_key") || keyEndsWith(k, n, "apikey");
}

// Overwrite, in place, the value of every secret-named key in a JSON text with '*' - string values
// between their quotes, bare values (numbers, true/false) up to the next delimiter. The text keeps
// its length and structure, so a debug print still shows which fields arrived. Not a JSON parser:
// it only has to be right for the keys that matter and never read past the terminator.
inline void redactJsonSecrets(char* s) {
  if (s == nullptr) return;
  char* p = s;
  while (*p) {
    if (*p != '"') { p++; continue; }
    char* keyStart = ++p;                              // candidate key: scan to its closing quote
    while (*p && *p != '"') { if (*p == '\\' && p[1]) p++; p++; }
    if (!*p) return;
    const size_t keyLen = static_cast<size_t>(p - keyStart);
    p++;                                               // past the closing quote
    char* q = p;
    while (*q == ' ' || *q == '\t' || *q == '\r' || *q == '\n') q++;
    if (*q != ':') continue;                           // it was a string value, not a key
    q++;
    while (*q == ' ' || *q == '\t' || *q == '\r' || *q == '\n') q++;
    if (!isSecretKey(keyStart, keyLen)) { p = q; continue; }
    if (*q == '"') {
      q++;
      while (*q && *q != '"') {
        if (*q == '\\' && q[1]) { *q++ = '*'; }
        *q++ = '*';
      }
      p = *q ? q + 1 : q;
    } else if (*q != '{' && *q != '[') {
      while (*q && *q != ',' && *q != '}' && *q != ']' && *q != ' ' && *q != '\n') *q++ = '*';
      p = q;
    } else {
      p = q;                                           // an object/array under a secret name: descend
    }
  }
}

// ---------------------------------------------------------------------------------------------
// Retry timing
// ---------------------------------------------------------------------------------------------

// Exponential backoff with jitter: the attempt-th retry waits a random time in [d/2, d], where
// d = min(baseMs * 2^attempt, maxMs). `rnd` is any 32-bit random value (esp_random() on the device).
//
// The jitter is the point. After a broker restart or a neighbourhood power cut the whole fleet
// disconnects in the same second; with a fixed retry they all come back in the same second too,
// each doing an RSA-4096 chain verification, and the broker sees a thundering herd on every retry.
// Spreading each wave over half its interval turns that spike into a ramp.
inline uint32_t backoffWithJitter(uint8_t attempt, uint32_t baseMs, uint32_t maxMs, uint32_t rnd) {
  uint64_t d = baseMs;
  for (uint8_t i = 0; i < attempt && d < maxMs; i++) d <<= 1;
  if (d > maxMs) d = maxMs;
  const uint64_t half = d / 2;
  const uint64_t span = d - half + 1;
  return static_cast<uint32_t>(half + (rnd % span));
}

}  // namespace pixc
// AI: end
