#!/usr/bin/env python3
# AI: below section was generated by an AI
"""ePixC factory provisioning: the per-unit hotspot password and the label that carries it.

Pairing v2 (vault: 05-Firmware/Pairing and LAN security v2, "Hotspot"). Each controller gets a
random 10-character password from [a-z2-9], stored in NVS namespace `pixc_fac`, key `ap_psk`. The
firmware names its hotspot `ePixC-XXXX` (last four MAC hex digits, upper case) and opens it with
this password; a release build with no factory password opens no hotspot at all. A factory reset
keeps `pixc_fac`, so the printed label stays valid for the life of the unit.

This tool:
  1. reads the unit's MAC over USB (esptool read_mac), or takes --mac;
  2. draws the password with the OS CSPRNG (secrets);
  3. builds an NVS partition image for the `nvs` partition (0x9000, 0x5000 bytes, from
     tools/WLED_ESP32_8MB_epixc.csv) with esp-idf-nvs-partition-gen;
  4. writes it with esptool unless --no-flash;
  5. prints the label: SSID, password, and the Wi-Fi QR payload the app scans,
     WIFI:T:WPA;S:ePixC-XXXX;P:<psk>;;
  6. appends one CSV row (mac, ssid, psk, time) to --log, which the production line keeps: the
     backend never sees the hotspot password, and the label is the only other copy.

Flashing the NVS image REPLACES the whole nvs partition. Run it on a fresh board, before the
firmware first boots, or after an erase - never on a unit in a customer's hands.

Requirements: pip install esp-idf-nvs-partition-gen esptool

Examples:
  tools/factory_provision.py --port /dev/cu.usbserial-0001 --log factory_units.csv
  tools/factory_provision.py --mac aabbccddeeff --no-flash --out /tmp/nvs.bin   # dry run
"""
import argparse
import csv
import datetime
import os
import re
import secrets
import subprocess
import sys
import tempfile

ALPHABET = "abcdefghijklmnopqrstuvwxyz23456789"
PSK_LEN = 10
NVS_OFFSET = "0x9000"
NVS_SIZE = "0x5000"


def read_mac(port):
    out = subprocess.run([sys.executable, "-m", "esptool", "--port", port, "read_mac"],
                         capture_output=True, text=True, check=True).stdout
    m = re.search(r"MAC:\s*([0-9a-fA-F:]{17})", out)
    if not m:
        sys.exit("could not read the MAC:\n" + out)
    return m.group(1).replace(":", "").lower()


def hotspot_name(mac):
    return "ePixC-" + mac[-4:].upper()


def build_nvs(psk, out_path):
    with tempfile.TemporaryDirectory() as d:
        csv_path = os.path.join(d, "nvs.csv")
        with open(csv_path, "w", newline="") as f:
            w = csv.writer(f)
            w.writerow(["key", "type", "encoding", "value"])
            w.writerow(["pixc_fac", "namespace", "", ""])
            w.writerow(["ap_psk", "data", "string", psk])
        try:
            subprocess.run([sys.executable, "-m", "esp_idf_nvs_partition_gen", "generate",
                            csv_path, out_path, NVS_SIZE], check=True, capture_output=True, text=True)
        except FileNotFoundError:
            sys.exit("pip install esp-idf-nvs-partition-gen")
        except subprocess.CalledProcessError as e:
            sys.exit("NVS image generation failed:\n" + e.stdout + e.stderr)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--port", help="serial port of the unit (to read its MAC and flash)")
    ap.add_argument("--mac", help="12 hex digits, instead of reading it from --port")
    ap.add_argument("--psk", help="use this password instead of drawing one (re-labelling only)")
    ap.add_argument("--out", help="where to write the NVS image (default: a temp file)")
    ap.add_argument("--no-flash", action="store_true", help="build and print only")
    ap.add_argument("--log", help="CSV file to append mac,ssid,psk,time to")
    args = ap.parse_args()

    if args.mac:
        mac = args.mac.replace(":", "").lower()
    elif args.port:
        mac = read_mac(args.port)
    else:
        sys.exit("give --port or --mac")
    if not re.fullmatch(r"[0-9a-f]{12}", mac):
        sys.exit("MAC must be 12 hex digits")

    psk = args.psk or "".join(secrets.choice(ALPHABET) for _ in range(PSK_LEN))
    if not (8 <= len(psk) <= 63) or not all(0x20 <= ord(c) <= 0x7e for c in psk):
        sys.exit("password must be 8-63 printable ASCII characters (WPA2)")
    ssid = hotspot_name(mac)

    out_path = args.out or os.path.join(tempfile.gettempdir(), "epixc_nvs_%s.bin" % mac)
    build_nvs(psk, out_path)

    if not args.no_flash:
        if not args.port:
            sys.exit("--port is needed to flash (or pass --no-flash)")
        subprocess.run([sys.executable, "-m", "esptool", "--chip", "esp32s3", "--port", args.port,
                        "write_flash", NVS_OFFSET, out_path], check=True)

    if args.log:
        new = not os.path.exists(args.log)
        with open(args.log, "a", newline="") as f:
            w = csv.writer(f)
            if new:
                w.writerow(["mac", "ssid", "psk", "provisioned_at"])
            w.writerow([mac, ssid, psk, datetime.datetime.now(datetime.timezone.utc).isoformat()])

    print("NVS image : %s%s" % (out_path, "" if args.no_flash else " (flashed at %s)" % NVS_OFFSET))
    print()
    print("---- label ----")
    print("Wi-Fi     : %s" % ssid)
    print("Password  : %s" % psk)
    print("QR        : WIFI:T:WPA;S:%s;P:%s;;" % (ssid, psk))
    print("MAC       : %s" % mac)


if __name__ == "__main__":
    main()
# AI: end
